### PR TITLE
master-qa-30045

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-30045

CC @brandizzi

### CODE REVIEW

**Comment by vicnate5** [comment]
Needs calendar fixes. use the attached bundle, want to know if it works.

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by vicnate5** [comment]
Test passed when I ran it against a bundle without the fix, can you look into this?

**Comment by brandizzi** [comment]
Hey Victor, Clarissa.

It is probably my fault. I've sent a PR to BChan, but just closed it a bit later, to add tests: https://github.com/brianchandotcom/liferay-portal/pull/45975#issuecomment-270632387

However, he reopened and merged it. I guess the thought the PR was automatically closed due to unrelated errors.

Sorry for this distraction!

**Pull request closed without merging**
