### PR TITLE
LRQA-43788 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-43788

### CODE REVIEW

**Comment by john-co** [comment]
CI tests found here: https://github.com/john-co/liferay-portal/pull/9

**Comment by john-co** [comment]
CC @iovaneale

**Comment by john-co** [comment]
This is to fix failing poshi tests run against Commerce app that Alessandro was experiencing. Alessandro verified that this path is compatible and fixes the issue on commerce.

**Comment by vicnate5** [comment]
This might win the award for more hardcore path we have in all of poshi. Bravo.

**Comment by patriciajeanperez** [comment]
This may have fixed at least 7 of our failing Knowledge Base tests. +1 for winning the award for most hardcore path. 👍 Thanks, @john-co!

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/63585
https://github.com/brianchandotcom/liferay-portal-ee/pull/21842

**Comment by john-co** [comment]
> This may have fixed at least 7 of our failing Knowledge Base tests. +1 for winning the award for most hardcore path.  Thanks, @john-co!

@iovaneale actually came up with this epic path, so you can thank him! :)

**Pull request closed without merging**
