### PR TITLE
LPS-74571 Address add panel search bar issue in compat layer

### PR DESCRIPTION
**Pull request by Robert-Frampton**
/cc @jpince @vicnate5 @jbalsas

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
@pat270

**Comment by Robert-Frampton** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:stop

**Comment by Robert-Frampton** [comment]
ci:retest

**Pull request closed without merging**
