### PR TITLE
master-qa-53825

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-53823
https://issues.liferay.com/browse/LRQA-53825

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
Fixed a wrong command in expect file by force-pushing.

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 This looks good, the only thing missing is checking the output of the default `help` command (no argument)

From the test plan: "Type "help" to get available upgrade and verify commands."
Make sure commands are listed when the user types this.

**Comment by zhangyan0701** [comment]
Resend in [vicnate5#1470](https://github.com/vicnate5/liferay-portal/pull/1470),

**Pull request closed without merging**
