### PR TITLE
LRQA-68347 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-68347

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:stable

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@kyle-miho This broke again already, please regen again.

We must get this in Stable ASAP

**Comment by vicnate5** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test:stable

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@kyle-miho Still fails here, can you confirm this passes locally?

**Comment by kyle-miho** [comment]
@vicnate5 i cant run unit tests in portal-impl locally, i get this error
 [junit] SurvivorRatio (65536) must be less than or equal to ergonomic SurvivorRatio maximum (1024)
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.

But it looks like it broke again in between the time CI rebased this pull and i updated the regen

**Comment by kyle-miho** [comment]
ci:test:stable
I re-regened the configurations

**Comment by vicnate5** [comment]
@kyle-miho This really changes this much?

**Comment by kyle-miho** [comment]
@vicnate5 there was a new regen yesterday but not when the PR ran, could you try running this unit test locally (if it works for you?)
in portal-impl run `ant test-class -Dtest.class=ConfigurationEnvBuilderTest`

**Comment by kyle-miho** [comment]
ci:test:stable

**Comment by kyle-miho** [comment]
ci:test:stable

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
BChan wanted to just ignore this test for now
https://github.com/brianchandotcom/liferay-portal/pull/104044

Once the improvements are in, we can re-visit adding this to relevant/stable.

**Pull request closed without merging**
