### PR TITLE
LRQA-67793 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-67793

### CODE REVIEW

**Comment by kyle-miho** [comment]
cc: fyi @ruben-pulido Now when making a change to a Configuration file, run ant generate-configuration-env in your liferay-portal base directory to regenerate modules/configuration-env.txt I'm not sure why this wasn't caught in the PR I'll have to look into it later

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
