### PR TITLE
LRQA-52004 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Testing new changes

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
@koor4356 can you take a look at this, I had the test run smoke, but it failed

Why is it `http://[::1]` instead of `http://[0:0:0:0:0:0:0:1]`?

**Comment by koor4356** [comment]
http://[0:0:0:0:0:0:0:1] is the same as http://[::1]. The configuration on hosts file is [::1]. I will look into why smoke failed. Thanks!

**Comment by koor4356** [comment]
New pr https://github.com/vicnate5/liferay-portal/pull/1338

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
