### PR TITLE
Lps 186793

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
relevant didn't run much, triggered `startup` so we can confirm. The upgrade suite did not show the error.

**Comment by vicnate5** [comment]
@shuyangzhou No issues found, this should be good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135981

**Pull request closed without merging**
