### PR TITLE
LRQA-64637 Account for all runtime scenarios

### PR DESCRIPTION
**Pull request by vicnate5**
@kyle-miho @koor4356

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
@koor4356 If 5 or less of the tests here fail, please trigger a ci forward on in your morning.

**Comment by koor4356** [comment]
okay, Thanks!

**Comment by koor4356** [comment]
ci:forward

**Comment by vicnate5** [comment]
https://github.com/vicnate5/liferay-portal/pull/1671

**Pull request closed without merging**
