### PR TITLE
LPS-158742 Test automation for "Add context thread information on upgrade logs for LXC to identify those lines"

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-158742

Tests passed: https://github.com/susanchen3/liferay-portal/pull/85#issuecomment-1298863934 
Relevant passed: https://github.com/susanchen3/liferay-portal/pull/85#issuecomment-1295741989

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@susanchen3 I have a some questions on this:
1. The original ticket [LPS-155004](https://issues.liferay.com/browse/LPS-155004) had 5 test scenarios, I only see 3 tests here, are the other 2 covered elsewhere? Where are we covering the custom name `upgrade.log.context.name=ExampleText`?
2. The original ticket specifies needing to add a custom `portal-log4j-ext.xml`, is that not needed anymore?
3. `upgradeLog=upgradeLog` seems like a strange logging for a user to find in the log file, can you gist me an example of what the log file looks like under this test?

I also would like to request some small changes:
1. Use 7.3.10 for this test. We want to stick to using DXP versions by default since we rarely will have a real user going from CE to DXP via upgrade.
2. We can also probably restrict this test to mysql only. Since the logging behavior isn't affected by DB type.
3. Nice job finding and using `copy-log-file`. Can you change the file name from `${liferayHome}/log` to `${liferayHome}/liferay.log` so it follows a normal file naming scheme?
4. If the custom log4j isn't needed, we should drop the "XML" name from the test names. If we do need that, we should call it "CustomLog4j" instead of "XML", because XML is just a type of file, we should name it based on its purpose, not its file type.

**Comment by susanchen3** [comment]
1. According to the ticket and the test map, the other two scenarios are covered by [backend tests](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-log4j-test/src/testIntegration/java/com/liferay/portal/log4j/test/PortalLog4jTest.java). See `testLogOutputWithLogContextUpgradeEnabledClassWhenUpgrading` and `testLogOutputWithLogContextUpgradeNotEnabledClassWhenUpgrading`. 
     - Will update test using ExampleText, I didn't realize default is upgradeLog.

2. `portal-log4j-ext.xml` is needed, which is added through `property log.context.enabled = "true"`. 2/3 of these tests are testing without it the xml enabled so I didn't call that property. 
3. https://gist.githubusercontent.com/susanchen3/10be1e69605081d5ea34a21dddee015d/raw/6c207426178f78db90a2ad54ac4a598be6087924/upgradeLog=upgradeLog

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
See my changes in the new PR. Let me know if you have any questions.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/125735

**Comment by susanchen3** [comment]
@vicnate5 is [LogOutputReturnsMarkedWithDefaultName](https://github.com/brianchandotcom/liferay-portal/pull/125735/files#diff-26b012c1c44f9ec4773aedb599713d7fe3bd1d3bd0443abcf0e699a82c243609R25-R31) needed? I think this scenario is covered by [testLogOutputWithLogContextUpgradeEnabledClassWhenUpgrading](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-log4j-test/src/testIntegration/java/com/liferay/portal/log4j/test/PortalLog4jTest.java#L279-L291).

If not, I can remove it. 
If it is, I can update the description on the test.

**Comment by vicnate5** [comment]
@susanchen3 let's keep it so we have a functional test for this to compare with the custom logging name. Good job paying attention to the integration level coverage.

**Pull request closed without merging**
