### PR TITLE
master-qa-61863

### PR DESCRIPTION
**Pull request by zhangyan0701**
Can be backported to 7.3.x

https://issues.liferay.com/browse/LRQA-61863
https://issues.liferay.com/browse/LRQA-62413
https://issues.liferay.com/browse/LRQA-62495

Tested in pr https://github.com/zhangyan0701/liferay-portal/pull/243, all tests passed.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
