### PR TITLE
LRQA-72463 | master

### PR DESCRIPTION
**Pull request by Hijky**
This is only for master

https://issues.liferay.com/browse/LRQA-72463

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
I fixed SF failures and resent: https://github.com/Hijky/liferay-portal/pull/10

**Comment by Hijky** [comment]
I will re-pull it tomorrow

**Comment by Hijky** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
See https://github.com/vicnate5/liferay-portal/pull/1943

**Pull request closed without merging**
