### PR TITLE
master-qa-112

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-112

CC @leoadb

### CODE REVIEW

**Comment by ctampoya** [comment]
@vicnate5 Added Forms test fix 16f18c3

**Comment by ctampoya** [comment]
ci:retest

**Comment by vicnate5** [comment]
Thanks @ctampoya!

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/49784

**Pull request closed without merging**
