### PR TITLE
LRQA-58263 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-58263

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by dantewang** [comment]
Fetched

**Comment by vicnate5** [comment]
@dantewang FYI this test fails on Websphere (I also reproduce the failure locally). When executing the groovy script the Server Admin crashes.
```
ERROR [liferay/monitoring-2][ParallelDestination:59] Unable to process message {destinationName=liferay/monitoring, response=null, responseDestinationName=null, responseId=null, payload=[{displayName=Server Administration, portletId=com_liferay_server_admin_web_portlet_ServerAdminPortlet, requestType=ACTION, {attributes=null, companyId=20099, groupId=20118, description=null, duration=0, name=com_liferay_server_admin_web_portlet_ServerAdminPortlet, namespace=com.liferay.monitoring.Portlet, requestStatus=null, stopWatch=0:00:00.025, timeout=0, user=20127}}, {referer=http://localhost:8080/group/control_panel/manage?p_p_id=com_liferay_server_admin_web_portlet_ServerAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_server_admin_web_portlet_ServerAdminPortlet_mvcRenderCommandName=%2Fserver_admin%2Fview&_com_liferay_server_admin_web_portlet_ServerAdminPortlet_cur=0&_com_liferay_server_admin_web_portlet_ServerAdminPortlet_tabs1=script&_com_liferay_server_admin_web_portlet_ServerAdminPortlet_delta=0, remoteAddr=172.17.0.1, requestURL=, statusCode=0, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0, {attributes=null, companyId=20099, groupId=20118, description=null, duration=27, name=/c/portal/layout, namespace=com.liferay.monitoring.Portal, requestStatus=ERROR, stopWatch=0:00:00.027, timeout=-1, user=20127}}, {referer=http://localhost:8080/group/control_panel/manage?p_p_id=com_liferay_server_admin_web_portlet_ServerAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_server_admin_web_portlet_ServerAdminPortlet_mvcRenderCommandName=%2Fserver_admin%2Fview&_com_liferay_server_admin_web_portlet_ServerAdminPortlet_cur=0&_com_liferay_server_admin_web_portlet_ServerAdminPortlet_tabs1=script&_com_liferay_server_admin_web_portlet_ServerAdminPortlet_delta=0, remoteAddr=172.17.0.1, requestURL=, statusCode=0, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0, {attributes=null, companyId=20099, groupId=0, description=null, duration=31, name=/group/control_panel/manage, namespace=com.liferay.monitoring.Portal, requestStatus=ERROR, stopWatch=0:00:00.031, timeout=-1, user=null}}], values={defaultLocale=en_US, companyId=20099, groupId=0, principalName=20127, permissionChecker=com.liferay.portal.kernel.util.TransientValue@6b35485c, siteDefaultLocale=en_US, themeDisplayLocale=en_US}}
com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.NullPointerException
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.NullPointerException
	at com.liferay.portal.monitoring.internal.statistics.portlet.PortletStatistics.processDataSample(PortletStatistics.java:112)
	at com.liferay.portal.monitoring.internal.statistics.portlet.CompanyStatistics.processDataSample(CompanyStatistics.java:209)
	at com.liferay.portal.monitoring.internal.statistics.portlet.ServerStatistics.processDataSample(ServerStatistics.java:118)
	at com.liferay.portal.monitoring.internal.statistics.portlet.ServerStatistics.processDataSample(ServerStatistics.java:35)
	at com.liferay.portal.monitoring.internal.messaging.MonitoringMessageListener.processDataSample(MonitoringMessageListener.java:93)
	at com.liferay.portal.monitoring.internal.messaging.MonitoringMessageListener.doReceive(MonitoringMessageListener.java:121)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
	... 5 more
2020-04-29 22:29:49.495 WARN  [WebContainer : 2][code_jsp:142] {code="500", msg="java.lang.NoClassDefFoundError: javax.servlet.http.Cookie", uri=/group/control_panel/manage}
java.lang.NoClassDefFoundError: javax.servlet.http.Cookie
	at java.lang.Class.getDeclaredMethodsImpl(Native Method)
	at java.lang.Class.getDeclaredMethods(Class.java:942)
	at java.lang.Class.getMethodSet(Class.java:1374)
	at java.lang.Class.getMethods(Class.java:1315)
	at org.codehaus.groovy.reflection.stdclasses.CachedSAMClass.getSAMMethod(CachedSAMClass.java:164)
	at org.codehaus.groovy.reflection.ClassInfo.isSAM(ClassInfo.java:359)
	at org.codehaus.groovy.reflection.ClassInfo.createCachedClass(ClassInfo.java:349)
	at org.codehaus.groovy.reflection.ClassInfo.access$700(ClassInfo.java:41)
	at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:497)
	at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:488)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:36)
	at org.codehaus.groovy.reflection.ClassInfo.getCachedClass(ClassInfo.java:111)
	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:110)
	at org.codehaus.groovy.reflection.ParameterTypes.getParametersTypes0(ParameterTypes.java:81)
	at org.codehaus.groovy.reflection.ParameterTypes.getParameterTypes(ParameterTypes.java:67)
	at org.codehaus.groovy.reflection.CachedMethod.compareToCachedMethod(CachedMethod.java:157)
	at org.codehaus.groovy.reflection.CachedMethod.compareTo(CachedMethod.java:140)
```

Adding the commits from https://github.com/tinatian/liferay-portal/pull/1796 to test if it still fails on Websphere after the fix.

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by dantewang** [comment]
@vicnate5 I see, the test on Websphere fails with and without Jorge's pull. I'll take a look at the error when I have time.

**Comment by vicnate5** [comment]
@dantewang Thanks, created a ticket https://issues.liferay.com/browse/LPS-112840

**Comment by ChiZelin** [comment]
Hi @vicnate5 and @zhangyan0701,

I can't visit portal home page when running websphere in debug mode. So I can't fix [LPS-112840](https://issues.liferay.com/browse/LPS-112840) now.

But I found we can get the path by 'PropsUtil'. And the value returned by `PortalUtil#getGlobalLibDir` comes from `PropsUtil`. So you can use the following script to check global lib dir:
```
import com.liferay.portal.kernel.util.PropsKeys;
import com.liferay.portal.util.PropsUtil;

out.println(PropsUtil.get(PropsKeys.LIFERAY_LIB_GLOBAL_DIR));
```
And @zhangyan0701, Could you please take a look at the problem about debugging on websphere？

Thanks.

**Comment by ChiZelin** [comment]
Thanks for @zhangyan0701's careful check.
I forgot `Paths`.
The correct script is:
```
import com.liferay.portal.kernel.util.PropsKeys;
import com.liferay.portal.util.PropsUtil;
import java.nio.file.Paths;

out.println(Paths.get(PropsUtil.get(PropsKeys.LIFERAY_LIB_GLOBAL_DIR)));
```

**Comment by vicnate5** [comment]
Websphere debug known issue: https://issues.liferay.com/browse/LPS-91368

**Pull request closed without merging**
