### PR TITLE
LPS-101178 Configure admin.email.from.address, announcements.email.to.address and mail.send.blacklist properties in tests to avoid WARN traces

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-101178

This is a similar solution than previous pr https://github.com/vicnate5/liferay-portal/pull/1265 but instead of just configuring the email addresses, I am also changing `mail.send.blacklist` value to empty list, in order to avoid WARN traces

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
Hi @vicnate5 

That one is caused by a different change, see: https://issues.liferay.com/browse/LPS-100651

In that LPS in changed default trace level from ERROR to WARN in order to warn to the final customer in case they don't have SMTP server properly configured.

Can we handle this one separately in a different LPS?

Thank you

**Comment by vicnate5** [comment]
@jorgediaz-lr Fine with me.

Pushed to Shuyang
https://github.com/shuyangzhou/liferay-portal/pull/8223

**Comment by vicnate5** [comment]
New ticket: https://issues.liferay.com/browse/LPS-101460

**Pull request closed without merging**
