### PR TITLE
LRQA-72313 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-72313

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:help

**Comment by vicnate5** [comment]
@catarineaguiar Is there a reason that we are not doing step 5 on https://issues.liferay.com/browse/LRQA-72313? The main goal of the test is to confirm that the database is not populated, so we should be checking the the DB tables. We have the ability in Poshi to query the database. See usages of `SQL.executeMySQLStatement` in other testcases.

Also, I think we should improve the naming of the tests in this testcase file to note the primary goal of the tests.

This test rename to `CanEnableOrDisableDatabasePersistence`
Previous test (CanBeEnabledOrDisabledThroughSystemSettingsAndOSGIConfigFile) rename to `CanEnableOrDisableAudit`

Make sure value of `test.name.skip.portal.instance` is matching test name(it currently isn't matching for the other test)

Please make the changes and you can send back to me directly.

**Comment by catarineaguiar** [comment]
see https://github.com/vicnate5/liferay-portal/pull/2047

**Pull request closed without merging**
