### PR TITLE
master-qa-63981

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-63981

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 I found a more basic problem with the logic when I tried to backport this. The weird thing is that we actually fixed this for 7.2.x and earlier last year https://github.com/vicnate5/liferay-portal-ee/commit/5d2ed1aeb9d5939351ba2a381f2ab892637f6317 but it was not ported to master (7.3 at the time).

See https://github.com/brianchandotcom/liferay-portal/pull/98291

**Pull request closed without merging**
