### PR TITLE
master-qa-23158

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-23158

### CODE REVIEW

**Comment by ctampoya** [comment]
cc @sharonchoi

**Comment by sharonchoi** [comment]
looks legit :+1:

**Comment by vicnate5** [comment]
so legit

@sharonchoi @ctampoya

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37629

**Pull request closed without merging**
