### PR TITLE
JDK 17 - main CI

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by tinatian** [comment]
ci:report:2532519151

**Comment by vicnate5** [comment]
rebased on master

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by tinatian** [comment]
ci:reoport:2533947192

**Comment by tinatian** [comment]
ci:report:2533947192

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by julschong** [comment]
ci:report:2536283270

**Comment by vicnate5** [comment]
JDK 21 now available on CI

triggered at https://github.com/tinatian/liferay-portal/pull/2574

**Pull request closed without merging**
