### PR TITLE
master-qa-79002

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-79002

Case passed here: https://testray.liferay.com/home/-/testray/case_results/2151608252

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Added to https://github.com/liferay-core-infra/liferay-portal/pull/3036

**Pull request closed without merging**
