### PR TITLE
LPS-190280 Temp remove upgrade tests from running on DB2 11.5

### PR DESCRIPTION
**Pull request by susanchen3**
https://liferay.atlassian.net/browse/LPS-190280

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@susanchen3 We are planning on re-enabling in the future right?

Instead we should just comment out the batch with `#` syntax. Will give visibility to it is disabled but will be turned on again.

**Comment by susanchen3** [comment]
@vicnate5 ah right. Updated :)

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/137781

**Pull request closed without merging**
