### PR TITLE
LRQA-80807, LRQA-80804 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://liferay.atlassian.net/browse/LRQA-80807
https://liferay.atlassian.net/browse/LRQA-80804

Tests passed in https://github.com/zhangyan0701/liferay-portal/pull/551.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@zhangyan0701 Couple questions on this:

1. We are following the steps in the ticket https://liferay.atlassian.net/browse/LPS-114409, but what happens if a config file is in the subfolder? Is it read? Do we have any existing tests for this?
2. How did you create the jsp fragment artifacts? Do we have any other existing jsp fragment bundles in our source code?

**Comment by zhangyan0701** [comment]
> 1. We are following the steps in the ticket https://liferay.atlassian.net/browse/LPS-114409, but what happens if a config file is in the subfolder? Is it read? Do we have any existing tests for this?
> 2. How did you create the jsp fragment artifacts? Do we have any other existing jsp fragment bundles in our source code?

@vicnate5 
1. It is NOT read unless this property `module.framework.configs.dir` is set and point to the subfolder. We have a test to cover this property: `ModuleFrameworkPath#CustomPathDeploy`, just the custom path used in this test is not a subfolder under /osgi/configs.
2. I got the artifact directly from the LPP ticket that linked in the bug ticket. It can be created following this article https://help.liferay.com/hc/en-us/articles/360029122451-JSP-Overrides-Using-OSGi-Fragments. I didn't find out existing one in our source code.

**Comment by vicnate5** [comment]
@zhangyan0701 Rename `com.liferay.blade.module.jsp.override` to `com.liferay.login.web.jsp.override.sample` and then you can send to BChan.

He might ask us to move the module into `modules/apps`, but since it is only 2 files, maybe he will accept it as part of dependencies.

**Pull request closed without merging**
