### PR TITLE
LPS-174081 Uniform Automated tests | Optimize Upgrades test suite

### PR DESCRIPTION
**Pull request by lucasperj**
Issue link : https://issues.liferay.com/browse/LPS-174081

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
@vicnate5 , I have removed the quarantine property from Auto Upgrade tests X>7.4 at [b37556](https://github.com/vicnate5/liferay-portal/pull/2277/commits/b4b75dc996436fc43bdf5f9f81e2bbc171b37556),  since the proterty, in the way that was being used, was basically doing nothing, since on our test.properties we are defining the quarantine tickets to dont run using the portal.acceptance, not the portal.upstream. And they are consistenly passing, exception for ViewPortalSmokeArchiveAutoUpgrade6130 that it's still failling due to a bug ticket. 
Do you prefer to removing the property (unused) or fix the property of the tests and really make them quarantined? Thanks.

**Comment by lucasperj** [comment]
Seems that the auto upgrade tests that have failed are only due to known issues, and the others have passed as expected.

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/131525

**Pull request closed without merging**
