### PR TITLE
LRQA-68915

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance

**Comment by koor4356** [comment]
@vicnate5 Those failures have nothing to do with the changes I made. One is a bug (LPS-135976) & the other looks random. I suggest you push these changes. Thanks!

**Comment by vicnate5** [comment]
ci:test:acceptance
Rerunning since that DB partition validator failure might be an unrelated regression

**Comment by vicnate5** [comment]
@koor4356 Here is the regression ticket https://issues.liferay.com/browse/LPS-136103

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/104694

**Pull request closed without merging**
