### PR TITLE
LPS-70895 SF

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
Hey @vicnate5 , the original fix is in the commit https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/82. Could you re-run CI there as soon as this is merged? Thanks!

**Comment by marcellustavares** [comment]
@pedroqueiroz94, please add these commits into the original pull. I can send to @vicnate5 for his review.

Thanks

**Comment by marcellustavares** [comment]
ci:close

**Comment by pedroqueiroz94** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@pedroqueiroz94 See https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/101. We need this merged first unfortunately. Keep this pull open.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/47913

**Pull request closed without merging**
