### PR TITLE
LRQA-72463 | master

### PR DESCRIPTION
**Pull request by Hijky**
This is only for master

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test

**Comment by Hijky** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@Hijky Run SF locally using these instructions https://github.com/Hijky/liferay-portal/pull/10#issuecomment-1012691434 and just commit the changes.

Once SF passes, run ci test upstream-functional

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
@vicnate5 I Run SF locally and commit the changes, but it also error

**Comment by vicnate5** [comment]
ci:test:upstream-functional

**Comment by vicnate5** [comment]
@Hijky Can you check the results here, is there any issues in the tests that upload files?

**Comment by Hijky** [comment]
@vicnate5 I check results, but no issues about upload files.

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
rebased and resent
https://github.com/vicnate5/liferay-portal/pull/1950

**Pull request closed without merging**
