### PR TITLE
LRQA-14646

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-14646

### CODE REVIEW

**Comment by vicnate5** [comment]
@ctampoya 

Could you add this to PGCalendar.testcase instead of a new file?

**Comment by ctampoya** [comment]
force pushed to origin

**Comment by vicnate5** [comment]
@ctampoya Per our conversation:

**Comment by vicnate5** [comment]
Pushed to BChiu. https://github.com/brianchiu/liferay-portal/pull/584

**Pull request closed without merging**
