### PR TITLE
master-qa-28035

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-28035

### CODE REVIEW

**Comment by ctampoya** [comment]
Hey @thiago-rocha After comparing this pull to master, there seems to be no difference in how the styling editions of a Paragraph Field are reflected. It is automatically reflected on both master and on this pull. Could you clarify what styling editions were added to this pull? The only issue that we found was that when you edit a table cell, a new added table does not appear automatically on the form builder (refer to the gif).

Steps to Reproduce Issue:
1. Add a Form Text field
2. Under Body Text, click the (+) to add a styling edition
3. Click on table icon
4. Assert table is automatically shown on builder
5. Add a second table
6. Assert it is added on builder
7. Add text to one of the table cells
8. Add a third table
*Result:* The third table is not shown on the builder until one of the cells is edited.
 
onlyissue

cc @brunobasto @fernandosouza @vicnate5

**Comment by fernandosouza** [comment]
Hi, @ctampoya. 

Try to make a text **bold** by selecting it and clicking the **B** icon. On master the bold style does not reflect on the form builder.

**Comment by ctampoya** [comment]
Hey @fernandosouza @thiago-rocha! So I found a bug with the 'link' styling edition. Could you take another look at this please? 

Steps to reproduce:
1. Add a Form Text field
2. Input a Form Text title
3. Input "Google" as the body text
4. Double click on "Google" > Select 'Link' icon
5. Type in "www.google.com" as the default link
6. Save link
7. Save Form Text Field
8. Click on Form Text field to open side bar
9. Assert linked page was not saved
10. Double click on "Google" and link it to www.google.com again
11. Add some text after "Google" (ie "Click this link")
12. Save field
13. Edit Form Text field > Assert Link has been saved

*Result:* A linked page should be saved with our without additional text. When the Form is added to a Form portlet, you will see that the link works only if there is some text after the linked page.

cc @brunobasto @vicnate5

**Comment by brunobasto** [comment]
Hey @ctampoya,

Was this issue introduced with this PR?

Thanks for looking into it.

**Comment by fernandosouza** [comment]
@brunobasto My guess is this PR supposed to fix that.

@diogo-lins, could you take a look, please?

**Comment by ctampoya** [comment]
Hi @brunobasto I assumed this pull fixed all the styling editions for a Form Text. The same issue is present at master head.

**Comment by brunobasto** [comment]
Got it. Sorry for the confusion. I assumed something else from your report. @diogo-lins is looking into it. 

Thanks

**Comment by ctampoya** [comment]
Thanks @brunobasto

**Pull request closed without merging**
