### PR TITLE
Lps 126777

### PR DESCRIPTION
**Pull request by shuyangzhou**
@vicnate5 can you add the com.liferay.document.library.asset.auto.tagger.tensorflow.internal.configuration.TensorFlowImageAssetAutoTagProviderDownloadConfiguration.config preparation to CI setup script, and point it to a local "file:///" url?
The local file should be downloaded from https://repository.liferay.com/nexus/service/local/artifact/maven/redirect?r=third-party&g=com.liferay&a=org.tensorflow.models.inception&v=5h&e=jar , I think Chas should make a copy of it somewhere else where we host CI files.

You can confirm whether it is working by running ```modules/apps/document-library/document-library-asset-auto-tagger-tensorflow-test/src/testIntegration/java/com/liferay/document/library/asset/auto/tagger/tensorflow/test/DLFileEntryAutoTaggerTest.java```

Thanks!

### CODE REVIEW

**Comment by vicnate5** [comment]
@shuyangzhou Do we ever expect to updated this jar? if so how often?

**Comment by shuyangzhou** [comment]
I actually have no idea. @4lejandrito when was the last time you updated it?

**Comment by 4lejandrito** [comment]
Hi @vicnate5, @shuyangzhou,

We have never updated it. I don't think our PM has plans to invest in this module for now so I would say we won't be updating it in a while.

**Comment by vicnate5** [comment]
Manual testing passed

1. Local File:
```
INFO  [com.liferay.document.library.asset.auto.tagger.tensorflow.test-executor-thread][JarUtil:82] Downloading file:/opt/dev/projects/github/org.tensorflow.models.inception-5h.jar to /opt/dev/projects/github/bundles/tomcat-9.0.37/temp/20210128220135738YTPTLWQS
INFO  [com.liferay.document.library.asset.auto.tagger.tensorflow.test-executor-thread][JarUtil:90] Downloaded file:/opt/dev/projects/github/org.tensorflow.models.inception-5h.jar to /opt/dev/projects/github/bundles/tomcat-9.0.37/temp/20210128220135738YTPTLWQ
````
2. Expected `FileNotFoundException` thrown if the file path is incorrect.

3. Using network file:
```
INFO  [com.liferay.document.library.asset.auto.tagger.tensorflow.test-executor-thread][JarUtil:82] Downloading https://repository.liferay.com/nexus/service/local/artifact/maven/redirect?r=third-party&g=com.liferay&a=org.tensorflow.models.inception&v=5h&e=jar to /opt/dev/projects/github/bundles/tomcat-9.0.37/temp/20210128221742167IILTSSGN
INFO  [com.liferay.document.library.asset.auto.tagger.tensorflow.test-executor-thread][JarUtil:90] Downloaded https://repository.liferay.com/nexus/service/local/artifact/maven/redirect?r=third-party&g=com.liferay&a=org.tensorflow.models.inception&v=5h&e=jar to /opt/dev/projects/github/bundles/tomcat-9.0.37/temp/20210128221742167IILTSSGN
```

@shuyangzhou  Can I forward this once I finish confirming with CI we are safe to use their cache?

**Comment by shuyangzhou** [comment]
Yes, please, thanks @vicnate5 !

**Comment by vicnate5** [comment]
@shuyangzhou Errors on the previous PR when this test ran on CI. It does use a local cache, but it failed to download
```
     [exec] com.liferay.document.library.asset.auto.tagger.tensorflow.test.DLFileEntryAutoTaggerTest > testAutoTagsABMPImage STARTED
     [exec] 2021-01-27 12:19:24.756 INFO  [com.liferay.document.library.asset.auto.tagger.tensorflow.test-executor-thread][JarUtil:82] Downloading https://mirrors/repository.liferay.com/nexus/service/local/artifact/maven/redirect?r=third-party&g=com.liferay&a=org.tensorflow.models.inception&v=5h&e=jar to /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.37/temp/20210127121924739DAEILUCF
     [exec] 2021-01-27 12:19:24.776 ERROR [com.liferay.document.library.asset.auto.tagger.tensorflow.test-executor-thread][SynchronousDestinationTestRule$TestSynchronousDestination:398] Unable to process message {destinationName=liferay/tensorflow_model_download, response=null, responseDestinationName=null, responseId=null, payload=null, values={defaultLocale=en_US, companyId=20101, groupId=0, principalName=20129, permissionChecker=com.liferay.portal.kernel.util.TransientValue@5646c609}}
     [exec] com.liferay.portal.kernel.messaging.MessageListenerException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:41)
     [exec] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
     [exec] 	at com.liferay.portal.kernel.test.rule.SynchronousDestinationTestRule$TestSynchronousDestination.send(SynchronousDestinationTestRule.java:395)
     [exec] 	at com.liferay.portal.messaging.internal.DefaultMessageBus.sendMessage(DefaultMessageBus.java:265)
     [exec] 	at com.liferay.document.library.asset.auto.tagger.tensorflow.internal.configuration.persistence.listener.TensorFlowImageAssetAutoTagProviderCompanyConfigurationModelListener.onAfterSave(TensorFlowImageAssetAutoTagProviderCompanyConfigurationModelListener.java:59)
     [exec] 	at com.liferay.portal.configuration.persistence.internal.ConfigurationPersistenceManager.store(ConfigurationPersistenceManager.java:257)
     [exec] 	at org.apache.felix.cm.impl.persistence.PersistenceManagerProxy.store(PersistenceManagerProxy.java:203)
     [exec] 	at org.apache.felix.cm.impl.ConfigurationImpl.update(ConfigurationImpl.java:461)
     [exec] 	at org.apache.felix.cm.impl.ConfigurationAdapter.update(ConfigurationAdapter.java:145)
     [exec] 	at com.liferay.portal.configuration.test.util.ConfigurationTestUtil._updateProperties(ConfigurationTestUtil.java:178)
     [exec] 	at com.liferay.portal.configuration.test.util.ConfigurationTestUtil.saveConfiguration(ConfigurationTestUtil.java:77)
     [exec] 	at com.liferay.portal.configuration.test.util.ConfigurationTemporarySwapper.<init>(ConfigurationTemporarySwapper.java:44)
     [exec] 	at com.liferay.document.library.asset.auto.tagger.tensorflow.test.DLFileEntryAutoTaggerTest._withTensorflowAutoTagProviderEnabled(DLFileEntryAutoTaggerTest.java:159)
     [exec] 	at com.liferay.document.library.asset.auto.tagger.tensorflow.test.DLFileEntryAutoTaggerTest.testAutoTagsABMPImage(DLFileEntryAutoTaggerTest.java:75)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
     [exec] 	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
     [exec] 	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
     [exec] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
     [exec] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
     [exec] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
     [exec] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
     [exec] 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
     [exec] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
     [exec] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
     [exec] 	at java.net.URL.openStream(URL.java:1045)
     [exec] 	at com.liferay.portal.util.JarUtil.downloadAndInstallJar(JarUtil.java:85)
     [exec] 	at com.liferay.document.library.asset.auto.tagger.tensorflow.internal.util.InceptionModelUtil.download(InceptionModelUtil.java:48)
     [exec] 	at com.liferay.document.library.asset.auto.tagger.tensorflow.internal.messaging.TensorflowModelDownloadMessageListener.doReceive(TensorflowModelDownloadMessageListener.java:54)
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48)
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34)
     [exec] 	... 40 more
```

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 did you change the URL for the configuration? How does it know to use a local file? The error message says it is still downloading from network "https://mirrors/repository.liferay.com/nexus/service/local/artifact/maven/redirect?r=third-party&g=com.liferay&a=org.tensorflow.models.inception&v=5h&e=jar" and on CI we reroute the url to mirrors. And this jar does not seem to be on mirrors.

**Comment by vicnate5** [comment]
@pyoo47 Is mirrors the cache you mentioned for our nexus? Any idea why it might be missing this jar?

**Comment by vicnate5** [comment]
Opened ticket for IT https://issues.liferay.com/browse/IS-2203

**Comment by vicnate5** [comment]
See https://github.com/vicnate5/liferay-portal/pull/1620

**Pull request closed without merging**
