### PR TITLE
LPS-180625 Uniform Automated tests | Add assert tree image on homepage after clean cache at Continuous Upgrade tests to cover LPS-180446

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:upgrade:nocompile

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@lucasperj Shouldn't this have failed due to https://issues.liferay.com/browse/LPS-180446? The fix isn't merged yet.

**Comment by lucasperj** [comment]
I have tested manually also with Auto Upgrade, and also failed.
Running the test locally I got the error
Selection_392

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:close

**Pull request closed without merging**
