### PR TITLE
LPS-166087, LPS-166760, LPS-158742 Fix API calls when using DB Partitioning

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-166087
- Fix log in JSON macros
- API calls were unable to grab users from isolated instances
- Tested here: https://github.com/susanchen3/liferay-portal/pull/91

https://issues.liferay.com/browse/LPS-166760
- Isolate Segmentation tests
- Tests were passing locally > maybe bad cleanup on CI?
- Tested here: https://github.com/susanchen3/liferay-portal/pull/92#issuecomment-1308160608

https://issues.liferay.com/browse/LPS-158742
- Update upgrade context log test description

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
I want to test this against non-DB partition

**Comment by susanchen3** [comment]
I don't think relevant will run anything cause I only made Poshi changes. I tested the changes on acceptance wiithout db partition here: https://github.com/susanchen3/liferay-portal/pull/91#issuecomment-1308060530. Didn't see any regressions.

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
Nice job on this @susanchen3

**Pull request closed without merging**
