### PR TITLE
LRQA-74248

### PR DESCRIPTION
**Pull request by koor4356**
- LRQA-74248 Enable DB2 11.5 testing
- LRQA-74248 Do not commit

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:environments:nocompile

**Comment by vicnate5** [comment]
@koor4356 Can you run this with all the integration tests on DB2 11.1 and 11.5? I want to know if we can get more stability out of 11.5 for the backend tests.

**Comment by koor4356** [comment]
ci:test:backend:nocompile

**Comment by koor4356** [comment]
ci:test:backend:nocompile

**Comment by vicnate5** [comment]
Is CI working on this now? The DB2 11.5 backend tests aren't running...

**Comment by koor4356** [comment]
I have reached out to Charlotte Wong about this. So I am waiting for her feedback.

**Comment by koor4356** [comment]
@vicnate5 
Charlotte Wong still working on this. "I am still working on it, I am not sure why it cannot find that directory, it is there in the db2 11.5.6.0 image!"

**Pull request closed without merging**
