### PR TITLE
LPS-67961 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@thiago-rocha Is there visual UI changes on this pull?

**Comment by thiago-rocha** [comment]
@vicnate5  Nops

**Comment by vicnate5** [comment]
Full check for regressions https://github.com/vicnate5/liferay-portal/pull/543

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/43122

**Pull request closed without merging**
