### PR TITLE
LRQA-75244

### PR DESCRIPTION
**Pull request by koor4356**
- LRQA-75244 Move backend upgrade core tests to upgrades team
- LRQA-75244 Do not commit

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:upgrade:nocompile

**Comment by vicnate5** [comment]
@koor4356 Doesn't look like this worked, I see upgrade tests under "Portal Services" still

**Comment by koor4356** [comment]
Let's talk about this during our meeting. I don't really know the implementation of this functionality or how it should work. Thanks!

**Comment by vicnate5** [comment]
This won't work until LRCI-1398 is completed, but it doesn't hurt to merge this now

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/119091

**Pull request closed without merging**
