### PR TITLE
LPS-65078 Workflow is not usable after upgrade from ee-6.1 to 7.0 DXP

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares Thanks for sending to me, This fixes the failure during upgrade.
Unfortunately, the user still cannot fully approve pending content. Content shows as "Pending (Approved)" in the UI on approval. The assets are still considered Pending in their respective portlets. This also applies to new content added post-upgrade.

We could consider this a different issue if you want, and I can open a new ticket.

Errors are thrown on assignment/approval (_could be unrelated issue as the Kaleo Forms asset shows "null" title_)
```
22:11:02,546 ERROR [http-nio-8080-exec-8][JDBCExceptionReporter:234] Unknown column 'kaleoproce0_.uuid_' in 'field list'
22:11:02,548 ERROR [http-nio-8080-exec-8][BeanPropertiesImpl:415] jodd.bean.BeanException: Simple property not found: asset-title. Invalid property: DefaultWorkflowTask#asset-title (DefaultWorkflowTask#asset-title, forced=false)
jodd.bean.BeanException: Simple property not found: asset-title. Invalid property: DefaultWorkflowTask#asset-title (DefaultWorkflowTask#asset-title, forced=false)
	at jodd.bean.BeanUtilBean.getSimpleProperty(BeanUtilBean.java:154)
	at jodd.bean.BeanUtilBean.getIndexProperty(BeanUtilBean.java:246)
	at jodd.bean.BeanUtilBean.getProperty(BeanUtilBean.java:499)
	at jodd.bean.BeanUtil.getProperty(BeanUtil.java:108)
	at com.liferay.portal.bean.BeanPropertiesImpl.getObject(BeanPropertiesImpl.java:412)
	at com.liferay.portal.bean.BeanPropertiesImpl.getObject(BeanPropertiesImpl.java:403)
	at com.liferay.portal.kernel.bean.BeanPropertiesUtil.getObject(BeanPropertiesUtil.java:167)
	at com.liferay.taglib.ui.SearchContainerColumnTextTag.doEndTag(SearchContainerColumnTextTag.java:68)
...
```

**Comment by marcellustavares** [comment]
Yeah, I've noticed that too @vicnate5. @leoadb is fixing the kaleo forms upgrade and we should get rid of this issue along. 

Can you try to approve another asset?


Thanks

**Comment by vicnate5** [comment]
I was unable to approve Blogs or Web Content

**Comment by marcellustavares** [comment]
Ok @vicnate5, I'll wait for the kaleo forms fix. I'll resend this.

**Pull request closed without merging**
