### PR TITLE
LPS-181239 Uniform Automated test | Add login fallback to stabilize test on CI

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:license

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Nice job @lucasperj 

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/133557

**Comment by vicnate5** [comment]
I fixed the commit message so SF won't complain

**Pull request closed without merging**
