### PR TITLE
LRQA-66285 LRQA-71989 LRQA-71994

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:acceptance-functional:nocompile

**Comment by vicnate5** [comment]
@Hijky The test is inputting the wrong date. I suspect there is a difference between the Tomcat server time and the Poshi time.

**Comment by Hijky** [comment]
The local running case is to get the current time in the portal, I remember it is UTC time, and the date is the current date

> @Hijky The test is inputting the wrong date. I suspect there is a difference between the Tomcat server time and the Poshi time.

The local running case is to get the current time in the portal, I remember it is UTC time, and the date is the current date

**Comment by vicnate5** [comment]
I am looking into this in detail, there might actually be a bug here.

**Comment by vicnate5** [comment]
ci:test:acceptance-functional:nocompile

**Comment by vicnate5** [comment]
ci:test:acceptance-functional:nocompile

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
@Hijky I found that https://issues.liferay.com/browse/LPS-116111 keeps causing the new test to fail. I ignored the asserts for the default company until that is fixed. 

Please see all my commits here under LRQA-66285 (I added some unrelated other commits on top) and let me know if any of the changes do not make sense or are not clear.

CC @zhangyan0701

**Comment by vicnate5** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/110577

**Pull request closed without merging**
