### PR TITLE
master-qa-77116

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-77116

Test passed in https://github.com/zhangyan0701/liferay-portal/pull/506.

### CODE REVIEW

**Comment by vicnate5** [comment]
@zhangyan0701 Couple questions on this:

1. Since we already set the exact file name in a test variable, why do we need to regex to find the file? `-Dlpkg.symbolic.1=Gogo -Dlpkg.symbolic.2=Impl`|
2. What ended up being the problem that lead to this passing locally but failing on CI originally?

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Couple questions on this:
> 
> 1. Since we already set the exact file name in a test variable, why do we need to regex to find the file? `-Dlpkg.symbolic.1=Gogo -Dlpkg.symbolic.2=Impl`|
> 2. What ended up being the problem that lead to this passing locally but failing on CI originally?

Hi @vicnate5 
1. I was trying using the whole name when calling ant target, but the name couldn't be read as it contains spaces and "-". I couldn't find out a way that could resolve this, I tried using `'''` or transferring them, but neither could work. I am not sure if this a limitation of the function AndComand. So I used regex instead. I made some changes, now there is only one variable needed to find the file instead of two.
2. I found out tickets https://issues.liferay.com/browse/POSHI-502 and https://issues.liferay.com/browse/LPS-178014, I think this is the same issue as them. Before when I got the error, I set property `ci.retries.disabled` to true in test, then I remove the property like Susan did and rerun tests for several times, I didn't see the error again.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you refactor the exiting `move-file` ant target instead of creating a new one?

I don't even see the old target used, but the move you are doing is not specific to LPKG files, so it could be reused.

**Pull request closed without merging**
