### PR TITLE
LRQA-76535 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://liferay.atlassian.net/browse/LRQA-76535

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
@vicnate5 The properties are also updated here.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/137222

**Pull request closed without merging**
