### PR TITLE
LRQA-36543 | master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-36543

### CODE REVIEW

**Comment by vicnate5** [comment]
@pcwhite on viewTableDefinitionPublishedViaKDCP, does the test confirm the definition is published? I am worried this would give a false positive if: 
1) The definition did not get published 
2) The behavior changes to show draft definitions in Kaleo Designer

**Comment by pcwhite** [comment]
@vicnate5 1. indirectly, it should due to the xpath. currently, it does not, so i can resend a pull using WorkflowDefinition#DEFINITION_TABLE_TITLE_PUBLISHED.
2. "draft definitions" as in Not Published?

**Comment by vicnate5** [comment]
@pcwhite Sounds good.

Yes, using draft as "not published" in this case.

**Comment by pcwhite** [comment]
@vicnate5 updated!

**Pull request closed without merging**
