### PR TITLE
master-qa-79185

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-79185

Tested in https://github.com/zhangyan0701/liferay-portal/pull/446.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@zhangyan0701 How is the test running on a virtual instance if the `setup` doesn't have the virtual instance setup?

This isn't the first time we tried to fix it this way:
https://github.com/vicnate5/liferay-portal/commits/7ae89bef11ddc11b1e9c727a22cb8d978d8b3bd0/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/deployment/PortalTempDir.testcase

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/129488

**Comment by zhangyan0701** [comment]
@vicnate5 

I should've added the property `test.name.skip.portal.instance` last time, I thought that removing `TestCase.setUpPortalInstance(); `would work, but I only ran one test last time, so I didn't find out that my fix actually not work. 

It seems that the test runs on instance by default unless it has property `test.name.skip.portal.instance`.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you share this with the QA team? (I suggest `#qa-knwl-share`) We should know that removing the setup doesn't have the expected affect. I didn't know this, so I suspect others don't either.

**Pull request closed without merging**
