### PR TITLE
LPS-163282 Uniform | Turn DB Partition tests to run just with Mysql 5.7

### PR DESCRIPTION
**Pull request by lucasperj**
[LPS-163282](https://issues.liferay.com/browse/LPS-163282) - Enable DB Partitioning tests to run only on MySQL 5.7

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/123525

**Comment by vicnate5** [comment]
testing

**Comment by vicnate5** [comment]
test2

**Comment by vicnate5** [comment]
test3

**Pull request closed without merging**
