### PR TITLE
LRQA-75686 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-75686

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
As we discussed.

1. Set `database.host`
2. Pass in `param` values into the prepare-portal-ext-properties

**Comment by Kvale1733** [comment]
@vicnate5 I made the changes. I tested locally and I was able to start up a portal with postgresql.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@Kvale1733 This is looking good.

Now, I want you to add to it with some additional requirements.

### 1
Given the user sets a property in test.USERNAME.properties to use postgreSQL in a local run,
When the user runs a poshi test with "run-selenium-tomcat"
Then the postgreSQL container will start and be used for the test

### 2
Given the user sets a property in test.USERNAME.properties to use postgreSQL in a local run,
When the user runs a poshi **Upgrade** test with "run-selenium-tomcat"
Then the postgreSQL container will start and be used for the import of the DB and for the test

Note: in ant the user could also set a test property at runtime 
e.g. `ant -f build-test-tomcat.xml run-selenium-tomcat -Ddatabase.docker.enabled=true`

*Also fix the typo `<param name="database.postgresql.schema=lportal" value="lportal" />` :)

**Comment by vicnate5** [comment]
For this task, you can keep sending to me instead of Kyle.

**Pull request closed without merging**
