### PR TITLE
LRQA-79471

### PR DESCRIPTION
**Pull request by catarineaguiar**
Tested [here](https://github.com/catarineaguiar/liferay-portal/pull/70)

Using `functional-smoke-tomcat90` for all databases worked as expected, and the other batches I put as the `functional-tomcat90-mysql` one.

### CODE REVIEW

**Comment by vicnate5** [comment]
@catarineaguiar Can you explain why adding both solves the issue?

I also see in your run https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2195658632 that lots of tests ran on some DBs (I was only expecting smoke). This is creating a much bigger cost increase on relevant than we want to do.

**Comment by catarineaguiar** [comment]
@vicnate5 I believe only functional-smoke can make relevant run smoke tests (as we saw in my first try). The other batches make other tests run with other BDs. 

If we want to run only smoke in all BDs, the functional-smoke is the recommended, in my point of view.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@catarineaguiar I am OK using the smoke batches, but for the non-smoke ones, we need to override the default PQL, otherwise they will all run tests I think. 

Please run the build summary check locally before running on CI, right now I think that a group of tests is running on `functional-tomcat90-db2115-jdk8` for example, even though that batch should run nothing right now. It would only run something if we had a future change to a **module's test.properties** to add PQL for that batch.

This feature of allowing module test.properties to add tests should also be tested locally with the ant target.

If you are not sure, please send me your build summary result and I can show you how to read it.

**Pull request closed without merging**
