### PR TITLE
LPS-126747

### PR DESCRIPTION
**Pull request by BryanEngler**
got a 404 when trying to go to the liferay-release-tool-ee repo... will this commit be included in the bundle?

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:license

**Comment by BryanEngler** [comment]
commerce doesnt start up...

**Comment by BryanEngler** [comment]
2021-02-04 04:46:59.477 ERROR [fileinstall-directory-watcher][LPKGBundleTrackerCustomizer:357] Rollback bundle installation for [com.liferay.commerce.product.definitions.web_7.0.0 [1715], com.liferay.commerce.product.type.virtual.order.service_4.0.0 [1725], com.liferay.headless.commerce.delivery.catalog.client_4.0.0 [1766], com.liferay.headless.commerce.admin.channel.impl_4.0.0 [1753], com.liferay.headless.commerce.admin.catalog.impl_4.0.0 [1751], com.liferay.headless.commerce.admin.site.setting.client_4.0.0 [1760]
...
org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.account.admin.web [1654]
  Unresolved requirement: Import-Package: com.liferay.account.model; version="[2.0.0,3.0.0)"

**Comment by BryanEngler** [comment]
any way to maybe build on a more stable hash?

**Comment by vicnate5** [comment]
ci:test:license:66e8168ba76a3472d339633c44b636157b2d73b9

**Comment by vicnate5** [comment]
Trying a compile before the commits I expect broke this.

**Comment by BryanEngler** [comment]
@vicnate5 yep that hash worked, thanks!

**Comment by BryanEngler** [comment]
ci:test:license:66e8168ba76a3472d339633c44b636157b2d73b9

**Pull request closed without merging**
