### PR TITLE
LRQA-45896 Define oracle jdk11 batches

### PR DESCRIPTION
**Pull request by anthony-chu**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test:jdk11

**Comment by anthony-chu** [comment]
ci:test:environments

**Comment by anthony-chu** [comment]
@vicnate5 the oracle batches are running successfully, but it looks like there are scenarios where the gc options are being configured too early and causing jdk8 ant functionality to fail.

**Comment by vicnate5** [comment]
@anthony-chu sounds good.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68422
https://github.com/brianchandotcom/liferay-portal-ee/pull/23325

See https://github.com/brianchandotcom/liferay-portal/pull/68422/commits/3d1164327ebe8a69b23b24943459439d2c0d391b

**Pull request closed without merging**
