### PR TITLE
LPS-68362 Removing custom 'valueChanged' event in favor of the default 'valueChange' one

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
I was still able to reproduce this issue with the steps in the ticket:

1. Go to Content > Forms
2. Add new form
3. Add new field > Select from List
4. Input label
5. Add 3 options, then remove the last one
6. Close side bar

When an option is removed, the Select from List field is NOT being updated, it keeps all options including the removed one.

Can you take another look @fernandosouza?

**Comment by brunobasto** [comment]
@diogo-lins, can you take a look?

**Comment by diogo-lins** [comment]
Ok @brunobasto, I will take a look.

**Pull request closed without merging**
