### PR TITLE
LRQA-36107

### PR DESCRIPTION
**Pull request by rodrigo-e-c-souza**
https://issues.liferay.com/browse/LRQA-36107

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@rodrigo-e-c-souza This is a hard test to name.

How do you feel about `ViewShowRuleActivationAfterInputtingUnrelatedField`

**Comment by rodrigo-e-c-souza** [comment]
That's good, thanks for renaming!

**Pull request closed without merging**
