### PR TITLE
LPS-78331 | master

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Did a rebase and now I'm running tests again.

**Comment by vicnate5** [comment]
@pedroqueiroz Is ready for Brian? It doesn't need any test fixes.

**Comment by vicnate5** [comment]
Pushed to Prax
https://github.com/rafaprax/liferay-portal/pull/636

**Pull request closed without merging**
