### PR TITLE
JDK 21 for test-5 ONLY

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:report:2532425838

**Comment by rafaprax** [comment]
ci:report:2533080857

**Comment by rafaprax** [comment]
ci:test:object

**Comment by vicnate5** [comment]
@rafaprax I rebased and retriggered the unit tests

**Comment by tinatian** [comment]
ci:report:2533808823

**Comment by vicnate5** [comment]
@tinatian This branch is for the alternate CI on test-5 + JDK21 so it must be manually triggered by the CI team and has limited resources.

Use https://github.com/vicnate5/liferay-portal/pull/2462 branch is for regular CI on JDK17. But please revert https://github.com/vicnate5/liferay-portal/pull/2462/commits/569ead2113de6c692de73ca4b9c91926ff899a2f if you are going to run yourself.

**Comment by rafaprax** [comment]
ci:report:2535007754

**Comment by tinatian** [comment]
ci:report:2536227562

**Comment by tinatian** [comment]
ci:report:2536200874

**Comment by vicnate5** [comment]
Closing since we now have JDK21 upstream.

Triggered at https://github.com/tinatian/liferay-portal/pull/2574

**Pull request closed without merging**
