### PR TITLE
LRQA-82154 | master

### PR DESCRIPTION
**Pull request by catarineaguiar**
Moved the test to MBThread.testcase as asked on https://github.com/vicnate5/liferay-portal/pull/2429#issuecomment-1800081058.

https://liferay.atlassian.net/browse/LRQA-82154
Tested on https://github.com/catarineaguiar/liferay-portal/pull/130#issuecomment-1802651799

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/143591

See https://github.com/brianchandotcom/liferay-portal/pull/143591/commits/97ae889c3684d0f25e4a171675d95a2c5990a3c4
We can revert this if there is a reason it needs to run by itself.

**Pull request closed without merging**
