### PR TITLE
LPS-68011 Add npm shrinkwrap file

### PR DESCRIPTION
**Pull request by diogo-lins**
@brunobasto

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by diogo-lins** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@brunobasto node modules issue.

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@diogo-lins There is still a startup error. Were you able to reproduce this on your machine? It looks like the integration tests fail from it as well.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@diogo-lins I am consistently able to reproduce this and this won't pass the PR tester. Could you take another look at the stuff you added here?

The error hints this is something with the javascript modules.
```
21:50:13,662 ERROR [Framework Event Dispatcher: Equinox Container: 4016b455-d8a2-0016-19d7-c9041b83585f][com_liferay_frontend_js_loader_modules_extender:97] FrameworkEvent ERROR 
     [exec] java.lang.NullPointerException
     [exec] 	at com.liferay.frontend.js.loader.modules.extender.internal.JSLoaderModule.generateConfiguration(JSLoaderModule.java:124)
     [exec] 	at com.liferay.frontend.js.loader.modules.extender.internal.JSLoaderModule.urlToConfiguration(JSLoaderModule.java:274)
     [exec] 	at com.liferay.frontend.js.loader.modules.extender.internal.JSLoaderModule.<init>(JSLoaderModule.java:80)
     [exec] 	at com.liferay.frontend.js.loader.modules.extender.internal.JSLoaderModulesTracker.addingService(JSLoaderModulesTracker.java:69)
     [exec] 	at com.liferay.frontend.js.loader.modules.extender.internal.JSLoaderModulesTracker.addingService(JSLoaderModulesTracker.java:38)
     [exec] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
     [exec] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
     [exec] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
     [exec] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
     [exec] 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
```

**Comment by brunobasto** [comment]
@diogo-lins,

Any updates on this?

Thanks

**Comment by diogo-lins** [comment]
@brunobasto @vicnate5  I will take a look!

**Pull request closed without merging**
