### PR TITLE
LPS-103034 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@achaparro Some strange failures on DB2, going to re-run to confirm. I also needed to build service, see last commit

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by achaparro** [comment]
I also have to do something similar before, I guess is because we have to rebase everytime and some new changes are included which affect our pull.

Cross fingers.

**Comment by vicnate5** [comment]
@achaparro Still search issues on DB2, could you see if these might be related?
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/227322/#showFailuresLink

**Comment by achaparro** [comment]
Hey @vicnate5,

I have checked some of the errors and they are related to blogs:
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/227322/#showFailuresLink
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/227322/AXIS_VARIABLE=4,label_exp=!master/consoleText

Because there is a missing deleteEntries method but we don't modify that

an others seem also unrelated.

We can check it together tomorrow

**Comment by vicnate5** [comment]
Comparing the results between runs, the failures are not consistent. I am leaning toward these just being flaky test cases, which means we can proceed.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/80029

**Pull request closed without merging**
