### PR TITLE
LPS-69836

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @marcellustavares

### CODE REVIEW

**Comment by vicnate5** [comment]
@jonathanmccann Unfortunately, I found a regression on this pull. Workflow assets that have been assigned to a user are showing up in the "Assigned to My Roles" table. Could you take another look at this?

Steps to Reproduce:
1. Add new user
2. Assign user to Portal Content Reviewer role
3. Go to Liferay > Configuration > Workflow Configuration
4. Enable Single Approver for Blogs entry
5. Go to Content > Blogs
6. Submit a blogs entry for publication
7. Sign out
8. Sign in to created user
9. Go to My Workflow Tasks
10. Go to "Assigned to My Roles" tab
11. View pending asset in Assigned to My Roles table
12. Assign pending asset to Me
13. View Assigned to My Roles table

**Expected Result:**
Assigned asset no longer displays in "Assigned to My Roles" table

**Actual Result:**
Assigned asset displays in "Assigned to My Roles" table.

CC @marcellustavares

**Comment by jonathanmccann** [comment]
@vicnate5 Thanks for letting me know. I'll investigate the issue.

**Comment by marcellustavares** [comment]
Thanks @vicnate5 @jonathanmccann

**Comment by jonathanmccann** [comment]
https://github.com/vicnate5/liferay-portal/pull/704

**Pull request closed without merging**
