### PR TITLE
LPS-106167 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Test combined fixes for https://github.com/shuyangzhou/liferay-release-tool-ee/pull/3 and https://github.com/shuyangzhou/liferay-portal/pull/8678

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@tinatian release-tool test failed

```
compile:
     [echo] January 2, 2020 at 03:54 PM
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/modules/core/portal-compat/petra/util-java-compat/classes
 [proguard] ProGuard, version 5.2
 [proguard] ProGuard is released under the GNU General Public License. You therefore
 [proguard] must ensure that programs that link to it (net.sf.antcontrib.logic, ...)
 [proguard] carry the GNU General Public License as well. Alternatively, you can
 [proguard] apply for an exception with the author of ProGuard.
 [proguard] Reading program directory [/opt/dev/projects/github/liferay-portal/portal-impl/classes] (filtered)
 [proguard] Reading library jar [/opt/java/jdk1.8.0_121-x64/jre/lib/jce.jar]
 [proguard] Reading library jar [/opt/java/jdk1.8.0_121-x64/jre/lib/rt.jar]
 [proguard] Reading library directory [/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.petra.encryptor]
 [proguard] Reading library jar [/opt/dev/projects/github/liferay-portal/lib/development/servlet-api.jar]
 [proguard] Reading library jar [/opt/dev/projects/github/liferay-portal/lib/portal/commons-io.jar]
 [proguard] Reading library directory [/opt/dev/projects/github/liferay-portal/modules/core/portal-compat/petra/util-java-compat/classes]
 [proguard] Reading library directory [/opt/dev/projects/github/liferay-portal/portal-impl/classes] (filtered)
 [proguard] Reading library directory [/opt/dev/projects/github/liferay-portal/portal-kernel/classes]
 [proguard] Reading library directory [/opt/dev/projects/github/liferay-portal/util-java/classes]
 [proguard] Warning: com.liferay.portal.ee.license.LCSLicenseManager: can't find referenced class com.liferay.petra.string.StringPool
 [proguard] Warning: com.liferay.portal.ee.license.classloader.DecryptorClassLoader: can't find referenced class com.liferay.petra.string.StringPool
 [proguard] Warning: com.liferay.portal.license.LicenseManager: can't find referenced class com.liferay.petra.string.StringPool
 [proguard] Warning: com.liferay.portal.license.validator.KeyValidator: can't find referenced class com.liferay.petra.string.StringPool
 [proguard] Warning: there were 4 unresolved references to classes or interfaces.
 [proguard]          You may need to add missing library jars or update their versions.
 [proguard]          If your code works fine without the missing classes, you can suppress
 [proguard]          the warnings with '-dontwarn' options.
 [proguard]          (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
[stopwatch] [run.batch.test.action: 17:42.871 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build.xml:129: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-release.xml:744: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/ext/7.2.x/build-release-license.xml:11: Please correct the above warnings first.
      [get] Getting: http://test-1-21/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/295992//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20200102155432189.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20200102155432189.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null389303791.properties
```

**Comment by tinatian** [comment]
@vicnate5 Fix and resend here : https://github.com/shuyangzhou/liferay-release-tool-ee/pull/4

**Comment by vicnate5** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang Seems new compile issues coming up, please fix and send me a pull based on this shuyangzhou/liferay-release-tool-ee#4.

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Fix and resend here https://github.com/shuyangzhou/liferay-release-tool-ee/pull/5

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Pull request closed without merging**
