### PR TITLE
LRQA-78846

### PR DESCRIPTION
**Pull request by catarineaguiar**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
I don't know why this [test](https://testray.liferay.com/home/-/testray/case_results/2130584311?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2130583708%26testrayRunId%3D2130584070%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is passing

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
See https://github.com/vicnate5/liferay-portal/pull/2218

**Pull request closed without merging**
