### PR TITLE
LRQA-45362 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-45362

### CODE REVIEW

**Comment by john-co** [comment]
last commit fixes ExportImport#EditExportTemplate, passes locally.
testing on CI: https://github.com/john-co/liferay-portal/pull/80
Messageboard and Wiki test errors are unrelated

**Comment by john-co** [comment]
Backport to 7.1.x

**Comment by vicnate5** [comment]
@john-co The backport to 7.1 is messy, can you send?

**Comment by john-co** [comment]
7.1.x: https://github.com/vicnate5/liferay-portal-ee/pull/210

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69204
https://github.com/brianchandotcom/liferay-portal-ee/pull/23453

**Pull request closed without merging**
