### PR TITLE
LRQA-78759 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-78759

This is to add the additional components to relevant for /apps/static
Tested if the correct tests run here:https://github.com/Kvale1733/liferay-portal/pull/244

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@vicnate5 Added another line to run LiferayOnline#Smoke which is the only test with the property liferay.online.smoke.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@Kvale1733 Can you update with some changes?
1. No need to add ` **/static/portal-lpkg-deployer` since backend tests from here already included.
2. Add "File Install" and "Publications" functional tests
3. Is there a way we can make LiferayOnline#Smoke run on all relevant runs (not just when we update static modules)?

**Comment by Kvale1733** [comment]
Gonna test is out on CI with changes to check if I got it right.

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
