### PR TITLE
LRQA-42955, LRQA-42954

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:clustering

**Comment by koor4356** [comment]
Backport this to 7.1.X, 7.2.X, and 7.3.X branches.

**Comment by koor4356** [comment]
@vicnate5,
The loopback error does happen on running time whether the test runs locally or CI. I have tried to reproduce manually, but I couldn't get the error.

`LIFERAY_ERROR: Unable to detect bind address for JGroups, using loopback`

**Comment by vicnate5** [comment]
@koor4356 I think this will fix it, I searched up that error on JIRA and checked the class and method that throws the error.
https://github.com/vicnate5/liferay-portal/pull/1725

**Pull request closed without merging**
