### PR TITLE
Db2 single txddl

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@zhangyan0701 This should fix the DB2 issue

**Comment by vicnate5** [comment]
@shuyangzhou Still reproducible
https://testray.liferay.com/reports/production/logs/2022-08/test-1-28/test-portal-acceptance-pullrequest(master)/3923/functional-tomcat90-db2111-jdk8/1/5/liferay-log.txt.gz?authuser=0

https://testray.liferay.com/reports/production/logs/2022-08/test-1-28/test-portal-acceptance-pullrequest(master)/3923/functional-tomcat90-db2111-jdk8/1/6/liferay-log.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:environments

@vicnate5 adding back the BaseDB debug logging to rerun for more info.
I will also make a new pull to try to make all statements in that tx in a batch to see if that will make a difference.

**Comment by shuyangzhou** [comment]
ci:test:environments

**Pull request closed without merging**
