### PR TITLE
Headless API Fix

### PR DESCRIPTION
**Pull request by vicnate5**
This fixed the timeout for me locally @kyle-miho

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:poshi

**Comment by kyle-miho** [comment]
ci:test:poshi 
@vicnate5 trying one more time to check for performance, ima run a dummy test run and link to this pr

**Comment by kyle-miho** [comment]
ran control here: https://github.com/kyle-miho/liferay-portal/pull/411
poshi run started at approximately the same time

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@kyle-miho took 4 hours to run relevant...but it does look like this is unrelated to this change.

We still should probably get https://issues.liferay.com/browse/LPS-123610 fixed before we merge this, to prevent big logs on most runs.

**Pull request closed without merging**
