### PR TITLE
LPS-68076 SF

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by fernandosouza** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@vicnate5, please let me know if we have a regression on this. Thanks

**Comment by vicnate5** [comment]
@marcellustavares There does seem to be an issue, based on the test results.

The validation options are gone and the label for validation looks wrong.

before0

**Comment by vicnate5** [comment]
@fernandosouza @brunobasto See above comment.

**Comment by fernandosouza** [comment]
I will check it out @vicnate5 and @marcellustavares

**Comment by vicnate5** [comment]
@fernandosouza Thanks! I am going to close this for now.

**Comment by fernandosouza** [comment]
@vicnate5 @marcellustavares fix sent to @brunobasto to review.

https://github.com/brunobasto/liferay-portal/pull/751

**Pull request closed without merging**
