### PR TITLE
LRQA-66293 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-66877

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:relevant
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@kyle-miho Backportable?

**Comment by vicnate5** [comment]
Removed in https://github.com/liferay/liferay-portal/commit/147d3ef1f3951ab1a94e012676036bb58b386846

**Pull request closed without merging**
