### PR TITLE
LPS-67562 Fix required validation

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 Can you take another look ? :) You can forward to BChan if it's ok. Thanks a lot !!!

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by vicnate5** [comment]
There is still a render failure with conditional visibility applied. See comment https://github.com/vicnate5/liferay-portal/pull/497#issuecomment-239229083

Pushed to @leoadb with poshi test added to the CI so we have better visibility.
https://github.com/leoadb/liferay-portal/pull/235

**Comment by leoadb** [comment]
@vicnate5 Thanks !!! As I said to you I couldn't reproduce that locally. :( Will try again.

**Pull request closed without merging**
