### PR TITLE
LPS-101450 SF

### PR DESCRIPTION
**Pull request by achaparro**
Hey @vicnate5 

This is the pull to allow to revert minor changes. I am executing the tests here just in case we need to modify some of the tests in the CI.

Cheers!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@achaparro This looks good from the tests.

There is one unique failure, but it is likely a fluke. Linking here just in case we see it again: https://testray.liferay.com/home/-/testray/case_results/777337247

I am going to test manually for the actual revert scenario.

**Comment by vicnate5** [comment]
@achaparro I am blocked from testing manually. The changes do not backport cleanly to 7.2.x.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/78423

**Pull request closed without merging**
