### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Victor,

This pull is based on https://github.com/shuyangzhou/liferay-portal/pull/8871, only enable sidecar and corresponding test fixes.

Please rerun clustering manual tests if the test results look good.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@tinatian See thread dump on one of the failing cluster tests:
https://testray.liferay.com/reports/production/logs/test-1-15/1582182101885/test-portal-acceptance-pullrequest(master)/2297/functional-tomcat90-mysql57-jdk8/4/0/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
Rolling Restart test is unstable, but seen Passing on this PR here:
https://testray.liferay.com/home/-/testray/case_results/1014345771

RollingRestartEE#UpdatePortalPropertiesWithMultipleClusters

**Comment by tinatian** [comment]
@vicnate5 
This is expected for sidecar, one known issue is that we have random failure when shutting down master node, but for the issue shown on thread dump you mentioned earlier, could you please confirm if it can be reproduced? 

I am trying to figure out a way to make sidecar stable when cluster is enabled, could you please check what you can do to make the rolling restart test on head stable?

Thanks.
Tina.

**Comment by tinatian** [comment]
Update pull at https://github.com/vicnate5/liferay-portal/pull/1415.

**Pull request closed without merging**
