### PR TITLE
LRQA-61560 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-61560

### CODE REVIEW

**Comment by kyle-miho** [comment]
lpkg persistence test passed 4x in a row with this change. Stop app-server w/docker does not wait for the port to become availble to check if the app-server is stopped like it does when not using docker. This was causing the upgrade to run during server shutdown causing unexpected behavior. https://issues.liferay.com/browse/LPS-120311 This should help improve test stability.

**Comment by kyle-miho** [comment]
Should for sure backport this to every branch this cleanly backports on (but maybe we should wait a bit to ensure that this actually increases stability)

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
If we are going to add this, this should fail the test if the server doesn't stop to mirror the logic in `stop-app-server-cmd`. This current code can set the timeout property, but not do anything with it.

**Pull request closed without merging**
