### PR TITLE
LPS-168040 Disable upgrade and db partitioning tests on release

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-168040
- Disable upgrade tests on db2 11.5
- Disable db partitioning tests on mysql 8.0

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@susanchen3 Can you update the commit messages to explain why we are disabling these? Please note the change for DB2 11.5 is temporary.

**Comment by susanchen3** [comment]
Updated @vicnate5

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/126035

**Pull request closed without merging**
