### PR TITLE
LPS-171559 Apply custom timeout to upgrade execution

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade-performance

**Comment by vicnate5** [comment]
ci:test:upgrade-performance:nocompile

**Comment by vicnate5** [comment]
ci:test:upgrade-performance:nocompile

**Comment by vicnate5** [comment]
@susanchen3 can you follow up on this next week? Trying to set a reasonable timeout for the upgrade tool on CI, but proving difficult

**Comment by susanchen3** [comment]
Manually forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/128177

Ended up setting the custom timeout for the upgrade tool to 490 seconds (~8.1 minutes).

**Comment by susanchen3** [comment]
ci:close

**Pull request closed without merging**
