### PR TITLE
master-qa-66486

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-66486

> 1. Is the groovy script "repair" still needed? Can we just fix these cases directly in the original groovy script files?

I thought the `out.println` is pretty normal in Groovy, as I saw that the example also uses it in Sever Admin UI. But somehow it doesn't work when execute Groovy in Gogo command, this seems a limitation of this method. It took me some extra time to figure out this because the error message is not very clear. So I decided to change that in ant target just in case that if someone else wants to add new groovy scripts to tests in the future but doesn't know about this.

> 2. Rename `test.groovy` to `portal-script.groovy` to be more specific what this is.

Updated.

> 3. Can you pull out `Clustering.runGroovyScript` to a new macro file `Groovy.macro` and make the UI instructions a separate macro? Since none of the logic overlaps between UI and Expect versions, no reason to put them in the same macro. I also want to just account for the fact that non-clustering tests use these.

Updated.

> 4. To avoid the pause in [3d777c7](https://github.com/vicnate5/liferay-portal/commit/3d777c7bd2402fb207a174a377b1ca32b4b68cce), is it possible to design a new macro `waitForConsoleTextPresentOnSpecificNode` that will allow us to wait for it to show in the console? I suggest a while loop that runs every 2 seconds to re-grab the log and check. Make sure the looping count is limited so this can only run up to 30 seconds.

Currently I am afraid it's not possible to create `waitForConsoleTextPresentOnSpecificNode`. I think we need to add new selenium method in poshi-runner first to support this. So I changed to use a while loop.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
This looks good, I am running into a problem running the tests locally I will need to look into on Monday.

**Comment by vicnate5** [comment]
@zhangyan0701 See my changes

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/125558

**Pull request closed without merging**
