### PR TITLE
Remove ignore error, Add new upgrade tests, and ignore warning error

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-50576

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@koor4356 please review the test results and let me know if there is any issues

**Comment by koor4356** [comment]
@vicnate5,  those issues are not new, tests history show.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/76811

**Pull request closed without merging**
