### PR TITLE
LPS-108105 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-108105

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
@vicnate5 @shuyangzhou Found these unique integration failures
```
    com.liferay.portal.upgrade.v7_0_6.test.UpgradeResourceActionsTest.testDeleteDuplicateBitwiseValuesOnResource
    com.liferay.asset.auto.tagger.opennlp.test.BlogsEntryOpenNLPDocumentAssetAutoTaggerTest.testAutoTagsAnAsset
    com.liferay.asset.auto.tagger.opennlp.test.BlogsEntryOpenNLPDocumentAssetAutoTaggerTest.testAutoTagsAnAssetInNotEnglishLanguage
    com.liferay.asset.auto.tagger.opennlp.test.BlogsEntryOpenNLPDocumentAssetAutoTaggerTest.testDoesNotAutoTagAnAssetWhenNotEnabled
    com.liferay.portal.workflow.metrics.service.test.WorkflowMetricsSLADefinitionLocalServiceTest.testAddSLADefinition1
    com.liferay.portal.workflow.metrics.service.test.WorkflowMetricsSLADefinitionLocalServiceTest.testAddSLADefinition2
    com.liferay.portal.workflow.metrics.service.test.WorkflowMetricsSLADefinitionLocalServiceTest.testAddSLADefinitionDuplicateName
    com.liferay.portal.workflow.metrics.service.test.WorkflowMetricsSLADefinitionLocalServiceTest.testUpdateSLADefinition
    com.liferay.portal.workflow.metrics.service.test.WorkflowMetricsSLADefinitionLocalServiceTest.testUpdateSLADefinitionDuplicateName
    com.liferay.change.tracking.internal.test.LayoutCTTest.testPublishLayoutWithConflictingConstraints
```

**Comment by vicnate5** [comment]
Those Workflow SLA ones are random at head.

**Comment by kyle-miho** [comment]
@shuyangzhou 
see
```

    com.liferay.journal.service.test.JournalArticleServiceTest.testSearchArticlesByKeyword
    com.liferay.organizations.service.test.OrganizationLocalServiceTest.testSearchOrganizationsWithOrganizationsTreeParameterAsAdminUser
```
One DB query failed to execute, the other failure could possibly be an issue not sure

**Comment by vicnate5** [comment]
Baseline: https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320181/#showFailuresLink

This PR: https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/111982/#showFailuresLink

**Comment by vicnate5** [comment]
ci:test

**Pull request closed without merging**
