### PR TITLE
Portlet 3.0 TCK

### PR DESCRIPTION
**Pull request by stiemannkj1**
@vicnate5, the only things that need to be done with this PR are:

1. Create issues for the failing tests (some of which only fail for automated testing). We only need these tickets for tracking purposes. It'd be great to reference these tickets in **`tck/ignoredTestCases.xml`**. Right now there are a lot of comments like this in that file:

```
<!-- https://issues.liferay.com/browse/LPS-TODO -->
```

2. Fix between 30-40 test failures. I think personally this PR could be merged upstream and these fixes could be done later. The TCK has over 6200 tests so 30 failures is very minor. All the failing tests are skipped right now since they are included in **`tck/ignoredTestCases.xml`**, so they won't cause any issues.

cc @ngriffin7a

### CODE REVIEW

**Comment by stiemannkj1** [comment]
ci:test:tck

**Comment by stiemannkj1** [comment]
cc @ngriffin7a

**Comment by ngriffin7a** [comment]
@vicnate5 -- Most of the 30-40 test failures that @stiemannkj1 referred to are Portlet 3.0 test failures in the Portlet 3.0 TCK, not Portlet 2.0 tests in the Portlet 3.0 TCK. However, I manually clicked on ALL of the test buttons in the 3.0 tests recently and they ALL pass. So honestly, we are looking 3-5 failures which are related to Equinox and should hopefully be fixed at our next Equinox upgrade by @rotty3000.

**Comment by stiemannkj1** [comment]
ci:test:tck

**Comment by vicnate5** [comment]
compile failure just got fixed

**Comment by vicnate5** [comment]
ci:test:tck

**Comment by vicnate5** [comment]
Pushed to Shuyang
https://github.com/shuyangzhou/liferay-portal/pull/7499

**Pull request closed without merging**
