### PR TITLE
LPS-163998 | Add license removal condition for SQLServer on 6.2

### PR DESCRIPTION
**Pull request by lucasperj**
https://issues.liferay.com/browse/LPS-163998

Tested here : https://github.com/lucasperj/liferay-portal/pull/307

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@lucasperj Can you change to to all DBs? No reason to make this specific for SQL Server, and I am worried that we could run into this problem in the future on another DB.

**Comment by vicnate5** [comment]
Please reopen or resend once this is updated.

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:license

**Comment by lucasperj** [comment]
@vicnate5  Failures not related.

**Comment by vicnate5** [comment]
@lucasperj This is still only fixed for CI-side, not for local runs that are not using docker. It will only run if `<isset property="database.docker.image" />`. We should do this cleanup before the conditional.

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
Changed @vicnate5 , thanks. :heavy_check_mark:

**Comment by vicnate5** [comment]
@lucasperj One more change, sorry to keep pushing back, but I want you to practice this.

In the comment message, specify why we are needing to delete the license "Delete license for 6.2 portal versions because...". You can quickly fix it with `git rebase -i HEAD~3` and then use `r` to reword the commit message.

**Comment by lucasperj** [comment]
@vicnate5 thats ok?

**Pull request closed without merging**
