### PR TITLE
master-qa-65919

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-65919

Issue also happens on 7.3.x, please backport to 7.3.x.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Tested in https://github.com/zhangyan0701/liferay-portal/pull/265, LCS smoke test passed.

**Comment by vicnate5** [comment]
@zhangyan0701 What branches does this apply to?

**Comment by zhangyan0701** [comment]
Hi @vicnate5 

This if for master and 7.3.x branches.

**Comment by vicnate5** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/100726

**Pull request closed without merging**
