### PR TITLE
master-qa-42914

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-42914

7.1.x: [vicnate5/liferay-portal-ee#253](https://github.com/vicnate5/liferay-portal-ee/pull/253)

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 Why are some of the tests not running on all databases? Did we have issues generating the database dumps? if so, do we know why there were issues?

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@vicnate5 Yes, some database dumps failed to generate for 6.2. I think this is because some database types version that used on Jenkins for generating the dumps does not support older version portal.
We have filed some tickets for this kind of issues before:
https://issues.liferay.com/browse/LRQA-44971
https://issues.liferay.com/browse/LRQA-45014
https://issues.liferay.com/browse/LRQA-46511
But they were all closed as Discarded, seems like Jenkins doesn't support multiple database versions and choose one to use.

**Comment by vicnate5** [comment]
@zhangyan0701 there are some inconsistencies that are not related to supported version.

621015 has "db2,mysql,oracle"
621021 has "db2,mysql,oracle,postgresql"

625 is also missing postgresql (when I would expect it to work since it worked for 621021)

I am going to merge this, but I created a follow up ticket for investigating the database dumps, please take a look when you have a chance (https://issues.liferay.com/browse/LRQA-49878)

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74601
https://github.com/brianchandotcom/liferay-portal-ee/pull/25027
https://github.com/brianchandotcom/liferay-portal-ee/pull/25028

**Pull request closed without merging**
