### PR TITLE
LRQA-68736 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-68736

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
failed as expected locally, checking that it now passes that the fix is merged upstream/confirming that it works on ci

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@kyle-miho Can you update the test map for these?

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
the one test that failed based on a description in the bug ticket which was recently deleted because its intended to not change the URL friendly url if the language selector portlet selects a new language (it should only affect the page, not the user's url), this is the same functionality we have always had, i checked in our older versions, so i removed that test (originally failed on CI).

SF is not even running on this PR to some issue with jenkins, it passed on my branch locally

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/104518

**Pull request closed without merging**
