### PR TITLE
LRQA-48181 Remove appservers and database from running portal upgrade tests

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-48181

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 any of the failures here showing that we need to turn off more? I see upgrade failures.

**Comment by koor4356** [comment]
I am looking at them now.

**Comment by vicnate5** [comment]
Closing, this was merged in https://github.com/brianchandotcom/liferay-portal/pull/71396

**Pull request closed without merging**
