### PR TITLE
LPS-158994 Debug

### PR DESCRIPTION
**Pull request by petershin**
The new task can be run like this: `ant debug-bnd '-Dmodule.dir=apps/commerce/commerce-service'`

Run this in a loop in CI to see if the error happens. The output will contain the classpath that Shuyang asked about. It'll run `bnd print` at the end as well.

If the error never happens, the bug may only be happening when Gradle is building everything in parallel. In that case, I'll need to send you a different patch.

### CODE REVIEW

**Comment by vicnate5** [comment]
@petershin Thanks for the full debug push, this is easier.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
Attempt to just run new debug target https://github.com/vicnate5/liferay-portal/pull/2158

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@petershin I do not see the debug logging during the compile on CI https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/986/consoleText

**Comment by vicnate5** [comment]
I also cannot get the debug logging locally, even after I set `JENKINS_HOME`

**Comment by petershin** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
Still not seeing the debug output on CI

**Comment by petershin** [comment]
This is a bit more complicated. When its done, I'll retrigger the test on this pull

The bnd plugin is applied three different ways and the one we're interested in hides the classpath

**Comment by petershin** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
I can see the output now, the first build didn't include the bad import, so running a few more times.

**Comment by vicnate5** [comment]
so far none of these bundles have the bad import

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
I wasn't able to get the bad build here... all of these are good

**Comment by vicnate5** [comment]
Trying another method with new merged functionality
https://github.com/vicnate5/liferay-portal/pull/2161

**Pull request closed without merging**
