### PR TITLE
LPS-106592-LPS-103577 test

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
Testray results from Clustering suite since this did not post here
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1034842973&testrayRunId=1034842975

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
Cluster tests still affects by https://issues.liferay.com/browse/LRCI-1048

Still seeing the strange error on node3 that references node2 (not reproducible locally)
https://testray.liferay.com/reports/production/logs/test-1-16/1583350227392/test-portal-acceptance-pullrequest(master)/5605/functional-tomcat90-mysql57-jdk8/9/0/jenkins-console.txt.gz

**Pull request closed without merging**
