### PR TITLE
LRQA-36543, LRQA-37397 | master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-36543
https://issues.liferay.com/browse/LRQA-37397

### CODE REVIEW

**Comment by pcwhite** [comment]
ci:test

**Comment by pcwhite** [comment]
ci:stop

**Comment by pcwhite** [comment]
stopped CI testing of Kaleodesigner#DeleteConnectors becuase of other bugs found

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@pcwhite Is this ready for review?

**Comment by pcwhite** [comment]
@vicnate5 yes it's ready

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54726

**Pull request closed without merging**
