### PR TITLE
LPS-148610 Disable ErrorReportValve by default.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:acceptance-functional

**Comment by vicnate5** [comment]
@shuyangzhou This doesn't break the functional tests, I am OK moving forward with this solution.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please just forward it once CI is cleared.

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
