### PR TITLE
Cluster License testing

### PR DESCRIPTION
**Pull request by vicnate5**
@tinatian

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
@tinatian I just needed to update the tests for the new messaging.

I did notice that this incorrect message is on the 3rd node (2 node cluster), even when it **will** be shutdown or deactivated
before4
Message from: https://github.com/tinatian/liferay-release-tool-ee/blob/93dc66b5a7c8f6061f5631ca4b97cf8d0c6d7e74/ext/7.4.x/ext-impl/src/com/liferay/portal/ee/license/LCSLicenseManager.java#L751-L754

I updated to test to check for `will automatically shut down` on the node that will shutdown or `will be automatically deactivated` under manual recovery, so we can rerun the tests on the fix to confirm.

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
I fixed the issue you mentioned on the release repo and re-trigger the test.

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
@tinatian

### Regression
The auto activation of a deactivated node once the user reduces the node count to under the limit is not working anymore.

Steps:
1. Start 3 nodes (2 node limit) with `license.cluster.overload.node.auto.shut.down=false`
2. Wait for grace period to end (3rd node will be deactivated)
3. Shutdown 2nd node
4. Wait 2 minutes

Expected: 3rd node gets activated
Actual: 3rd node still deactivated.

### Message issue
Phrasing of the error message after a grace period expires:
before5
`during the grace period which already ends`

Should be
`during the grace period which already ended`

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
@tinatian Everything looks good now

**Pull request closed without merging**
