### PR TITLE
master-qa-56272

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-56272

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Fix the SF error by force pushing.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Forwarding at https://github.com/vicnate5/liferay-portal/pull/1500

**Pull request closed without merging**
