### PR TITLE
Sprite

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou Acceptance tests look good, will just need to run the full gauntlet now.

**Comment by vicnate5** [comment]
ci:test:gauntlet

**Comment by shuyangzhou** [comment]
ci:test:gauntlet

**Comment by shuyangzhou** [comment]
ci:test:gauntlet

**Comment by vicnate5** [comment]
@shuyangzhou The gauntlet results show no regressions. Looks good to go :)

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Pull request closed without merging**
