### PR TITLE
master-qa-26722

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-26722

### CODE REVIEW

**Comment by ctampoya** [comment]
WorkflowadminCPDocumentsandmedia#SaveAsDraftAndViewCategories is still going to fail from LPS-60870

**Comment by vicnate5** [comment]
Don't bother retesting right now. Cuz there is regression at head.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@ctampoya Does this apply to ee-7.0.x?

**Comment by ctampoya** [comment]
@vicnate5 No, just master.

**Comment by vicnate5** [comment]
@ctampoya Can you take another look at this?

I ran `WorkflowadminUsecase#AddWebContentWithCategorySpecificDefinition` twice and it failed both times.

**Comment by ctampoya** [comment]
@vicnate5 Oh weird... It passed when I ran it. I'll take a look.

**Pull request closed without merging**
