### PR TITLE
master-qa-58530

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-58530

Test passed on Windows + Tomcat/Wildfly/Weblogic on local with the fixes of [LPS-111757](LPS-111757).

For property LIFERAY_LIB_GLOBAL_SHARED_DIR, we cannot get this one from ant scripts, so I didn't include it in test. Just add LIFERAY_LIB_PORTAL_DIR and LIFERAY_WEB_PORTAL_DIR.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:result

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Fix the SF failure by force-pushed.

**Comment by vicnate5** [comment]
https://github.com/ChiZelin/liferay-portal/pull/258

**Pull request closed without merging**
