### PR TITLE
LPS-68216 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
Test failures are not related to this pull

**Comment by yuhai** [comment]
Hi @vicnate5 

I hope you are well.

Could you please prioritize this case? Because the ticket came from EE customer.

Best Regards,
Hai

**Comment by jonmak08** [comment]
Hey @ctampoya,

Can you pull this in and send it through since a customer is waiting for this fix?

Please let me know if you have any questions. Thanks!

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by ctampoya** [comment]
Hey @jonmak08 No Problem.  I will review it ASAP.

**Comment by jonmak08** [comment]
Thanks @ctampoya!

**Comment by ctampoya** [comment]
Running all DDL test https://github.com/ctampoya/liferay-portal/pull/27

**Comment by ctampoya** [comment]
Pushed to https://github.com/sharonchoi/liferay-portal/pull/914. 

@jonmak08 I added a test to cover this issue so we can track any regressions with this issue. Let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Hey @yuhai and @vicnate5,

Since this has been sent to @sharonchoi at https://github.com/sharonchoi/liferay-portal/pull/914, we can now close this pull request.

Please let me know if you have any questions. Thanks!

**Comment by ctampoya** [comment]
@brunobasto I do not have permissions to close this pull. Since @vicnate5 is out until Monday, can you go ahead and close the pull?

**Pull request closed without merging**
