### PR TITLE
master-qa-28790

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-28790

### CODE REVIEW

**Comment by vicnate5** [comment]
Since this is a big change, gonna run all the tests
https://github.com/vicnate5/liferay-portal/pull/605

**Comment by vicnate5** [comment]
Calendar is frustrating because there are so many variations and the html does not play nicely with our tests.

Unfortunately, this breaks some tests
See
https://testray.liferay.com/home/-/testray/case_results/56534854
https://testray.liferay.com/home/-/testray/case_results/56534989
https://testray.liferay.com/home/-/testray/case_results/56535066
https://testray.liferay.com/home/-/testray/case_results/56535120
https://testray.liferay.com/home/-/testray/case_results/56535110

Feel free to get more of my input on this. These locators have long haunted me.

**Comment by ctampoya** [comment]
Oh boy. Okay, thanks =)

**Comment by brianwulbern** [comment]
@ctampoya @vicnate5 what if we just use the conditionals, and scrap the locator changes?  Do the tests work better?  I just used conditional macro updates when fixing next-day/next-week test failures, and it seemed to lower the flakiness.

**Comment by ctampoya** [comment]
@brianwulbern I haven't tried using only the conditionals yet.  This fix was based on our original thought that maybe the locators weren't specific enough, so the test was finding the wrong element.  I am open to just using the conditionals if that stabilizes this issue more.

**Comment by brianwulbern** [comment]
Testing it here:
https://github.com/brianwulbern/liferay-portal/pull/95

**Comment by brianwulbern** [comment]
I think there are at least two separate issues at play.  I'm going to test a pull that just adds one conditional to a common pain point `CalendarScheduler#selectSpecificEvent`

**Comment by ctampoya** [comment]
@brianwulbern Nice. Thank you for looking into this! =)

**Comment by brianwulbern** [comment]
Testing here: https://github.com/brianwulbern/liferay-portal/pull/100

**Comment by brianwulbern** [comment]
They say _hate_ is a strong word.  I think it's the perfect word to describe my feelings towards these tests...

**Comment by brianwulbern** [comment]
I'm close to saying flakiness > consistent failure, and just leave these tests be until we have a eureka moment and make them nice later.

**Comment by vicnate5** [comment]
@brianwulbern "They say hate is a strong word. I think it's the perfect word to describe my feelings towards these tests..." hahahahahaha, I agree.

**Comment by brianwulbern** [comment]
@vicnate5 Haha, glad I'm not alone on that :)

Yeah, if you look at the latest [Testray run](https://testray.liferay.com/home/-/testray/case_results?filterStatuses=4%2C3%2C1%2C5%2C7%2C0&testrayRunId=57717831), it seems the tests aren't always failing on the weekends.  I think it's moreso when the weekend coincides with a month boundary

**Pull request closed without merging**
