### PR TITLE
LPS-201756 Remove bnd instructions that were inherited from app.bnd/suite.bnd

### PR DESCRIPTION
**Pull request by petershin**
@david-truong

### CODE REVIEW

**Comment by petershin** [comment]
@vicnate5 - just fyi, when bchan merges this, it'll automatically be backported to `7.0.x`

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
ci:test:lpkg

**Comment by vicnate5** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/143887

**Pull request closed without merging**
