### PR TITLE
LPS-75036 DON’T MERGE THIS COMMIT

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@leoadb I manually re-triggered the pull.

**Comment by vicnate5** [comment]
ci:reopen

**Comment by leoadb** [comment]
@vicnate5 I needed to change .gitrepo file in order to send DDM code together with portal.

**Comment by vicnate5** [comment]
Forwarded to myself to prevent the subrepo change check
https://github.com/vicnate5/liferay-portal/pull/856

**Pull request closed without merging**
