### PR TITLE
LPS-132032 Apply to account tests that create companies

### PR DESCRIPTION
**Pull request by vicnate5**
@achaparro @pei-jung @drewbrokke

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Looks good, thanks for the heads up @vicnate5.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
