### PR TITLE
LPS-68011 Add Unit test

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by diogo-lins** [comment]
@brunobasto

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by brunobasto** [comment]
@diogo-lins, you need to run gw formatSource. Your build.gradle is not organized properly.

**Comment by diogo-lins** [comment]
ci:retest

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44767

**Pull request closed without merging**
