### PR TITLE
master-qa-78721

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-78721

The test will be failed due to [LPS-170627](https://issues.liferay.com/browse/LPS-170627), but it has been taken by dev, so I don't  ignore the error. But I tested with ignoring the error here https://github.com/zhangyan0701/liferay-portal/pull/426, test could pass, no other issues found.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@zhangyan0701 Do we need https://issues.liferay.com/browse/LPS-170627 resolved before we can continue with full regression testing?

**Comment by vicnate5** [comment]
Pushed to BChan. See my changes.
https://github.com/brianchandotcom/liferay-portal/pull/127493

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Do we need https://issues.liferay.com/browse/LPS-170627 resolved before we can continue with full regression testing?

Yes, I think it will fail many tests. But I can start updating Poshi tests now, and once it gets resolved, I can run tests immediately.

**Pull request closed without merging**
