### PR TITLE
master-qa-26503

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-26503

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:retest

**Comment by vicnate5** [comment]
@austinchiang can you fix the SF error?

**Comment by austinchiang** [comment]
:thumbsup:

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
@vicnate5 the latest SF error looks unrelated to my commits.

**Comment by vicnate5** [comment]
@austinchiang it is. Thanks!

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41667
See my changes.

**Pull request closed without merging**
