### PR TITLE
Add gogo shell test script

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-53704 https://issues.liferay.com/browse/LRQA-53705

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
I have combined these tickets on one commit.
https://issues.liferay.com/browse/LRQA-53704 
https://issues.liferay.com/browse/LRQA-53705

**Comment by koor4356** [comment]
ci:retest

**Comment by vicnate5** [comment]
@koor4356 Why do we need https://github.com/vicnate5/liferay-portal/pull/1360/commits/e6f2b7c27a32cf5d87eb01456060e618f25418a1? This isn't an IPV6 test.

**Comment by vicnate5** [comment]
@koor4356 Going to push this back for updates

1. Why are you using `sequential` and `parallel` for the targets?
2. The setup for the tests are the same currently, but that means that both call `prepare-portal-ext-properties` which adds a non-default gogo shell property. We should stick to the default for `no-default-access-to-gogo-shell-command`
3. What is the `get-gogo-shell-client-paths` macro for?
4. The "waitfor" app server logic is redundant. See the logic inside of `<antcall inheritall="false" target="start-app-server" />`
5. Are `redirector.err` and `redirector.out` actually files that are created? We should just put the output into a property, no need to create files.
6. What is the point of the string replace "before" to "after"?

Why is any of this needed?
```
<inputfilterchain>
	<replacestring from="before" to="after" />
</inputfilterchain>
<outputmapper to="redirector.out" type="merge" />
<errormapper to="redirector.err" type="merge" />
```

**Comment by koor4356** [comment]
Testing revised here https://github.com/koor4356/liferay-portal/pull/50

**Pull request closed without merging**
