### PR TITLE
LRQA-66293 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-66293

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
backport as far back as we can, there will probably be backport conflicts, so we should backport once we are satisfied with this current pull first

**Comment by kyle-miho** [comment]
ci:test

**Comment by vicnate5** [comment]
@kyle-miho We will need to backport some other macros before this can go back to 7.2.x and 7.3.x. On 7.3.x we need the headless api macros for instances to be backported. Please follow up on this when you have a chance.

I also removed the commits that ignore the tests, I would rather them fail for visibility on the bugs.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/101165

**Pull request closed without merging**
