### PR TITLE
LPS-76776 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-76776

### CODE REVIEW

**Comment by kyle-miho** [comment]
Tested here: [#59](https://github.com/kyle-miho/liferay-portal/pull/59). Most of the unique failures seem to be random / a cause of panels passing. One is dependent on being able to assert non case-sensitive text.

**Comment by kyle-miho** [comment]
@jbalsas

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Pushed to BChan. I redid the SF to be sure.
https://github.com/brianchandotcom/liferay-portal/pull/57021

**Pull request closed without merging**
