### PR TITLE
Revert "LPS-66561 This check is not longer needed." This function is used in other places (e.g. quick edit popup.)

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
@brandizzi @brunobasto Is there a quick test that can be written for this? This doesn't look like a high risk for regression.

**Comment by brandizzi** [comment]
@vicnate5 would you like a POSHI test for that, then? Just confirm it and I'll proceed with taht :)

**Comment by vicnate5** [comment]
@brandizzi I am not sure a poshi test is the best way to just assert the name shows up without the resource. Unless we don't have another method to test this right now.

**Comment by brandizzi** [comment]
@vicnate5 well, a JavaScript test would be perfect to that, but we do not have infrastructure for it yet...

**Comment by vicnate5** [comment]
@brandizzi Ok. We can poshi test this for now. I need to check, but this might just require us to update an existing test. We already have some tests that assert the calendar names listed with the site name.

I am going to build this pull and confirm. If it is the quick change I think it is, I can take care of this.

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-26201

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41020

**Pull request closed without merging**
