### PR TITLE
LRQA-33643 JSON conversions for master

### PR DESCRIPTION
**Pull request by BChenLR**

### CODE REVIEW

**Comment by BChenLR** [comment]
https://issues.liferay.com/browse/LRQA-33643

**Comment by vicnate5** [comment]
Looks good with the SF commit. 

Asked Foundation team for a review of the tests we converted to identify which tests should still use the UI, will move this forward once I hear back from them.

**Comment by vicnate5** [comment]
CC @christianstokes

**Comment by vicnate5** [comment]
List of tests to use for the UI permissions testing
```
CPRolesPGBlogs#AddBlogsEntryOrgRole
CPRolesPGBlogs#AddBlogsEntryRegRole
CPRolesPGBlogs#AddBlogsEntrySiteRole
RolesandpermissionsUsecase#GroupScopePermissionCheck
```
per @alee8888

**Comment by BChenLR** [comment]
@alee8888 @vicnate5 Repushed with rebase to revert specified testcases.

**Comment by vicnate5** [comment]
Pushed to Albert
https://github.com/alee8888/liferay-portal/pull/462

**Pull request closed without merging**
