### PR TITLE
LRQA-32402 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-32402

@vicnate5 these are the only changes I could see that needed adding to master.  The other FW tests on master were already turned on or re-added.

**Note** that cherry picking to add `AssignThenApproveWorkflowTaskAsPortalContentReviewer` had a conflict, as it brought `ApproveWorkflowTaskAsSiteAdmin` with it.  You can remove the latter test from the commit if you see fit - but that test addition will make the testcase file on master and 7.0 identical.

### CODE REVIEW

**Comment by vicnate5** [comment]
@brianwulbern Both tests in https://github.com/vicnate5/liferay-portal/pull/786/commits/31b31c95b0844c5083a9d9f453959cbdec0c7996 were removed under https://issues.liferay.com/browse/LPS-69532. We added integration tests to cover these. 

Because it was done under a story ticket, not sure if we will be able to backport the integration tests in the near future. (FYI we are using **LPS Task** tickets for future test conversions)

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/48915

**Comment by brianwulbern** [comment]
@vicnate5 gotcha, and thanks for the workflow update.  Man, I would _hope_ that our rule for not backporting stories wouldn't prevent our tests from running more efficiently on unit/integration tests.

**Comment by vicnate5** [comment]
@brianwulbern One of my devs is working on backporting all the workflow integration tests we have written recently.

**Comment by brianwulbern** [comment]
@vicnate5 Tremendous!

**Pull request closed without merging**
