### PR TITLE
LPS-102842 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Test Fix for LPS-102842

### CODE REVIEW

**Comment by vicnate5** [comment]
@achaparro Test fix for https://github.com/brianchandotcom/liferay-portal/pull/82834. I can send a follow up PR to BChan with this once we confirm your code is ready.

**Comment by vicnate5** [comment]
ci:test:upgrade-client

**Comment by achaparro** [comment]
Great @vicnate5! We have a plan

Thanks

**Comment by vicnate5** [comment]
ci:test:upgrade-client

**Comment by vicnate5** [comment]
ci:test:upgrade-client

**Comment by vicnate5** [comment]
https://github.com/achaparro/liferay-portal/pull/430

**Pull request closed without merging**
