### PR TITLE
LPS-69335 Attachs the Form as event target of the fields.

### PR DESCRIPTION
**Pull request by brunobasto**
@vicnate5,

It'd be also good to have tests for this one.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:reopen

**Comment by almonwork** [comment]
Hi @vicnate5,

This issue is affecting an EE customer. Any update on the PR?

Regards
  Alberto

**Comment by vicnate5** [comment]
@almonwork Sorry for the delay.

I pushed this to BChan: https://github.com/brianchandotcom/liferay-portal/pull/45139

**Comment by almonwork** [comment]
Thanks.

**Pull request closed without merging**
