### PR TITLE
master-qa-56331

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-56331

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Needs Sybase dump
https://testray.liferay.com/home/-/testray/case_results/1037512521

**Comment by vicnate5** [comment]
Will rerun after https://github.com/brianchandotcom/liferay-qa-portal-legacy-ee/pull/290 is merged

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/vicnate5/liferay-portal/pull/1430
https://github.com/brianchandotcom/liferay-portal-ee/pull/29400

**Pull request closed without merging**
