### PR TITLE
LPS-69214 BuildLang

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares @inacionery I have a concern with the UX on this story and I asked Charlles to take a look and to add some requirements to the ticket because it is currently blank.

This change means that there will Always be a pop-up when the user tries to leave the form builder. I am worried this might be too much.

Scenario:
1. A user creates the form
2. User navigates back
3. User gets pop-up warning that unsaved changes will be lost
4. User saves form
5. User navigates back again
6. User gets same pop up, even though they just saved

I changed the phrase of the message to `Any unsaved changes will be lost, are you sure you want to leave?` so that it sounds better in english and fixed the poshi tests, but I would like to get some feedback and requirements before pushing this in so that we can properly test this behavior in the future.

**Comment by marcellustavares** [comment]
Hey Victor, the pop up should just be shown if the data is unsaved.

Em 12 de dez de 2016 19:08, "Victor Ware" <notifications@github.com>
escreveu:

**Comment by dantasjadson** [comment]
@inacionery , please, update the message according to @vicnate5 feedback and check if the last step "6. User gets same pop up, even though they just saved" is happening. Because the correct scenario is:
    1. A user creates the form
    2. User navigates back
    3. User gets pop-up warning that unsaved changes will be lost
    4. User can choose between [leave and save] or [stay]
    5. If user choose [leave and save] he leaves form and save all changes
    6. If user choose [stay] he does not leave the form and continue navigating

User will get the modal again just if he makes changes on the form and tries to leave the form builder but, if he just navigates and did not make changes he will not get the modal anymore.

**Comment by inacionery** [comment]
Hey @vicnate5,

Please close this PR, I'll send another one with these changes.

Thanks!

**Comment by vicnate5** [comment]
New Pull: https://github.com/vicnate5/liferay-portal/pull/683

**Pull request closed without merging**
