### PR TITLE
LRQA-66273 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-66273

### CODE REVIEW

**Comment by kyle-miho** [comment]
all passed locally, index.html is attached to each jira ticket, theres almost 0 risk of not testing this on CI since everything is Site Scoped & Mainly UI Functionality checks

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test

**Comment by vicnate5** [comment]
@kyle-miho This looks good, but there is a slight issue. The new name of the testcase conflicts with the old testcase we have on 7.3 and earlier (where MDR is also tested along with fiftyonedegrees database - which we removed on master). I would like to backport these tests, but they will conflicts for sure. See https://github.com/liferay/liferay-portal-ee/blob/7.3.x/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/sites/mobiledevicefamilies/MobileDeviceFamilies.testcase

I cannot think of a good solution, do you have any thoughts?

**Comment by kyle-miho** [comment]
@vicnate5 in the older branches, we can add 2 extra commits , one before (rename MobileDeviceFamilies.testcase in legacy branches to any temporary but clean name), cherry-pick all of the master commits over so we dont have to deal with any conflicts, and then recombine them together w/ adjusting the property levels of the custom property MobileDeviceFamily test so we can test the same thing but in the same file (we can also seperate them but i think that its cleaner to have them all together, there shouldnt be any future conflicts with just 1 extra testcase)

**Comment by kyle-miho** [comment]
if you think this idea is okay i can send you pulls to the older branches as well (just let me know how far to backport to)

**Comment by vicnate5** [comment]
@kyle-miho That sounds good. Backport this as far back as we have the MobileDeviceFamilies testcase.

**Comment by kyle-miho** [comment]
7.3.x: https://github.com/vicnate5/liferay-portal-ee/pull/499
7.2.x: https://github.com/vicnate5/liferay-portal-ee/pull/500
7.1.x: https://github.com/vicnate5/liferay-portal-ee/pull/501

**Comment by vicnate5** [comment]
@kyle-miho I don't think the backports account for https://github.com/vicnate5/liferay-portal/pull/1702/commits/a33b491eded02ff465792e1d22027471def4c58d in the EE test

**Comment by kyle-miho** [comment]
@vicnate5 tests passed on the backports too

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/100997
https://github.com/brianchandotcom/liferay-portal-ee/pull/34140
https://github.com/brianchandotcom/liferay-portal-ee/pull/34141
https://github.com/brianchandotcom/liferay-portal-ee/pull/34142

**Pull request closed without merging**
