### PR TITLE
LRQA-74343

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:upgrade:nocompile

**Comment by vicnate5** [comment]
@AlfredSoto We are working on splitting the tests out for the Upgrades team.

What would you like the team name to be on Testray?

Options we thought of
1. "Upgrades Core" (Noting that this is the core of upgrades, not upgrades for all teams)
2. "Upgrades"
3. "Uniform" (new name under review)

Do you have a thought about this?

**Comment by koor4356** [comment]
ci:test:upgrade

**Comment by koor4356** [comment]
Okay, I will update that, thanks!

**Comment by koor4356** [comment]
ci:test:upgrade:nocompile

**Comment by vicnate5** [comment]
@koor4356 The backend upgrade tests are ending up under Core
https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1860204113&testrayTeamId=1310700713

Should be able to move these by changing the test.properties for their respective modules.

**Comment by koor4356** [comment]
okay, I will look. thanks!

**Comment by vicnate5** [comment]
Koor found that the upgrades backend tests are under modules/app/portal, so we cannot split right now.

Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/117973

**Pull request closed without merging**
