### PR TITLE
LRQA-73176

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:license-cluster:nocompile

**Comment by koor4356** [comment]
ci:retest:license-cluster:nocompile

**Comment by vicnate5** [comment]
@koor4356 Please investigate the further failures here.

**Comment by koor4356** [comment]
ci:retest:license-cluster

**Comment by vicnate5** [comment]
ci:test:license

**Comment by koor4356** [comment]
ci:test:cluster-license

**Comment by koor4356** [comment]
ci:test:license

**Comment by koor4356** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
@koor4356 Did something change or did we just have a corrupt build before?

**Comment by koor4356** [comment]
I think the issue may have to do with prebuild bundle. I am not really sure what has changed. I run the cluster license tests using "ci:test:license-cluster:nocompile" when they all failed.

**Comment by vicnate5** [comment]
@koor4356 That makes sense, the pre-built bundle will not work for the license tests because they need a release bundle.

**Comment by vicnate5** [comment]
@koor4356 See https://github.com/liferay/liferay-portal/blob/7707483ca38025bd57fdc5ab828f82ffe1932c3f/test.properties#L3473

If this is set, you cannot use `nocompile`

**Comment by koor4356** [comment]
Awesome, thanks for pointing this out.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/113982

**Pull request closed without merging**
