### PR TITLE
LRQA-59555 | master

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/90796

**Comment by richiezhao** [comment]
ci:test:environments-release-dxp

**Pull request closed without merging**
