### PR TITLE
LRQA-49173 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-49173

### CODE REVIEW

**Comment by vicnate5** [comment]
@john-co will `Icon#DELETE` not work for this instead?

**Comment by john-co** [comment]
@vicnate5 that should work too. I'll update the path to Icon#DELETE and deprecate the old icon path.

**Comment by john-co** [comment]
@vicnate5 updated, test works locally.

**Comment by vicnate5** [comment]
@john-co Please make sure to use more general paths whenever possible.

Is this needed on any other branches?

**Comment by john-co** [comment]
@vicnate5 Currently it is only needed on 7.2.x

It likely to have been caused by https://issues.liferay.com/browse/LPS-92038 and it hasn't been backported to other affected branches 7.1.x and 7.0.x. How do we know if it will be fixed for the other branches down the road?

**Comment by vicnate5** [comment]
@john-co if we know the LPS cause, you can change the commits to use that LPS, that would make sure it gets backported alongside the rest of the LPS.

**Comment by john-co** [comment]
@vicnate5 gotcha, done

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73403

**Pull request closed without merging**
