### PR TITLE
Friendly URL with shared locales but different languages

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-53821

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by vicnate5** [comment]
@koor4356  What is up with the `[beta]` icon? Is this specific to certain languages?

**Comment by koor4356** [comment]
@vicnate5, I do know if the language still in the beta version. It shows up when selecting Britain and Australia English.

**Comment by vicnate5** [comment]
@koor4356 Please use non-Beta languages for this testing. I am worried about maintenance since these will one day have the "Beta" part removed probably.

**Pull request closed without merging**
