### PR TITLE
LRQA-55470 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-55470

### CODE REVIEW

**Comment by kyle-miho** [comment]
the jar is published as portal-master since we didnt branch yet, we'll have to use this naming for now

**Comment by kyle-miho** [comment]
This is required for us to generate the DB archive

**Comment by vicnate5** [comment]
@kyle-miho will this resolve to 7.3 even though we haven't branched?
```
portalVersion.startsWith("7.3")
```

**Comment by kyle-miho** [comment]
> @kyle-miho will this resolve to 7.3 even though we haven't branched?
> 
> ```
> portalVersion.startsWith("7.3")
> ```

https://github.com/kyle-miho/liferay-qa-portal-legacy-ee/pull/1/files
yea it should, that is a file directory match

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/84343

**Pull request closed without merging**
