### PR TITLE
LRQA-74248 DB2 11.5

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments:nocompile

**Comment by vicnate5** [comment]
ci:test:environments:nocompile

**Comment by vicnate5** [comment]
ci:test:environments:nocompile

**Comment by vicnate5** [comment]
ci:test:environments:nocompile

**Comment by vicnate5** [comment]
ci:test:environments:nocompile

**Comment by koor4356** [comment]
ci:retest:environments:nocompile

**Comment by koor4356** [comment]
ci:close

**Comment by koor4356** [comment]
Testing this here: https://github.com/vicnate5/liferay-portal/pull/2044

**Pull request closed without merging**
