### PR TITLE
LRQA-66288 Create config file instead for readability and to avoid issues encountered when copying

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
@kyle-miho

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@kyle-miho Can you fix the upgrade test check and pull out Serveradministration#ViewGlobalLibDirectory from environment acceptance for now? (we need to update this test for a change Shuyang made anyways)

Resend this to me when you have these fixes. We need at least baseline relevant to pass.

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Pull request closed without merging**
