### PR TITLE
Database partitioning with clustering

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-58440

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/89121

**Comment by vicnate5** [comment]
closed the wrong one..

**Comment by vicnate5** [comment]
@koor4356 I just had a chance to review today and I am going to close this for now because I am rethinking the requirements for this test.

see discussion on https://docs.google.com/document/d/1PPGo4xruHyeAUC-xKuyh_viGSOdX1MdlOHAawMIQ6PE/edit?disco=AAAAJxlIHtU

**Pull request closed without merging**
