### PR TITLE
LRQA-82335 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://liferay.atlassian.net/browse/LRQA-82335

Tested in https://github.com/catarineaguiar/liferay-portal/pull/111.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@catarineaguiar I noticed that `AzureConnectionDoesNotLeakWhenServingFileAsStream` and `S3ConnectionDoesNotLeakWhenServingFileAsStream` are identical in their test scripts.

Could you extract out the logic into a macro file? That way we could avoid the duplicate code and simplify writing these tests for all types of stores.

I am thinking we could use the similar model as the [upgrade tests
](https://github.com/liferay/liferay-portal/blob/7665ca5bea07440485ac14e5b6cc5405d793cf1a/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalSmokeUpgrade.testcase) where the macros set the test logic and each test just calls the same macro. I assume this pattern could apply to other cloud store tests, since most of the behavior in the UI is identical.

This also enables you to write the GCS tests easily, even if CI doesn't support it yet.

CC @Kvale1733 since you were helping to write store tests.

**Comment by catarineaguiar** [comment]
@vicnate5 I have tested this same script on GCS and I got an error, not sure what is different on this, I need to investigate deeper. But I'm going to create the macro for the other cloud store tests. Thanks!!

**Comment by catarineaguiar** [comment]
see https://github.com/vicnate5/liferay-portal/pull/2409

**Pull request closed without merging**
