### PR TITLE
LPS-65794 Apply changes to select template page too

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
@vicnate5 This pr make changes on select structure and select template pages. Now, we are using a link in the name of structure/template to choose the structure/template instead of a button and these changes broke a lot of functional tests :sad.  Could you please take a look on that?
After that, you can sending this to Brian.

Thanks

/cc @marcellustavares

**Comment by vicnate5** [comment]
Cool. We take a look [LRQA-25456](https://issues.liferay.com/browse/LRQA-25456)

**Comment by vicnate5** [comment]
Pushed to BChan with test fixes.
https://github.com/brianchandotcom/liferay-portal/pull/40178

**Comment by rafaprax** [comment]
Thx @vicnate5

**Pull request closed without merging**
