### PR TITLE
LPS-171644 Fix cleanup between upgrade client tests

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-171644

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:upgrade:nocompile

**Comment by susanchen3** [comment]
upgrade client tests passing https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2150032857&testrayCaseName=LocalFile.DatabaseUpgradeClient

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/128433

**Pull request closed without merging**
