### PR TITLE
master-qa-53825

### PR DESCRIPTION
**Pull request by zhangyan0701**
This should cherry-pick cleanly back to 7.1.x

https://issues.liferay.com/browse/LRQA-53823
https://issues.liferay.com/browse/LRQA-53825

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@zhangyan0701 FYI we have a new test suite `upgrade-client` that can be used to just run the upgrade client tests, instead of all the upgrade tests in the `upgrade` suite

**Comment by vicnate5** [comment]
Testing backport https://github.com/vicnate5/liferay-portal-ee/pull/356

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
