### PR TITLE
LRQA-42945, LRQA-42944, and LRQA-42939

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 Test failure

**Comment by koor4356** [comment]
@vicnate5 
The issue has nothing to do with the test. The test has passed locally and also it just passed here: https://github.com/koor4356/liferay-portal/pull/108.

I have resent you new PR here: https://github.com/vicnate5/liferay-portal/pull/1704

**Pull request closed without merging**
