### PR TITLE
LPS-106592-LPS-103577 test

### PR DESCRIPTION
**Pull request by tinatian**
Hi Victor,

This pull is based on https://github.com/shuyangzhou/liferay-portal/pull/8899.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by tinatian** [comment]
Resend at https://github.com/vicnate5/liferay-portal/pull/1428

**Pull request closed without merging**
