### PR TITLE
LRQA-67531 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-67531

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@kyle-miho Please fix the SF

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@vicnate5 passed

**Comment by vicnate5** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/103174

**Pull request closed without merging**
