### PR TITLE
master-qa-55958

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-55958

### CODE REVIEW

**Comment by zhangyan0701** [comment]
In order to run ci test, I fetched Tina's branch LPS-106592-LPS-103577-63-test and sent them together with the new tests.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
SF failure is not related to my changes.

**Comment by zhangyan0701** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@zhangyan0701 The test functional steps pass, but the screenshot looks bad:
https://testray.liferay.com/reports/production/logs/test-1-17/1583815159172/test-portal-acceptance-pullrequest(master)/5412/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.ClusterSidecar_AddAndRemoveSidecarNodes/screenshots/before0.jpg.gz

About the errors you mentioned:
https://issues.liferay.com/browse/LRQA-55958?focusedCommentId=2101359&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2101359
This is strange because it happens on first startup only on this test?

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LPS-109888

**Comment by vicnate5** [comment]
@zhangyan0701 I had trouble running this locally because of issues on my machine, but my guess is that there is something different about the startup configuration or behavior because you are not starting the tomcat bundle until after the test starts. I would expect these ERRORs to show up on other Clustering tests, but they only display on this one. Something about the configuration is different or incorrect.

This could be a real bug, but we need steps to reproduce it.

**Comment by vicnate5** [comment]
Maybe those errors occur when hitting localhost before starting the portal?

**Pull request closed without merging**
