### PR TITLE
LPS-178120 Investigate Flaky Duplicate entry 'en_US-6-0' for key 'IX_E26CFF79' for Continuous Upgrade tests

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-178120

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@susanchen3 I went ahead and pushed this since it shouldn't hurt. You can keep the tests running here to see the results.
https://github.com/brianchandotcom/liferay-portal/pull/131525

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by susanchen3** [comment]
@vicnate5 the property doesn't work with DB Partitioning based on the results https://github.com/vicnate5/liferay-portal/pull/2278/commits/9d832424cbcf552ac9dbba702c8cd98a10d61479

**Comment by vicnate5** [comment]
@susanchen3 Can you try the DB partition test with `property custom.properties = "virtual.hosts.valid.hosts=localhost,127.0.0.1,www.able.com";` - this should correctly enable usage of the second company and might prevent errors.

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by susanchen3** [comment]
@vicnate5 
[LocalFile.PortalContinuousUpgrade#AutoUpgradeFromLatest7413UpdateWithDBPartitionEnabled](https://testray.liferay.com/home/-/testray/case_results/2233242488)
is passing now with these changes.

[LocalFile.PortalContinuousUpgrade#AutoUpgradeFromLatest7413Update](https://testray.liferay.com/home/-/testray/case_results/2233242795) seems to passing better as well with the change in https://github.com/liferay/liferay-portal/commit/dd0d0d6ccf08761ed33791d0fc915032fd2bec03 and test retries. 

Will continue to monitor and testing the tests with [POSHI-489](https://issues.liferay.com/browse/POSHI-489).

**Comment by vicnate5** [comment]
@susanchen3 So are these now the final commits you want merged?

**Comment by susanchen3** [comment]
@vicnate5 yeah

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/131780

**Pull request closed without merging**
