### PR TITLE
LPS-67823 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by ctampoya** [comment]
@vicnate5 There are a couple of instances when the 'esc' doesn't seem to be working as intended.

A. __Missing confirmation dialog after editing a field setting__ 
* Add a Text field
* Before editing any field settings, test that pressing 'esc' works to close sidebar
* Click on field to edit
* Edit field label

__Expected Result:__ There is a confirmation box to confirm field changes and the sidebar will close automatically.
__Actual Result:__ There is no confirmation box to confirm changes. Pressing 'esc' does nothing. The only way to close the sidebar is by clicking the arrow on the upper right hand corner of the sidebar

B. __The 'esc' functionality only works on the first form you create__
* Add a Form on a clean database
* Test that pressing 'esc' closes the sidebar 
* Add a field to the form
* Save Form
* Add a second Form
* Add a form field (do not edit any field settings) 
* Press 'esc'

__Expected Result:__ Pressing 'esc' works exactly how it did when the first Form was created.
__Actual Result:__ Pressing 'esc' does nothing.
I noticed this to also be true when editing the Form. 

cc @fernandosouza @brunobasto

**Comment by ctampoya** [comment]
@brunobasto @fernandosouza Can you guys take another look at this?

**Comment by fernandosouza** [comment]
Thx, @ctampoya. I will take a look as soon as I can.

**Comment by fernandosouza** [comment]
@ctampoya, a new PR was sent to @brunobasto. https://github.com/brunobasto/liferay-portal/pull/714

**Pull request closed without merging**
