### PR TITLE
LRQA-46979, LRQA-47009, LRQA-47032, LPS-91182 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-46979
https://issues.liferay.com/browse/LRQA-47009
https://issues.liferay.com/browse/LRQA-47032
https://issues.liferay.com/browse/LPS-91182

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
cc @brianchiu @kyle-miho see 0b916b5

**Comment by vicnate5** [comment]
build time for full testing is insane...

**Comment by vicnate5** [comment]
@anthony-chu rebase conflict, can you fix and resend

**Comment by anthony-chu** [comment]
Resent here: https://github.com/vicnate5/liferay-portal/pull/1139

**Pull request closed without merging**
