### PR TITLE
LPS-163671 Uniform | Automated test NewCompanyStillAccessibleAfterRestartWithCaseInsensitiveDatabase

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:db-partition

**Comment by lucasperj** [comment]
ci:test:relevant

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
@vicnate5 - failures in ci:test:db-partition not related.

**Comment by vicnate5** [comment]
@lucasperj overall this test looks pretty good, but can you resend with some changes?

Testcase
1. Change new property name to `database.lowercase.enabled`. We use the "enabled" name for boolean properties in Poshi.
2. For `SQL.executeMySQLStatement` just inline the query since it is only used once. Do not create a variable for single usage. (maybe also merge the first two "task" blocks into 1)
3. Rename `showVariableState` to `variableQueryResult` since the variable is a result of the query.

build-test.xml
1. Is the value change for `database.docker.database.options` needed for local runs? It was null before and didn't break anything to my knowledge (remember that on CI, that property was already set previously)
2. Rename `database.docker.database.options.clause` to `database.docker.database.options.new`

Ping me on Slack if you have any questions.

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/124571

**Pull request closed without merging**
