### PR TITLE
Revert "LRQA-34760 Quaratine forms tests until LPS-74430 and LPS-74478 are fixed"

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 Can you test locally? I fixed the issue regarding DDLRuleBuilder.render template. The others issues are related to change to Bootstrap 4. Thanks!

**Comment by vicnate5** [comment]
@leoadb I don't think I can do anything until the portal compile is fixed. I will run a retest here once it is and check locally.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
The Workflow + Forms functional test will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/51601

The Preview and Publish test runs into a bug.

Requires specific Steps to Reproduce:
1. Add form
2. Add Text field
3. Close sidebar
4. Click "Publish"
5. Click "Preview"
6. Close preview window
7. Type in browser: Localhost:8080
8. Go to Site > Forms
9. Edit Form by name

Result: Form does not load.

**Comment by leoadb** [comment]
@vicnate5 Could not reproduce locally :( ... trying again ...

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
@leoadb 
Reproduced on [this bundle](https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2388/bundles/liferay-portal-bundle-tomcat.zip ) + Firefox 45 and Chrome 60

Video of the behavior:
formnotloading

**Comment by leoadb** [comment]
@vicnate5 trying one more time ...

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
Test fix tracking https://issues.liferay.com/browse/LRQA-35057

**Comment by vicnate5** [comment]
https://github.com/leoadb/liferay-portal/pull/374

**Pull request closed without merging**
