### PR TITLE
LPS-69417 Fix how to get siblings nodes

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 Please forward to Brian if all broken Poshi tests pass. Thanks !!!

cc @marcellustavares

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@ctampoya Can you take a look at this one when the test results come in?

**Comment by ctampoya** [comment]
@vicnate5 Yes I can =)

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
@vicnate5 Looks good. 

cc @leoadb

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45167

**Pull request closed without merging**
