### PR TITLE
LPS-166777 | Fix FileConfigsWillTriggerDataCleanup TEST

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@lucasperj Can you explain how or why this fixes the test? (ideally the git commit will contain the explanation)

**Comment by vicnate5** [comment]
@lucasperj 
`cleanUpSoftwareCatalogModuleData` is in https://github.com/liferay/liferay-portal/blob/master/modules/apps/data-cleanup/data-cleanup/src/main/java/com/liferay/data/cleanup/internal/configuration/DataCleanupConfiguration.java

`removeExpiredJournalArticles` is in https://github.com/liferay/liferay-portal/blob/master/modules/apps/data-cleanup/data-cleanup/src/main/java/com/liferay/data/cleanup/internal/configuration/DataRemovalConfiguration.java

So this test should be failing based on this change here. Going to close for now, please reopen or resend once this is cleared up.

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/125735

**Pull request closed without merging**
