### PR TITLE
LRQA-43950 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-43950

### CODE REVIEW

**Comment by john-co** [comment]
ci tests on https://github.com/john-co/liferay-portal/pull/16

need backport to 7.1.x
CC @patriciajeanperez, @iovaneale

**Comment by vicnate5** [comment]
@john-co Do you know if this resolves https://issues.liferay.com/browse/LRQA-43949 as well?

**Comment by john-co** [comment]
This will resolve the forms issue.
Test for websphere: https://github.com/john-co/liferay-portal/pull/17

**Comment by vicnate5** [comment]
Please resend with additional work from https://github.com/john-co/liferay-portal/pull/17 is done

**Pull request closed without merging**
