### PR TITLE
LPS-119582 Reset the state of merge layout prototypes thread local

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hey @vicnate5, integration test failure is fixed here. and DB partitioning issue is reproducible even without this PR, please see https://issues.liferay.com/browse/LPS-122281 for details.
Thanks!

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test

**Comment by vicnate5** [comment]
@pavel-savinov I am unable to reproduce https://issues.liferay.com/browse/LPS-122281 at head on master and the poshi test for this scenario is passing at head.

On this PR, I am unable to access a new virtual instance that uses database partitioning. The poshi test is also failing. The new virtual instance URL causes a redirect loop. I manually checked this multiple times on a master bundle vs this PR bundle.

**Detailed steps to reproduce the Regression:**
1. Setup /etc/hosts file for custom URL:
```
127.0.0.1 localhost
127.0.0.1 www.able.com
```
2. Create fresh MySQL database
3. Setup portal-ext based on CI settings
```
plugin.notifications.enabled=false
jdbc.default.jndi.name=
jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.password=
jdbc.default.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
jdbc.default.username=root
jdbc.default.connectionTimeout=600000
jdbc.default.maximumPoolSize=20
jdbc.default.minimumIdle=0
jdbc.counter.maximumPoolSize=5
jdbc.counter.minimumIdle=0
jdbc.default.initialSize=0
jdbc.default.maxActive=20
jdbc.default.maxIdle=0
jdbc.default.minIdle=0
jdbc.counter.initialSize=0
jdbc.counter.maxActive=5
jdbc.counter.maxIdle=0
jdbc.counter.minIdle=0
company.security.strangers.verify=false
browser.launcher.url=
setup.wizard.enabled=false
mail.send.blacklist=
mail.session.jndi.name=
module.framework.properties.dependency.manager.sync.timeout=1800
module.framework.properties.initial.system.check.enabled=true
sprite.root.dir=/tmp/sprite
memory.scheduler.org.quartz.threadPool.threadCount=1
persisted.scheduler.org.quartz.threadPool.threadCount=1
virtual.hosts.default.site.name=
com.liferay.portal.servlet.filters.strip.StripFilter=true
web.server.http.port=8080
admin.email.from.address=test@liferay.com
announcements.email.to.address=noreply@liferay.com
login.secure.forgot.password=false
database.partition.enabled=true
```
4. Start server
5. Login and Navigate to Control Panel > Virtual Instances
6. Create a new instance with `www.able.com` in all fields
7. Attempt to navigate to `www.able.com:8080`, will cause a redirect loop.

URL modified to
```
http://www.able.com:8080/c/portal/login?redirect=%2Fweb%2Fguest%2Fhome%3Fp_p_state%3Dmaximized%26p_p_mode%3Dview%26refererPlid%3D19%26saveLastPath%3Dfalse%26_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName%3D%252Flogin%252Flogin%26p_p_id%3Dcom_liferay_login_web_portlet_LoginPortlet%26p_p_lifecycle%3D0%26_com_liferay_login_web_portlet_LoginPortlet_redirect%3D%252Fweb%252Fguest%252Fhome%253Fp_p_state%253Dmaximized%2526p_p_mode%253Dview%2526refererPlid%253D19%2526saveLastPath%253Dfalse%2526_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName%253D%25252Flogin%25252Flogin%2526p_p_id%253Dcom_liferay_login_web_portlet_LoginPortlet%2526p_p_lifecycle%253D0%2526_com_liferay_login_web_portlet_LoginPortlet_redirect%253D%25252Fweb%25252Fguest%25252Fhome%25253Fp_p_state%25253Dmaximized%252526p_p_mode%25253Dview%252526refererPlid%25253D19%252526saveLastPath%25253Dfalse%252526_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName%25253D%2525252Flogin%2525252Flogin%252526p_p_id%25253Dcom_liferay_login_web_portlet_LoginPortlet%252526p_p_lifecycle%25253D0%252526_com_liferay_login_web_portlet_LoginPortlet_redirect%25253D%2525252Fweb%2525252Fguest%2525252Fhome%2525253Fp_p_state%2525253Dmaximized%25252526p_p_mode%2525253Dview%25252526refererPlid%2525253D19%25252526saveLastPath%2525253Dfalse%25252526_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName%2525253D%252525252Flogin%252525252Flogin%25252526p_p_id%2525253Dcom_liferay_login_web_portlet_LoginPortlet%25252526p_p_lifecycle%2525253D0%25252526_com_liferay_login_web_portlet_LoginPortlet_redirect%2525253D%252525252Fweb%252525252Fguest%252525252Fhome%252525253Fp_p_state%252525253Dmaximized%2525252526p_p_mode%252525253Dview%2525252526refererPlid%252525253D19%2525252526saveLastPath%252525253Dfalse%2525252526_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName%252525253D%25252525252Flogin%25252525252Flogin%2525252526p_p_id%252525253Dcom_liferay_login_web_portlet_LoginPortlet%2525252526p_p_lifecycle%252525253D0&refererPlid=19&p_l_id=19
```

This database partitioning feature is critical for Portal offering SaaS on DXP Cloud.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by vicnate5** [comment]
https://github.com/pavel-savinov/liferay-portal/pull/655

**Pull request closed without merging**
