### PR TITLE
LRQA-58543 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-58453

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/88628

**Comment by vicnate5** [comment]
Thanks for taking care of the backports

**Pull request closed without merging**
