### PR TITLE
master-qa-47817

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-47817

This is for master only.

/cc @GinsonRen, @brianwulbern

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 Even though this fix does not completely resolve the problem on 7.1.x. I still think it is worth updating 7.1 to a service module.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70943
https://github.com/brianchandotcom/liferay-portal-ee/pull/23833

**Pull request closed without merging**
