### PR TITLE
LRQA-31546 LRQA-35462 LRQA-35463 | master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-31546

### CODE REVIEW

**Comment by pcwhite** [comment]
ci:retest

**Comment by pcwhite** [comment]
ci:stop

**Comment by pcwhite** [comment]
ci:retest

**Comment by vicnate5** [comment]
Nice job.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/52385

**Pull request closed without merging**
