### PR TITLE
LPS-81084 Field sidebar does not render Options fields

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@rafaprax No unique failures here, but there are some regressions at head :(

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/58724

**Comment by rafaprax** [comment]
@vicnate5 :(

**Pull request closed without merging**
