### PR TITLE
LRQA-46052 | master

### PR DESCRIPTION
**Pull request by anthony-chu**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test:sf

**Comment by anthony-chu** [comment]
@anthony-chu
- make open11 copies for tomcat
- make open11 copy for release-functional-tomcat...

**Comment by anthony-chu** [comment]
functional bundle batches:

- functional-bundle-marketplaceapp-smoke-tomcat-mysql57-open11
- functional-bundle-tomcat-db2111-open11
- functional-bundle-tomcat-hypersonic20-open11
- functional-bundle-tomcat-mariadb100-open11
- functional-bundle-tomcat-mysql57-open11
- functional-bundle-tomcat-oracle122-open11
- functional-bundle-tomcat-postgresql110-open11
- functional-bundle-tomcat-sybase160-open11
- functional-smoke-bundle-tomcat-mysql57-open11
- release-functional-smoke-bundle-tomcat-mysql57-open11

**Comment by anthony-chu** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Thanks @anthony-chu, had Kiyoshi take a look. 

I only needed the tomcat-mysql ones, and it was easier for me to reset the commits and patch those ones into a new commit.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66815
https://github.com/brianchandotcom/liferay-portal-ee/pull/23017

**Pull request closed without merging**
