### PR TITLE
LPS-131312 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-131312

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@kyle-miho I am still seeing a lot of hits when I grep for `com.liferay.cluster.test.module` (the module config id, some tests).

Please resend with the rename completed.

**Pull request closed without merging**
