### PR TITLE
LRQA-43073 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-43073

@vicnate5 let me know if you think this is a good approach to handling the legacy tomcat version cleanup. if it's good, i have the backports for the other branches as well. thanks!

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@anthony-chu Looks good. go ahead and do the backport.

**Pull request closed without merging**
