### PR TITLE
LPS-66513 Generate file for DDM Checkbox soy

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
POSHI Test plan for this issue:

1. Go to Content > Forms
2. Add a Form
3. Add a Multiple Selection field
    1. Choose to show field as a Switcher
    2. Choose to NOT show field label
    3. Save form field
4. Save Form
5. Create a page
6. Add Form portlet
7. Select Form
8. View Multiple Selection field
9. Assert the field’s label is not visible

**Comment by vicnate5** [comment]
@pedroqueiroz94 Can you make an LRQA ticket for this test plan and link it here?

**Comment by pedroqueiroz94** [comment]
@vicnate5 @brunobasto This is the link for the LRQA ticket for this test plan https://issues.liferay.com/browse/LRQA-26308

**Comment by vicnate5** [comment]
This branch was pushed to me for review with test fixes.
https://github.com/vicnate5/liferay-portal/pull/435

**Pull request closed without merging**
