### PR TITLE
Deploy license xml to osgi directory

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-64651

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:license

**Comment by koor4356** [comment]
ci:retest:license

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@koor4356 The license bundle does not compile right now. I added back in the DXP apps and it caused an issue on CI that I am currently investigating.

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
https://github.com/vicnate5/liferay-portal/pull/1656

**Pull request closed without merging**
