### PR TITLE
LRQA-51076 Add jsf-jdk8 test to acceptance test runs

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-51076

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by koor4356** [comment]
ci:stop

**Comment by koor4356** [comment]
ci:retest:jsf

**Comment by vicnate5** [comment]
Not merging because the tests are failing and fix timeline is unknown

**Pull request closed without merging**
