### PR TITLE
LRQA-64648 Sort

### PR DESCRIPTION
**Pull request by vicnate5**
For 7.3.x as well

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:license

**Comment by koor4356** [comment]
ci:retest:license

**Comment by koor4356** [comment]
ci:stop

**Comment by koor4356** [comment]
ci:retest:license

**Comment by vicnate5** [comment]
ci:retest:license

**Comment by vicnate5** [comment]
Possible real bugs here, will check locally

**Comment by vicnate5** [comment]
ci:retest:license

**Comment by vicnate5** [comment]
Expecting one of the tests to fail due to https://issues.liferay.com/browse/COMMERCE-5721

Disabled the LCS test for now since LCS isn't in the bundle. Chas is looking into it

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
