### PR TITLE
LPS-64685 Disables submit button while evaluations are still pending

### PR DESCRIPTION
**Pull request by brunobasto**
hey @vicnate5,

This makes visibility expressions be evaluated as soon as the users types the text.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by vicnate5** [comment]
@brunobasto 
This pull needs some test fixes. The validation changes is marking it difficult for the test to click the "Add" button to save a new field. I already figured out a fix.

**Comment by brunobasto** [comment]
Oh, Ok. Thanks @vicnate5

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@brunobasto I have this all fixed and ready to go. However, I am concerned about the visible flashing this causes on the Submit buttons. Is the button re-rendering each time validation occurs?

**Comment by brunobasto** [comment]
hey @vicnate5, I noticed that too. This was done to prevent the user from submitting a form before the validation/visibility have been computed. Image that I have form where when "gender" has the value "male" 5 other fields show up, but the user submit the form even before those fields show up. If one of those fields are required, the form won't get submitted, of course, but if none of them are, the form is going to be submitted and the user will  never know that there were more fields to fill. I think the major issue is in the field setting modal, where the flashing is more noticeable. On the published form the flashing didn't annoy me as much. I showed it to Marcellus yesterday and he thought it was a good precaution to take. I can remove the flashing for the field settings modal and leave it on the published form, what do you think?

**Comment by brunobasto** [comment]
To answer you question, the button is not being rerendered, it's going from disabled state and back. Also, we can notice the flashing more because we are using portal on a localhost connection. For real users it wouldn't be a flashing. The transition would be slower.

**Comment by vicnate5** [comment]
I am still worried the flashing could also be easy to see for a real user as well. I connected on a Windows VM with IE 11 and could see it clearly on the Form portlet submission.

**Comment by brunobasto** [comment]
I'll talk to Jadson (UX) to see what he thinks.

**Comment by brunobasto** [comment]
Hey @vicnate5,

Can you send me your PR with your test fixes? Jadson suggested some UX improvements that can make the flashing less annoying.

**Pull request closed without merging**
