### PR TITLE
LPS-114547 | master

### PR DESCRIPTION
**Pull request by vicnate5**
License workaround

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
maybe better to pass in the property to the ant call, will see how this goes

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
try setting hash to "master" in a future run

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
@kyle-miho can you pick this up and prioritize? This has a workaround to get the license test batch running (and it works), but there is another problem...The git commit file is not correctly updating to head as expected. Roy should be able to help fix this, the fix is needed Jenkins-side.

@tinatian you can cherry pick this https://github.com/vicnate5/liferay-portal/pull/1493/commits/59fb71306988175c883b63e19d75a3a9151c0505 to unblock your license PRs (make sure to rebase your `liferay-release-tool-ee` branch)

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRCI-1380

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Pull request closed without merging**
