### PR TITLE
LPS-64282 buildSoy

### PR DESCRIPTION
**Pull request by marcellustavares**
hey @vicnate5, could you help me to do a sanity check on this pull?

I've ran couple of tests manually but I'm still concerned to cause any regressions. We've removed the hardcoded paths for the dataProviderURL and the evaluatorURL in this pull, so technically everything that uses evaluation or data providers could be affected.

Let me know if we're good.

cc @brunobasto 

Thanks a lot!

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares This looks good. I ran all the tests against it.

**Comment by vicnate5** [comment]
@marcellustavares you want me to send this in?

**Comment by marcellustavares** [comment]
yes @vicnate5, thx

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37926

**Pull request closed without merging**
