### PR TITLE
LPS-85610 Update versions

### PR DESCRIPTION
**Pull request by anthony-chu**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
Failures during sign-in are unrelated to changes.

**Comment by vicnate5** [comment]
@anthony-chu is this good to go?

**Comment by anthony-chu** [comment]
looks like there's still some work that needs to be done. integration tests related to some of the jars are failing.

**Pull request closed without merging**
