### PR TITLE
LRQA-64640 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-64640

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:license
last fixes, tested locally

**Comment by kyle-miho** [comment]
ci:test:license

**Comment by vicnate5** [comment]
@kyle-miho Test failures on CI

**Comment by kyle-miho** [comment]
@vicnate5 passes now, tested here: https://github.com/kyle-miho/liferay-portal/pull/426
works with the *.log file, its due to the wait-for-console-log macro in build-test w/beanshell reading the *.log file not the *.xml file that poshi uses. Minor fixes adjusted locally, pull should be good

**Comment by kyle-miho** [comment]
ci:test:license

**Comment by kyle-miho** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
@kyle-miho Still failures on the cluster tests

**Comment by kyle-miho** [comment]
@vicnate5 this cannot be reproduced locally with run-selenium-tomcat, I think some of the cluster nodes could be possibly crashing in this batch (thats what it looks like), is there a way to check? (are these running on the 32gb nodes yet?)

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by kyle-miho** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/100423

**Pull request closed without merging**
