### PR TITLE
LRQA-42938

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance

**Comment by koor4356** [comment]
ci:retest:acceptance

**Comment by vicnate5** [comment]
@koor4356 How easy will this be to backport?

**Comment by koor4356** [comment]
@vicnate5,
Seen you backported this https://github.com/vicnate5/liferay-portal/pull/1704 to all 7.x.x branches except 7.0.x, I think we should do the same for this pull request. Also if backporting is not clean, let me know and I can send PR to each branch.

Thanks!

**Comment by vicnate5** [comment]
@koor4356 For https://github.com/vicnate5/liferay-portal/pull/1710/commits/c2d3d87bb891cc11cb23902e736e73d431dab4ca, this should be cleaned up by passing in the unique value as a variable "value" instead of a variable "name". Set a single variable (e.g. `test.command`), and then set it to the value that is needed for the config (e.g `-Dtest.command=invoke-method-portal`)

Then you can have a single echo statement in the build-test.xml script
`<echo file="${liferay.home}/osgi/configs/com.liferay.cluster.test.module.configuration.ClusterTestConfiguration.config">clusterTestCommand="${testCommand}"</echo>`
We should be avoiding stacking if/elseif when possible

Please resend.

**Pull request closed without merging**
