### PR TITLE
LPS-106592-LPS-103577 test

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
Rolling restart test instability due to https://issues.liferay.com/browse/POSHI-7. Requested CI team to prioritize.

New PR: https://github.com/vicnate5/liferay-portal/pull/1416, will just workaround by executing the test 5 additional times for each run.

**Comment by vicnate5** [comment]
@tinatian 
Examples of the random startup error

From https://github.com/vicnate5/liferay-portal/pull/1414
Cluster https://testray.liferay.com/reports/production/logs/test-1-12/1582223296432/test-portal-acceptance-pullrequest(master)/2384/functional-tomcat90-mysql57-jdk8/2/0/jenkins-console.txt.gz
Cluster https://testray.liferay.com/reports/production/logs/test-1-15/1582182101885/test-portal-acceptance-pullrequest(master)/2297/functional-tomcat90-mysql57-jdk8/4/0/jenkins-console.txt.gz

From this PR
Non-cluster https://testray.liferay.com/reports/production/logs/test-1-16/1582230094982/test-portal-acceptance-pullrequest(master)/5510/functional-tomcat90-mysql57-jdk8/36/0/jenkins-console.txt.gz
Non-cluster https://testray.liferay.com/reports/production/logs/test-1-16/1582230094982/test-portal-acceptance-pullrequest(master)/5510/functional-tomcat90-mariadb102-jdk8/4/0/jenkins-console.txt.gz

From https://github.com/vicnate5/liferay-portal/pull/1416
Cluster https://testray.liferay.com/reports/production/logs/test-1-14/1582230849982/test-portal-acceptance-pullrequest(master)/5524/functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
@joshchong could you take a look at this failure? I see it on many of our sidecar pulls https://testray.liferay.com/home/-/testray/case_results/1013687638

**Comment by joshchong** [comment]
@vicnate5 That test isn't meant to run with sidecar enabled so you can ignore it.

**Pull request closed without merging**
