### PR TITLE
LRQA-57943 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@nhpatt @manoelcyreno test properties for headless, I based this off of the existing test suite

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:stop

**Comment by manoelcyreno** [comment]
ci:stop

**Comment by manoelcyreno** [comment]
ci:close

**Comment by manoelcyreno** [comment]
You can track it in this PR: https://github.com/manoelcyreno/liferay-portal/pull/92

**Pull request closed without merging**
