### PR TITLE
LRQA-38433, LRQA-38989 | master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-38433
https://issues.liferay.com/browse/LRQA-38989

### CODE REVIEW

**Comment by pcwhite** [comment]
@vicnate5 Updated!

**Comment by vicnate5** [comment]
@pcwhite Couple questions on this.

1) Why remove the check for THREAD_TABLE_POSTS when adding THREAD_TABLE_REPLIES, can we not check both? If one Posts now shows, instead of Replies, this feels like a significant change. Do we know why it changed?
2) Have you talked to anyone on the Collab team about these changes? We want to discuss this with the them because we are adding a new path to `MessageBoards.path`.

**Comment by pcwhite** [comment]
@vicnate5 
0. according to the newly added logic from [this PR](https://github.com/austinchiang/liferay-portal/pull/254), changing the value for LRQA-38989 is appropriate.
1. 'Posts' isn't even on the home section of MB, but 'Replies' is there, and i noticed other recent changes like [this](https://github.com/brianchandotcom/liferay-portal/pull/55296) to suggest that asserting 'Replies' present is what to do now for tests that are about to assert new post details from 'Home'.
2. Will talk to Collab team today about it.

**Comment by vicnate5** [comment]
Waiting on response from the Collab team.

**Comment by pcwhite** [comment]
@vicnate5 updated and ready for review!

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56058

**Pull request closed without merging**
