### PR TITLE
LRQA-72198

### PR DESCRIPTION
**Pull request by koor4356**
- LPS-72198 Assert Stopping blacklisted bundle is present in console
- LRQA-72198 Do not commit

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/111930

**Pull request closed without merging**
