### PR TITLE
LRCI-2150 Remove deprecated file

### PR DESCRIPTION
**Pull request by vicnate5**
@john-co @kyle-miho @kenjiheigel @Tim-Cao

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:acceptance-functional

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/101537

**Pull request closed without merging**
