### PR TITLE
LRQA-68068 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-68068

### CODE REVIEW

**Comment by kyle-miho** [comment]
Tested here: https://testray.liferay.com/home/-/testray/case_results?testrayCaseTypeId=101949&testrayBuildId=1542410102
Goal: make sure if a rare case occurs where the URL login fails for an unknown reason (Seems like 1/30 failures in CI for random tests once in a while for certain teams), it can at least fallback to the UI login to ensure stability for these tests at least

**Comment by vicnate5** [comment]
@kyle-miho What happens if the auto-login stops work completely for all testcases? Will all of them just start using the UI with this change?

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@vicnate5 we probably would be in the dark, but if it starts failing often, i added a "warning" with a screenshot (info on what happened) + echo (you cant throw an intentional warning in poshi right now by following a specific branch). Would this adjustment be okay?

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
