### PR TITLE
LRQA-59742 Headless API | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-59742

### CODE REVIEW

**Comment by kyle-miho** [comment]
BlogsSharing# and AppBuilder# have failed for sure (can run through tests abc order, but BlogsSharing should be faster to run)

**Comment by kyle-miho** [comment]
I have the attempted fix commited/reverted if you wanted to check the potential fix if you can manage tor reproduce it

**Comment by vicnate5** [comment]
Figured out steps to Reproduce to unblock Kyle, closing for now.

**Comment by vicnate5** [comment]
Fixes from Alberto
https://github.com/vicnate5/liferay-portal/pull/1600

**Pull request closed without merging**
