### PR TITLE
LPS-71394 BuildLang

### PR DESCRIPTION
**Pull request by diogo-lins**
cc @thiago-rocha

### CODE REVIEW

**Comment by vicnate5** [comment]
This looks good. Going to add a poshi test for deleting pages.

**Comment by vicnate5** [comment]
@diogo-lins Should we be able to delete a page without any confirmation from the user?

**Comment by diogo-lins** [comment]
@vicnate5 I asked to Jadson to check this behavior, when he answer this I will let you know.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/47831

**Pull request closed without merging**
