### PR TITLE
master-qa-27268

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-27268

@vicnate5 This should account for events created just after midnight on a test that starts just before midnight.

**Please backport to 7.0.x as you see fit**

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@vicnate5 I tried 'performance' testing the midnight calendar event issue by running CI three times between 11:30 and 11:45 (LA time).  Looks good from that point of view.

I did have a question about the locator in this conditional (https://github.com/vicnate5/liferay-portal/pull/527/commits/a6b5023088bd3cdab5b2d088f2082b38bfb29f2f): if `Calendar#SCHEDULER_VIEW_EVENT_NOT_TODAY` uses the following xPath:
'//td[not(contains(@class,'scheduler-today')) and contains(.,'${key_eventTitle}')]//div[@class='scheduler-event-content']/../../div'

then the following logic has a bunch of double-negatives, and I lose track:
```
					 <if>
						<not>
							<condition function="IsElementPresent" locator1="Calendar#SCHEDULER_VIEW_EVENT_NOT_TODAY" />
```

**Comment by vicnate5** [comment]
@brianwulbern Thanks for running tests on this, yea...these are a mess because we have had so many issues with this. Every time I try to clean it up I get lost too. Someday...

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42786
https://github.com/brianchandotcom/liferay-portal/pull/42787

**Pull request closed without merging**
