### PR TITLE
master-qa-30618

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-30618

### CODE REVIEW

**Comment by ctampoya** [comment]
ci:stop

**Comment by ctampoya** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@ctampoya There is something wrong with Forms.testcase here. Can you take a look?

**Comment by ctampoya** [comment]
Pushed with fix https://github.com/vicnate5/liferay-portal/pull/743

**Pull request closed without merging**
