### PR TITLE
LRQA-67078 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-67078

### CODE REVIEW

**Comment by kyle-miho** [comment]
Passed here: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1531999042&testrayRunId=1531999055
No need to backport, caused by login, which wasnt yet backported

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@kyle-miho Fix the SF and you can send this straight to BChan.

**Pull request closed without merging**
