### PR TITLE
LPS-144124_PoshiDependenciesArchiveFileCheck_20211228_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi  Victor,

https://issues.liferay.com/browse/LPS-144124

Can you help fix SF issues?

```
java.lang.Exception: Found 8 formatting issues:
1: Do not add binary archive files for test, they must be expanded: /home/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/cpusersandorganizations/dependencies/organizations-7.0.lar
2: Do not add binary archive files for test, they must be expanded: /home/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/knowledgebase/dependencies/KBArticlesWithMarkdown.zip
3: Do not add binary archive files for test, they must be expanded: /home/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/knowledgebase/dependencies/KBArticlesWithMarkdownChangedPriorities.zip
4: Do not add binary archive files for test, they must be expanded: /home/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/knowledgebase/dependencies/KBArticlesWithMetadata.zip
5: Do not add binary archive files for test, they must be expanded: /home/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/knowledgebase/dependencies/KBArticlesWithNoPriorityPrefix.zip
6: Do not add binary archive files for test, they must be expanded: /home/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/exportimport/dependencies/6210buildNumber.lar
7: Do not add binary archive files for test, they must be expanded: /home/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/exportimport/dependencies/bookmarks-corrupted.portlet.lar
8: Do not add binary archive files for test, they must be expanded: /home/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/sitetemplates/usecase/dependencies/class-site-template-7.0.lar
```

Related pulls:
7.3.x: https://github.com/vicnate5/liferay-portal-ee/pull/562
7.2.x: https://github.com/vicnate5/liferay-portal-ee/pull/563
7.1.x: https://github.com/vicnate5/liferay-portal-ee/pull/564
7.0.x: https://github.com/vicnate5/liferay-portal-ee/pull/565

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@Hijky Could you fix these? https://issues.liferay.com/browse/LRQA-72463

**Comment by ling-alan-huang** [comment]
I resolved conflicting files and resent: https://github.com/Hijky/liferay-portal/pull/9

**Pull request closed without merging**
