### PR TITLE
Lps 186650

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@susanchen3 is checking the results here

**Comment by susanchen3** [comment]
Still occurring on startup. [Full log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-38/test-portal-acceptance-pullrequest(master)/7832/functional-tomcat90-mysql57-jdk11_open/18/24/liferay-log.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
the stack shows the patch lib is not being used at all... this is just starting up with JDK11?

**Comment by shuyangzhou** [comment]
it is a gradle issue somehow, the portal-remote-jaxrs-whiteboard is not deploying the patch lib. I need to check with Peter for this.

**Comment by shuyangzhou** [comment]
ci:test:jdk11

**Comment by shuyangzhou** [comment]
@vicnate5 @susanchen3 I just need to rerun the jdk11 batch, right?

**Comment by susanchen3** [comment]
Reviewed, test failures aren't related. The JDK 11 error is no longer present. :heavy_check_mark: 

Unique semver error, but I don't think it's related to this PR.
```
     [exec] > Task :apps:object:object-web:packageRunBuild
     [exec] ../object-js-components-web/types/src/main/resources/META-INF/resources/index.d.ts(33,39): error TS2306: File '/opt/dev/projects/github/liferay-portal/modules/apps/object/object-js-components-web/types/src/main/resources/META-INF/resources/components/ManagementToolbar/ManagementToolbarSearch.d.ts' is not a module.
     [exec] src/main/resources/META-INF/resources/js/components/ModalAddColumns.tsx(149,18): error TS7006: Parameter 'searchTerm' implicitly has an 'any' type.
     [exec] Command /opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/tsc --emitDeclarationOnly exited with code 2
     [exec] Received 1
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] > Task :apps:object:object-web:packageRunBuild FAILED
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135960

**Pull request closed without merging**
