### PR TITLE
master-bchiu-upgrade

### PR DESCRIPTION
**Pull request by vicnate5**
Test upgrade client

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by vicnate5** [comment]
Closing this so I don't get too confused.

**Comment by vicnate5** [comment]
The issue is that the classpaths are sometime incorrectly generated. Resulting in the tool being unable to find the .jar with the classes it needs to run the upgrade. I am gonna continue with a possible workaround here https://github.com/vicnate5/liferay-portal/pull/342

**Pull request closed without merging**
