### PR TITLE
LRQA-79471

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LRQA-79471

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:stop:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@catarineaguiar Given that we have a smoke and non-smoke version of each test batch, this is going to cause PortalSmoke test to run 2 times on each DB. Can you remove the smoke batches?

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:stop:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@catarineaguiar Relevant might not run properly here since we only changed the test properties.

Can you cherry pick this on top of one of our dev PRs and resend so we can see what relevant does?

**Comment by catarineaguiar** [comment]
@vicnate5 okay, I'll do that. I forgot it doesn't work without code changes.

**Pull request closed without merging**
