### PR TITLE
Lps 89456 without upgrade

### PR DESCRIPTION
**Pull request by tinatian**
Hi @vicnate5 

Please verify with mysql8.

cc @shuyangzhou, this pull is just to test if there is anything wrong with mysql8, I am still working on a pull with the upgrade process and will send you later.

Thanks.
Tina.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:help

**Comment by vicnate5** [comment]
ci:bundle

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Hi @vicnate5 
Just found something wrong with this pull, I will close it and send you a new one later.


Tina.

**Pull request closed without merging**
