### PR TITLE
LRQA-67051 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-67051

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
passed here: https://github.com/kyle-miho/liferay-portal/pull/440

**Comment by vicnate5** [comment]
@kyle-miho I think this should be changed to have the user set their password in the UI as well, unless you know that is covered in the UI elsewhere. That seems to be a main difference for new users that we should check for.

**Comment by kyle-miho** [comment]
PasswordPolicies#ViewPasswordChangeableAndChangeRequired is the main test that confirms that a user can change their password through the UI as well as expecting it to be required by default
A lot of other tests still use password setting via the UI as a bonus as well

**Comment by vicnate5** [comment]
Based on your comment, I think we can skip this.

**Pull request closed without merging**
