### PR TITLE
LPS-64917 Bubbles events to parent field

### PR DESCRIPTION
**Pull request by brunobasto**
/cc @marcellustavares :this fixes the reordering of repeatable fields on WCM/DDL

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by vicnate5** [comment]
@ctampoya is going to take a look at this

**Comment by ctampoya** [comment]
@brunobasto There is an issue with editing the order of the repeating fields. When the fields are reordered, it does not save properly unless the page is refreshed before editing. 

Steps to reproduce:
1. Go to Dynamic Data Lists > Manage Data Definition
2. Add a Data Definition with a repeating Text field
3. Add a DDL 
4. Add a DDL Record with repeating fields in the order of "A" and "B" > Publish
5. Edit field to be in the order of "B" and "A" > Publish
6. View DDL record

Expected Result: The order is rearranged and is viewed in the correct order.
Actual Result: The order is not edited. A workaround this would be to refresh the page prior to reordering the repeating fields.

**Comment by vicnate5** [comment]
Hey @brunobasto 
Can you take a look at the issue Clarissa found? I am going to close this for now.

**Comment by brunobasto** [comment]
Hey @vicnate5 and @ctampoya,

Sure, I'll try to get to it asap.

Thanks

**Comment by brunobasto** [comment]
Hey guys,

I think I have fixed the issue @ctampoya found last time. I have sent @vicnate5 a fix: https://github.com/vicnate5/liferay-portal/pull/313

If everything goes well, you can send it to Brian.

Thx

**Pull request closed without merging**
