### PR TITLE
LRQA-56192 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-56192

### CODE REVIEW

**Comment by kyle-miho** [comment]
Tested here: https://github.com/kyle-miho/liferay-portal/pull/336
One of the locale.testcase functional tests is still kind of flakey, due to the Web Content creation page taking too long to load, however thats out of scope for this ticket

**Comment by vicnate5** [comment]
@kyle-miho Do these optimizations cause the need to isolate the test cases? Or do they require this change regardless?

**Comment by kyle-miho** [comment]
@vicnate5 they require the change regardless, maybe it should be seperated into a seperate ticket

**Comment by kyle-miho** [comment]
some of the testcases were failing because they broke the other tests by modifying the portal properties within portal causing the locale to change for the next test

**Comment by vicnate5** [comment]
Summer noticed one of these too https://github.com/brianchandotcom/liferay-portal/pull/85683

We don't need another ticket here.

**Pull request closed without merging**
