### PR TITLE
LPS-72435 | master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-39483

### CODE REVIEW

**Comment by pcwhite** [comment]
@vicnate5 Updated!

**Comment by vicnate5** [comment]
@pcwhite Commit messages?

**Comment by pcwhite** [comment]
@vicnate5 ok!

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
Pushed and rebased to new dev branch
https://github.com/vicnate5/liferay-portal/pull/951

**Pull request closed without merging**
