### PR TITLE
LRQA-55106 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-55106

### CODE REVIEW

**Comment by kyle-miho** [comment]
No regressions found in PR here: https://github.com/kyle-miho/liferay-portal/pull/324

**Comment by vicnate5** [comment]
@kyle-miho can you look into this one?
https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/370122/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FragmentsUI_AddFragmentToContentPage_/

**Comment by vicnate5** [comment]
How easy will this be to backport to legacy branches?

**Comment by kyle-miho** [comment]
@vicnate5 did you check the wrong test run, the first test run in the link pull had those failures. I fixed it in the case that sometimes the teardown to clean up the virtual Instance gets skipped(maybe its not included in teardown by some tests or the test fails in teardown), so we need to deactivate the module on compile so it doesnt time out waiting for the console text, since company addition / deletion is very slow 

I didnt see any failures related in the build after the fix
https://testray.liferay.com/home/-/testray/case_results?testrayCaseTypeId=101949&testrayBuildId=1000458879

**Comment by kyle-miho** [comment]
This "SHOULD" be easily backportable, the module itself should be directly cherry-pickable since it doesnt yet exist. It should be getting published so we dont have to worry about versioning. The only worry is that it may take a while since it may have to go through the backport process

**Comment by vicnate5** [comment]
@kyle-miho What happens if one or more of the osgi configs are not set?

**Comment by kyle-miho** [comment]
an exception will be throw most likely

**Comment by vicnate5** [comment]
Consider making the osgi configs required. Check the behavior if the user does not set these.

**Comment by kyle-miho** [comment]
ci:test:nocompile

**Comment by kyle-miho** [comment]
ci:test

**Comment by vicnate5** [comment]
@kyle-miho SF issue.

Also, what is the behavior if the user does not set the (now required) configs?

**Comment by kyle-miho** [comment]
Rebased SF into first commit, @vicnate5 if the user doesnt set the configs, since its now required an exception will be thrown stating that a config is not set, but should be set, and the module will not activate

**Comment by vicnate5** [comment]
Pushed to Shuyang.
https://github.com/shuyangzhou/liferay-portal/pull/8843

**Pull request closed without merging**
