### PR TITLE
LPS-62374 Add missing dependency

### PR DESCRIPTION
**Pull request by brunobasto**
hey @vicnate5,

Can you contact Felix Zhang to see if it fixes issues on the devices mentioned on the ticket?

Thanks,

/cc @brandizzi

### CODE REVIEW

**Comment by vicnate5** [comment]
@brunobasto I contacted Felix. Thanks!

**Comment by vicnate5** [comment]
@brunobasto can you go ahead and merge this? I was not able to reproduce it myself, but would it hurt to merge?

**Comment by brunobasto** [comment]
@vicnate5 Should be good to merge. Thanks!

**Comment by vicnate5** [comment]
@brunobasto Just needed a rebase :)

**Comment by brunobasto** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/36664

**Pull request closed without merging**
