### PR TITLE
LRQA-64652

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:environments-windows10

**Comment by vicnate5** [comment]
@koor4356 Did CI team add Windows to PR tester? Can I get the details for this solution?

**Comment by koor4356** [comment]
@vicnate5 
"Did CI team add Windows to PR tester?"
 I do not know this one.
"Can I get the details for this solution?"
I have come to this solution because CommerceSmoke tests are already running on the environment tester. I believe if property "environment.acceptance" is set for the test, then that test runs on the environment tester. So I have decide to add window because I looked at the batches and I did not see the window batch.  Thanks!

**Comment by vicnate5** [comment]
@koor4356 Anytime we add a new environment to PR tester, we need to confirm with CI team that the environment is actually available. Please confirm if Windows is available before making this change.

Based on the info in your comment, I am not sure we need to do anything for this ticket since Commerce Smoke is already on the environment tester. AFAIK windows is not available on the PR tester, but please confirm.

**Comment by koor4356** [comment]
Roy says that we have window on the environment tester. "We have windows environments available on the environment tester (https://test-2-1.liferay.com)"

**Pull request closed without merging**
