### PR TITLE
LRQA-54910 | master

### PR DESCRIPTION
**Pull request by john-co**
**Description**
The flaky issue between js.fast.load and slow test environments seems to have been fixed sometime between last year and now. This aims to re-enable js.fast.load on weblogic and websphere since they now seem stable [8 out of 8 passed](https://github.com/john-co/liferay-portal/pull/367).

**Test Plan**
Run smoke tests on weblogic and websphere, make sure they pass consistently.

**Jira Ticket**
https://issues.liferay.com/browse/LRQA-54910

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
@john-co [The original ticket](https://issues.liferay.com/browse/LRQA-53768) changed this back to 7.1.x. Do you want to revert on legacy branches or just master?

**Comment by john-co** [comment]
Hi @vicnate5 , ah I haven't tested this on 7.1.x...I can run some more tests on those branches tomorrow to be safe before backporting.

**Comment by john-co** [comment]
Hi @vicnate5 , I'm not able to reproduce the original flaky issue with js.fast.load enabled on the legacy branches down to 7.1.x.
7.3.x: https://github.com/john-co/liferay-portal-ee/pull/92
7.2.x: https://github.com/john-co/liferay-portal-ee/pull/93
7.1.x: https://github.com/john-co/liferay-portal-ee/pull/94

However, there is an existing bug on 7.3.x: https://issues.liferay.com/browse/LPS-126677

I think it will be ok to re-enable js.fast.load on all branches except 7.3.x to keep websphere tests unblocked until https://issues.liferay.com/browse/LPS-126677 is resolved.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Pushed to BChan.
Master https://github.com/brianchandotcom/liferay-portal/pull/98112
7.3.x with workaround https://github.com/brianchandotcom/liferay-portal-ee/pull/33118

**Pull request closed without merging**
