### PR TITLE
Sidecar 8858 Disabled | master

### PR DESCRIPTION
**Pull request by vicnate5**
Test impact of merging sidecar without releasing ES7

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
Unique acceptance failure: https://testray.liferay.com/home/-/testray/case_results/1009419114?tab=history

**Comment by joshchong** [comment]
@vicnate5 @tinatian, not sure if this was addressed already, but looking at the `ci:test` run above, I'm seeing some unique failures in the [central-requirements batch](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/369924/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.portal.modules/ModulesStructureTest/testScanGradleFiles/) and [modules-unit batch](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/296149/).

**Comment by vicnate5** [comment]
ES7 is not built here, the backend tests are still running?

**Comment by joshchong** [comment]
Yeah, the ES7 unit tests can run independently. This is how they're running upstream now.

**Pull request closed without merging**
