### PR TITLE
master-qa-59874

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-59874

This is only for master. Thanks!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
@zhangyan0701 if this fails again for unrelated failure on relevant and I don't see it today, you can manually push to BChan and reopen. US office is out Tomorrow and Monday.

**Comment by vicnate5** [comment]
ci:forward

**Comment by zhangyan0701** [comment]
Manually forwarded
[brianchandotcom#90925](https://github.com/brianchandotcom/liferay-portal/pull/90925)

**Pull request closed without merging**
