### PR TITLE
BLOCKED | master-qa-66319

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-66319

7.3.x: [vicnate5/liferay-portal-ee#509](https://github.com/vicnate5/liferay-portal-ee/pull/509)

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@zhangyan0701 Can this be backported?

**Comment by zhangyan0701** [comment]
@vicnate5 

This PR is for master only. I forgot that the location of mysql driver has changed on master, I thought that it could be cherry picked directly.
I send you the backport for 7.3.x in https://github.com/vicnate5/liferay-portal-ee/pull/509.

**Comment by vicnate5** [comment]
I need to find out if there is an alternate solution to committing the compiled JAR before I send this.

**Comment by vicnate5** [comment]
@zhangyan0701 We cannot merge this as a new jar in dependencies, Alberto will need to migrate the validator to the portal source code. You can still use this branch to verify the bug https://issues.liferay.com/browse/LPS-131173?focusedCommentId=2437349&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2437349

**Comment by vicnate5** [comment]
@zhangyan0701 Please resend using https://github.com/liferay/liferay-portal/tree/master/modules/util/portal-tools-db-partition-schema-validator

**Pull request closed without merging**
