### PR TITLE
LRQA-73901 Temporarily ignore lpkg batch in results that can appear in pull requests frequently

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-73901

### CODE REVIEW

**Comment by kyle-miho** [comment]
removed from relevant and acceptance, left in other batches like upstream, backend etc since the noise lpkg tests have failing in releases or upstream analysis is very minimal since they are in a seperate batch. This should remove all of the noise from PRs though, especially with the main jobs being run ci:test, relevant, etc

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@kyle-miho Do we need to ignore all LPKG tests? I think lpkg-base is the most common, I don't like the idea of losing all lpkg coverage.

**Comment by vicnate5** [comment]
Need reference(s) to the issue(s) that is causing us to disable these. Please resend.

**Pull request closed without merging**
