### PR TITLE
LRQA-47668 Add integration batches to jdk11 suite

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-47668

tested here: https://github.com/anthony-chu/liferay-portal/pull/602

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
I need a bundle for a different reason, so I am using this PR

**Comment by vicnate5** [comment]
This needs to be a little cleaner on the property side, discussing over Skype

**Comment by anthony-chu** [comment]
Resent here:
https://github.com/vicnate5/liferay-portal/pull/1149

**Pull request closed without merging**
