### PR TITLE
LPS-169833 Reactivate test and fix upgrade completion message

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-169833

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by susanchen3** [comment]
Test failures unrelated, [LocalFile.UpgradeReport#TotalRuntimeLogged](https://testray.liferay.com/home/-/testray/case_results/2121869734) passing

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/127561

**Pull request closed without merging**
