### PR TITLE
LRQA-73297 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-73297

This is only for master.

@vicnate5
cc @zhangyan0701

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:help

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/117223

**Pull request closed without merging**
