### PR TITLE
LPS-68076 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@brunobasto, there's still one failing test?

**Comment by vicnate5** [comment]
@marcellustavares, I talked to @fernandosouza about this already, he was looking into it.

**Comment by vicnate5** [comment]
Closing for now.

**Comment by marcellustavares** [comment]
@fernandosouza @diogo-lins, can we test locally before sending to Victor? Just send the PR to yourself.

**Comment by diogo-lins** [comment]
Ok @marcellustavares I will do this before.

**Pull request closed without merging**
