### PR TITLE
master-qa-25563

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-25563

### CODE REVIEW

**Comment by ctampoya** [comment]
cc @alee8888 @xbrianlee 

I added a path for Site Pages > Page: Update

**Comment by vicnate5** [comment]
@ctampoya you know why the calendar test failed?

**Comment by ctampoya** [comment]
@vicnate5 It looks like a fluke.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40510

**Pull request closed without merging**
