### PR TITLE
master-qa-42923

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-42923
https://issues.liferay.com/browse/LRQA-42924

@vicnate5 
https://docs.google.com/document/d/1YFKdKngyWcOi4xv7HOeDWkwVJ-ofkcgwxKeHsPo8I98/edit#heading=h.mj2wqyv4pphe
Test Case 2a is to upgrade from a release bundle and check the schema version is set to the latest. In order to avoid hardcoding the version, I call ant targets to rebuild database and run upgrade from 7.0.4, then compare the schema version after upgrade with the original one.

But running the test on CI got some errors when start up portal after upgrade from 7.0. I tried to reproduce on local, but couldn't. 

In the test, before starting portal, osgi/state and osgi/work folders are deleted. 

Could you help to check if there is something with the test? Are there some other steps needed in the test?

Here is the jenkins report:
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/388786/AXIS_VARIABLE=0,label_exp=!master/

Thanks a lot!

### CODE REVIEW

**Comment by vicnate5** [comment]
I was looking at this log since the one you posted is gone now
https://testray.liferay.com/reports/production/logs/test-1-14/1589270453190/test-portal-acceptance-pullrequest(master)/6005/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz

I think the problem is that the upgrade is still running when the test attempts to start the app server again. These 2 commands are running together: https://github.com/vicnate5/liferay-portal/pull/1491/commits/709186dcedc7e955587d5f1899fb9b5342d01d13#diff-1eea359c423e17426290aa30cd83d284R341-R347

I am not sure if we have logic to find out when an ant script execution is completed or how it works. It looks OK in the previous upgrade in the test, but that upgrade probably executed faster.

I am not sure the best solution. For now, try to put a 3 minute pause after the upgrade is started (before starting the app server up again). If that resolves the issue, then you have confirmed the problem.

**Comment by zhangyan0701** [comment]
@vicnate5 

Thanks for taking look at this!

I tried to pause 3 minutes after the upgrade from 7.0 as you recommended and tested in [#182](https://github.com/zhangyan0701/liferay-portal/pull/182).

The result looks good. No error in the portal log. This can resolve the issue.
https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/352451/AXIS_VARIABLE=0,label_exp=!master/

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Forwarding at https://github.com/vicnate5/liferay-portal/pull/1500

**Pull request closed without merging**
