### PR TITLE
LPS-189798 Only run tests on DXP

### PR DESCRIPTION
**Pull request by susanchen3**
https://liferay.atlassian.net/browse/LPS-189798

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@susanchen3 How does this accomplish the goal of forcing this to run on DXP?

**Comment by susanchen3** [comment]
@vicnate5 The PQL for Portal on release is 
```
    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][portal-release][portal]=\
        (portal.smoke == true) OR \
        (\
            (\
                (app.server.types == null) OR \
                (app.server.types ~ tomcat)\
            ) AND \
            (\
                (database.types == null) OR \
                (database.types ~ mysql)\
            ) AND \
            (portal.upgrades == true)\
        )
```
having set portal.upgrades causes those tests to run in that environment. Should I also include **property test.run.environment = "EE";**?

**Comment by vicnate5** [comment]
@susanchen3 Yea the EE property is the correct way. I think this is just another example of a broader issue with the `portal.upgrades` property. The name isn't clear what it is for.

What it should be for is "smoke" upgrade tests essentially.

Can you rename it across the codebase to to `portal.smoke.upgrades`?

**Comment by susanchen3** [comment]
@vicnate5 changes made

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/137513

**Pull request closed without merging**
