### PR TITLE
master-qa-78550

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://liferay.atlassian.net/browse/LRQA-78550
https://liferay.atlassian.net/browse/LRQA-81009
https://liferay.atlassian.net/browse/LRQA-80833

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
The SF failure is not related. It should be a source-formatter issue:
https://liferay.slack.com/archives/C1SJ64S9X/p1687231368700729?thread_ts=1687184246.725049&cid=C1SJ64S9X

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/136654

**Pull request closed without merging**
