### PR TITLE
master-qa-72657

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-72657
https://issues.liferay.com/browse/LRQA-73819

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@zhangyan0701 Why is this button DXP only? https://github.com/vicnate5/liferay-portal/pull/2007/commits/a62dfb65b5d60669632f39aacf7988a4553938ce

**Comment by zhangyan0701** [comment]
@vicnate5 This is the "Done" button in the Terms of Use modal for Commerce but in Spanish. So it's DXP only.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/114709

**Pull request closed without merging**
