### PR TITLE
LRQA-45555 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-45555

### CODE REVIEW

**Comment by kyle-miho** [comment]
Tested Here: https://github.com/kyle-miho/liferay-portal/pull/278

**Comment by vicnate5** [comment]
Testing backport https://github.com/vicnate5/liferay-portal-ee/pull/336

**Comment by vicnate5** [comment]
@kyle-miho The changes here seem to significantly increase the runtime of this test batch, maybe because of the database imports.

Previous run at head: 53 minutes
Your test on this PR: 1 hour 34 minutes
My test on 7.1.x: 1 hour 59 minutes

We may want to consider splitting this up into different batches (as we do elsewhere) or not always importing the databases and just run the tests in a order that prevents conflict.

I don't want to merge this an cause such a bottleneck (the slowest test batch prevents others from reporting results)

**Comment by vicnate5** [comment]
I have another idea.

The tests we know will break future tests due to database changes, make those tests "clean up" by running the database import at the end of the test

The risk here is that if the test fails it could cascade to break others, but I am OK with this.

**Pull request closed without merging**
