### PR TITLE
LPS-101178 Configure admin.email.from.address and announcements.email.to.address properties in tests

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @vicnate5 

[LPS-101178](https://issues.liferay.com/browse/LPS-101178) is caused by [LPS-84320](https://issues.liferay.com/browse/LPS-84320) because we are blacklisting the emails configured by default.

This is done to force final customer to properly configure their server instead of leaving it with the default email configuration.

In order to avoid breaking all tests, my proposal is to configure `admin.email.from.address` and `announcements.email.to.address` properties.

I have applied them in `build-test.xml` (*prepare-portal-ext-properties* target) and `portal-impl/test/portal-test.properties` more information see commit https://github.com/vicnate5/liferay-portal/pull/1265/commits/7d90806e765ca850d86eea8a963e8df9f8546202

/cc: @ericyanLr

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
@jorgediaz-lr Thanks for this fix. This resolves most of the test issues but there is still an issue on some of the tests. The test log is throwing a WARN message, which gets picked up by the log assertor.

Is there anyway to prevent or suppress this warning?

```
Email test@liferay.com will be ignored because it is included in mail.send.blacklist
```

```
     [exec] com.liferay.calendar.search.test.CalendarBookingIndexerTest > testBasicSearch STARTED
     [exec] 17:15:55,015 WARN  [com.liferay.calendar.test-executor-thread][MailMessageListener:135] Email test@liferay.com will be ignored because it is included in mail.send.blacklist
     [exec] 
     [exec] com.liferay.calendar.search.test.CalendarBookingIndexerTest > testBasicSearch PASSED
     [exec] 
     [exec] com.liferay.calendar.search.test.CalendarBookingIndexerTest > testMultiLocale STARTED
     [exec] 17:15:55,636 WARN  [com.liferay.calendar.test-executor-thread][MailMessageListener:135] Email test@liferay.com will be ignored because it is included in mail.send.blacklist
     [exec] 
     [exec] com.liferay.calendar.search.test.CalendarBookingIndexerTest > testMultiLocale PASSED
     [exec] 
     [exec] com.liferay.calendar.search.test.CalendarBookingIndexerTest > testTrash STARTED
     [exec] 17:15:56,351 WARN  [com.liferay.calendar.test-executor-thread][MailMessageListener:135] Email test@liferay.com will be ignored because it is included in mail.send.blacklist
```

Full Log: https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/76833/AXIS_VARIABLE=5,label_exp=!master/consoleText

**Comment by jorgediaz-lr** [comment]
Hi @vicnate5 

I am going to have a look to it, I will update you

**Comment by jorgediaz-lr** [comment]
Hi @vicnate5 

I have sent a new pr with an alternative solution, see https://github.com/vicnate5/liferay-portal/pull/1266

**Pull request closed without merging**
