### PR TITLE
LRQA-50061 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-50061

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:poshi

**Comment by vicnate5** [comment]
@john-co Test failed when run here https://testray.liferay.com/home/-/testray/case_results/682288542

Can you check into this?

**Comment by john-co** [comment]
ci:test:poshi

**Comment by john-co** [comment]
Hi @vicnate5, that test is failing in upstream, I pinged @lawrence-lee and will create a ticket for the failing test: https://testray.liferay.com/home/-/testray/case_results/684480888/history?tab=result&hideFilterPin=true

failure is not due to the commits in this pull.
Test had passed here: https://github.com/john-co/liferay-portal/pull/151#issuecomment-512946200

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/75953

**Pull request closed without merging**
