### PR TITLE
LPS-129625 Include non-DXP Commerce modules in Liferay Online

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:liferay-online

**Comment by epgarcia** [comment]
@vicnate5 looks like the same error I got in epgarcia#1022. There's a NullPointerException when blacklisting some commerce modules. As said, I wasn't able to reproduce this locally.

**Comment by vicnate5** [comment]
@epgarcia The error can be seen locally by downloading the bundle in this PR
https://files.liferay.com/private/bundles/test-1-14/jobs/test-portal-acceptance-pullrequest(master)/builds/7955/liferay-portal-bundle-tomcat.tar.gz
VPN mirror http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-14/jobs/test-portal-acceptance-pullrequest(master)/builds/7955/liferay-portal-bundle-tomcat.tar.gz

Modify the included portal-ext to your environment and add
```
include-and-override=portal-liferay-online.properties
include-and-override=portal-liferay-online-limit.propertie
```

The bundle here is using release packaging and licensing, so we will need to solve this issue in order to use the properties in a release bundle. In a release bundle, Commerce does not activate until the portal is fully started and Commerce license is registered.

**Comment by epgarcia** [comment]
@vicnate5 I have the same issue with this PR epgarcia#1023. I that one I haven't changed the blacklisted commerce modules. Are liferay-online smoke tests passing in upstream? Thanks for the help

**Comment by vicnate5** [comment]
@epgarcia Yes, you are correct, the issue is at head on master, I reproduced it with the current properties at head. Based on the test history there was a regression in the last week. I think I need to ask Core team to take a look since this involves the blacklist and licensing interaction.

Here is the bug ticket: https://issues.liferay.com/browse/LPS-129773

**Pull request closed without merging**
