### PR TITLE
LPS-65977 Add functional test to check comments on Workflow of Kaleo Process

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by vicnate5** [comment]
Does this depend on https://github.com/inacionery/liferay-portal-ee/pull/2?

I would also like to use a LRQA ticket for the New Test for tracking.

**Comment by vicnate5** [comment]
@inacionery

**Comment by inacionery** [comment]
Hi @vicnate5,

yes it's a dependency.

**Comment by vicnate5** [comment]
Sorry about the delay on this one. I am going to wait for the big fixes to Kaleo Forms testing framework https://issues.liferay.com/browse/LRQA-24107 before reviewing/merging this test.

**Comment by vicnate5** [comment]
Moving this test to ticket https://issues.liferay.com/browse/LRQA-25778

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41349

**Pull request closed without merging**
