### PR TITLE
master-qa-79367

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-79367

The new tests require PR https://github.com/liferay-core-infra/liferay-portal/pull/3260 to be merged.

Tested in https://github.com/zhangyan0701/liferay-portal/pull/450.

One test failure [PortalReadWriteDatabaseConfiguration#LockUnlockDMFileEntryAndMBTread](https://testray.liferay.com/home/-/testray/case_results/2189308677) should be a regression and also reported here https://github.com/liferay-core-infra/liferay-portal/pull/3260#issuecomment-1422637908

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@zhangyan0701 Looks good, you can combine this with the dev branch when able.

**Comment by vicnate5** [comment]
Added to dev PR, closing.

**Pull request closed without merging**
