### PR TITLE
LPS-65127 DDM freezes in loading frame when saving a new DDM field

### PR DESCRIPTION
**Pull request by brunobasto**
hey @vicnate5,

Just sending it to you to double check. If everything goes well, you can send it to BChan.

Thx,

### CODE REVIEW

**Comment by ctampoya** [comment]
@vicnate5 Everything looks good. :) 

cc @brunobasto

**Comment by ctampoya** [comment]
@vicnate5 This failure occurs when using a DDL display freemarker template with a text field script. I have recorded the steps to reproduce in this gist -https://gist.github.com/ctampoya/dde2e762906b07e7aaf3169012cf310c

cc @brunobasto

**Comment by ctampoya** [comment]
@vicnate5 Issue is also occurring at head on master GIT ID d95452accddce6ad44ce358fb2265756c7ec124d

**Comment by vicnate5** [comment]
@ctampoya Can you test the DDL records with the following template:

```
<#assign records = ddlDisplayTemplateHelper.getRecords(reserved_record_set_id)>

<#if records?has_content>
	<#list records as cur_record>
		<div class="ddl-record">${ddlDisplayTemplateHelper.renderRecordFieldValue(cur_record.getDDMFormFieldValues("Text")?first, locale)}</div>
	</#list>
</#if>
```

I don't think this is a bug.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/39178

**Comment by brunobasto** [comment]
Thanks, guys!

**Pull request closed without merging**
