### PR TITLE
LRQA-47668 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-47668

### CODE REVIEW

**Comment by vicnate5** [comment]
@anthony-chu  Do we need to set the override variables in `test-class` and `test-class-group`? Could we just pass them in as blank if those are not set?

**Comment by anthony-chu** [comment]
@vicnate5 and then let junit-cmd set the values of the override variables? i think that might be better. less defaulting everywhere. i can update this pull with the change.

**Comment by vicnate5** [comment]
Running final tests at https://github.com/vicnate5/liferay-portal/pull/1153

**Comment by vicnate5** [comment]
Pushed to Shuyang.
https://github.com/shuyangzhou/liferay-portal/pull/7571

**Pull request closed without merging**
