### PR TITLE
LPS-127182 Execute SF to change all build.gradle files

### PR DESCRIPTION
**Pull request by jkappler**
Hi @vicnate5, I prefer to run this through you since many modules used the library with the vulnerability. If you prefer that I send it to someone else, please let me know.

As always, thanks for the help!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
@csierra, @javierdearcos

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@jkappler No regressions found in the test results.

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
FYI @shuyangzhou

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by jkappler** [comment]
thanks @vicnate5!

**Comment by vicnate5** [comment]
ci:reevaluate

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
Test failures not related.

Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/98551

**Pull request closed without merging**
