### PR TITLE
LPS-66384 DDL Details Column starts closed

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
@thiago-rocha We have a method with poshi to check CSS values. Would this be the best way to write a regression test for this fix?

**Comment by brunobasto** [comment]
Hey @vicnate5,

I think it would be enough to check for the class.

**Comment by vicnate5** [comment]
Thanks, Talked to @thiago-rocha about this. We have a way to test this. Will test with poshi.

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-26274

**Comment by vicnate5** [comment]
Pushed to BChan with poshi test.
https://github.com/brianchandotcom/liferay-portal/pull/41130

**Pull request closed without merging**
