### PR TITLE
master-qa-20823

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-20823

### CODE REVIEW

**Comment by vicnate5** [comment]
Want to wait for CI results on this one since we are adding to the PR tester

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Merge conflicts :( Can you resend? that will clear this off CI queue as well.

**Comment by ctampoya** [comment]
oh yea,. i will take a look at it

**Pull request closed without merging**
