### PR TITLE
master-qa-80226

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-80226
https://issues.liferay.com/browse/LRQA-80271

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:portal-context-path

**Comment by zhangyan0701** [comment]
ci:test:portal-proxy-path

**Comment by zhangyan0701** [comment]
ci:test:portal-context-path

**Comment by zhangyan0701** [comment]
ci:test:portal-proxy-path

**Comment by vicnate5** [comment]
@zhangyan0701 I won't have a chance to review this week, will pick it up next week.

**Comment by vicnate5** [comment]
ci:test:stable:nocompile

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/133936

**Pull request closed without merging**
