### PR TITLE
LPS-89024

### PR DESCRIPTION
**Pull request by Preston-Crary**
This is the high risk change we talked about.  Please run this against all the functional tests and see if there's anything breaking because of this change.

Thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by vicnate5** [comment]
Master: https://github.com/vicnate5/liferay-portal/pull/1084
Master-private: https://github.com/vicnate5/liferay-portal-ee/pull/165

**Comment by Preston-Crary** [comment]
Fixed the LibraryReferenceTest failure, do any of the functional tests look like they are caused by this?

**Comment by vicnate5** [comment]
@Preston-Crary We don't have any functional tests related to the issue with the LibraryReferenceTest.

Only unique failure in the functional layer was a failure with Clustering + Staging. Likely not related to your changes, I am re-running the test.

**Comment by Preston-Crary** [comment]
Thanks!

**Pull request closed without merging**
