### PR TITLE
master-qa-21733

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-21733

### CODE REVIEW

**Comment by kenjiheigel** [comment]
It was a little more involved than I anticipated, but I think this should be relatively cleaner. It should just pass the siteName var along if it's not set to Liferay and we won't have to deal with the defaultSiteName var anymore. I only tested the variable passing logic of the macro, under different conditions, which works as expected. 

I ended up just running all the functional tests cause there's other tests that will use it. I added your two tests in though in the "DO NOT PUSH..." commits. Let me know if there's still issues. 

Thanks!

**Comment by vicnate5** [comment]
Awesome. Thanks Kenji

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35600

**Pull request closed without merging**
