### PR TITLE
LPS-65554 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by ctampoya** [comment]
@vicnate5  I found a couple of issues with the "Add other option" feature. I have written steps for them below. 

Issue 1: Missing language keys for "Add Other Option" switcher 
  1. Add a Form
  2. Add a Select field 
  3. View "Add Other Option" switcher
   
*Current Result:* Switcher title is missing language keys.
  
Issue 2: When submitting a Form with "Other" as the selected choice, an error message _"A custom field validation failed."_ appears and the select option cannot be submitted.
  1. Add a Form 
  2. Add a Select field > Set "Add Other Option" to true
  3. Enter an option as "A"
  4. Save Form 
  5. Add Form portlet to a page and select created Form
  6. Choose option "A" > Submit
  7. Choose option "Other" > Submit
   
*Current Result:* When a User tries to submit a Form entry with the value "Other", a validation error appears and the entry is not submitted.

cc @brunobasto

**Comment by vicnate5** [comment]
cc @thiago-rocha

**Comment by vicnate5** [comment]
@brunobasto Can you or @thiago-rocha take a look at these and resend?

**Comment by brunobasto** [comment]
@ctampoya Thanks for catching this one :)

/cc @vicnate5

**Pull request closed without merging**
