### PR TITLE
master-qa-80137

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-80137
https://issues.liferay.com/browse/LRQA-79981

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@catarineaguiar This https://github.com/vicnate5/liferay-portal/pull/2353/commits/aadadadda57d0b9212504e758a7357593304ccd0 looks to me like a workaround for a bug...why do we need to modify a empty site after creation to avoid this error?

**Comment by vicnate5** [comment]
Pushed to BChan, but excluded aadadadda57d0b9212504e758a7357593304ccd0
https://github.com/brianchandotcom/liferay-portal/pull/135692

**Comment by catarineaguiar** [comment]
> @catarineaguiar This [aadadad](https://github.com/vicnate5/liferay-portal/commit/aadadadda57d0b9212504e758a7357593304ccd0) looks to me like a workaround for a bug...why do we need to modify a empty site after creation to avoid this error? I do not think a real user would do this or know to do this...

Hi @vicnate5 , all Export/Import tests include this step since the welcome site has by default the 404 error utility page

**Comment by vicnate5** [comment]
@catarineaguiar 
Can you provide some additional context? Why is this not considered a bug for clients who are trying to import a site? Does the client know they need to delete this page? (if so, is this documented for them?)

**Comment by catarineaguiar** [comment]
@vicnate5 the issue was already reported in the past, but it seems the "failure" is the expected result for now. 
Please see https://issues.liferay.com/browse/LPS-178972#:~:text=the%20feature%20flag.-,Right,-now%20it%27s%20the

**Comment by vicnate5** [comment]
@catarineaguiar Cool, that ticket answers my questions. Thanks!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/136039

**Comment by vicnate5** [comment]
Resent with AWS test enable
https://github.com/brianchandotcom/liferay-portal/pull/136064

**Pull request closed without merging**
