### PR TITLE
LPS-166395 Uniform Automated test | ReportPersistThroughAdditionalUpgradeRuns

### PR DESCRIPTION
**Pull request by lucasperj**
Issue link: [LPS-166395](https://issues.liferay.com/browse/LPS-166395)
Original PR: https://github.com/vicnate5/liferay-portal/pull/2195

### CODE REVIEW

**Comment by lucasperj** [comment]
Hey @vicnate5, can you try to run the test locally again and ensure that there is no remaining reports generated in the reports folder so that it does not get conflicts? I ran here locally again and it keeps passing. This way to confirm there are 2 different upgrade reports should be enough, since when running the upgrade tool again, no upgrade would be triggered and in the new report we would have (No upgrade processes registered.) 
While the previously generated Report MUST have the same list of Upgrades seen previously (Top 20 longest running upgrade processes)

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:upgrade:nocompile

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:stop

**Comment by lucasperj** [comment]
ci:stop

**Comment by lucasperj** [comment]
Hey @vicnate5 , try to run the test locally again and ensure that there is no remaining reports generated in the reports folder so that it does not get conflicts, for me and Susan passed quietly in these conditions. And also, I don't know if it would be necessary to change the way of asserting (if that works), since we would be really trying to verify that the second report generated does not have any upgrades, and the report checked later must have the same list of processes that was checked in the first steps(cause it's the same).

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
The regex did not worked for me in this case, so I tried another approach , can you check again @vicnate5 ? Thanks!

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@lucasperj See my changes at https://github.com/brianchandotcom/liferay-portal/pull/127901/commits/0bd5fd98df275ee09a21e0f67b356303dd15fb25. I took a different approach to getting the file that we use in other Poshi macros.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/127901

**Pull request closed without merging**
