### PR TITLE
LRQA-42938

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance

**Comment by koor4356** [comment]
Backport this to 7.1.X, 7.2.X, and 7.3.X branches.

**Comment by koor4356** [comment]
ci:retest:acceptance

**Comment by koor4356** [comment]
I am retesting this because the test was passing locally. This could be a fluke.

**Comment by vicnate5** [comment]
@koor4356 I have a workaround for this failure on CI, will test with that.

**Comment by koor4356** [comment]
Cool, thanks @vicnate5

**Comment by vicnate5** [comment]
@koor4356 In the future, for the clustering tests, just use `ci test clustering` instead of needing make a custom run, it will also improve stablity.

**Comment by vicnate5** [comment]
See https://github.com/vicnate5/liferay-portal/pull/1718

**Pull request closed without merging**
