### PR TITLE
Run rename tomcat test

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-62584

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
@koor4356 I am glad you got this working. Do you need so many properties changed? `set-tomcat-version-number` is changed far fewer properties for a similar use case (maybe something else is doing propagates them?). It is also just changing the properties in the app server props file, once this is done, I expect ant will import the new properties, do you need all the new macros?

I am also confused why you are changing so many properties here (https://github.com/vicnate5/liferay-portal/pull/1601/commits/3b7c847a01b00b1d31e5a0357692c273ac36e538#diff-d98844b18ba5230332f5a613cad8b8a241692b6b510f8c4529773210cbc13f35R4860), but only some of them are passed down to the properties files and macro.

This looks a little messy, if we need all of these changes, can you explain why we need so many custom macros and variables to get this working? There are multiple properties and parameters that look unnecessary here. Right now, you can assume this tomcat rename will ONLY happen in this specific test, the macros might be unneeded or could be simpler (no need to account for a custom `app.server.bundle.index` for example). 

We could have a call to work through this tomorrow if you want.

**Comment by koor4356** [comment]
Let talk about this, Thanks

**Comment by koor4356** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
use `start-renamed-app-server` instead of `start-rename-app-server`, apply this pattern where it is used.

**Comment by vicnate5** [comment]
We also need to use `LIFERAY_CLEAN_OSGI_STATE` as stated in the LRQA ticket. Please resend.

**Pull request closed without merging**
