### PR TITLE
LPS-171011 - Can create virtual instance with clustering testcase

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LPS-171011

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:stop:clustering

**Comment by catarineaguiar** [comment]
force-pushed to assert if the virtual instance opens in the second node.

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
See https://github.com/vicnate5/liferay-portal/pull/2216

I fixed the test and am running it without the bug fix to confirm it fails for the bug.

**Pull request closed without merging**
