### PR TITLE
LRQA-25404 Implement Sybase data dump import & activate Sybase upgrade tests.

### PR DESCRIPTION
**Pull request by pyoo47**
Victor, you can use this pull to test the Sybase database upgrade tests. One caveat is that my computer has to be connected to the network here for it to work... Let me know if you have any questions.

I've submitted a pull to BChan for the import logic [here](https://github.com/brianchandotcom/liferay-portal/pull/40190). We can activate the upgrade tests whenever we are ready.

### CODE REVIEW

**Comment by vicnate5** [comment]
Thanks @pyoo47, This is very helpful. The first tests failed to find the zip from your computer. Was it not up yet or is there another issue?

The Bug fix for this was sent to BChan. I might need to grab and rebase this on the fix when it goes in.

**Comment by pyoo47** [comment]
I forgot to mention, the zip is only available for 6.2.3. The other two version will always fail.

Peter

**Comment by vicnate5** [comment]
@pyoo47 I tested this with a rebase and the 6.2.3 test still fails to read the database zip. See https://github.com/vicnate5/liferay-portal/pull/380.

The curl throws `Warning: Failed to create the file`

**Comment by pyoo47** [comment]
I think I've fixed the issue with the new commit I've added. I also resolved a merge conflict that arose when something got merged to upstream last night.

**Comment by vicnate5** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by pyoo47** [comment]
I've removed the commits needed to download from my laptop. The zips can now be downloaded from the liferay-qa-legacy-ee repo now as they were meant to be.

**Comment by pyoo47** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Pull request closed without merging**
