### PR TITLE
LPS-67025 Fix poshi

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 I replace quotes by double apostrophe for now. Quotes inside quotes was throwing exception during expression evaluation.

Please take a look as soon as you can, this one is for Bank of America project. You can send to BChan if it's ok to you.

Thanks !!!

**Comment by vicnate5** [comment]
Hey @leoadb 

Thanks for sending this to me. I found a regression on this pull.
If there is more than 1 conditional visibility expressions on a form, it does not render for the user.

#### Steps to Reproduce:
1. Add Select from List field 
`name: "Select"`
`options: 1, 2`
2. Add Text field with condition
`equals(Select,"1")`
3. Add Single Selection field
`name: "Radio"`
`options: 1, 2`
4. Add Text field with condition
`equals(Radio,"1")`
5. Save form
6. Add Form portlet to the Welcome page
7. Select Form
8. Save

Form does not render.

See https://gist.github.com/104f7ce88e1f33383aaf96fc3182a1a3

**Comment by vicnate5** [comment]
Can you take another look?

**Comment by leoadb** [comment]
@vicnate5 Thanks !!! I'll take a look and send back to you.

**Pull request closed without merging**
