### PR TITLE
master-qa-66873

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-66873

This is only for master!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:upstream-functional

**Comment by vicnate5** [comment]
https://github.com/john-co/liferay-portal/pull/428

**Pull request closed without merging**
