### PR TITLE
Friendly URL should only displayed locale once

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-53822

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by vicnate5** [comment]
@koor4356 This one will need to be manually rebased on other PRs (e.g. LRQA-53818)

**Comment by koor4356** [comment]
Okay, will do tomorrow.

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by vicnate5** [comment]
@koor4356 EditFriendlyURL removed?

**Comment by koor4356** [comment]
New https://github.com/vicnate5/liferay-portal/pull/1391

**Pull request closed without merging**
