### PR TITLE
master-qa-32284

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-32284

CC @diogo-lins I fixed a POSHI test that was affected by the condition dropdown being inactive.

### CODE REVIEW

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by vicnate5** [comment]
Tests are OK, the first result was an unrelated issue.

**Comment by diogo-lins** [comment]
Awesome!

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/48725

**Pull request closed without merging**
