### PR TITLE
[Sidecar]LPS-106592-LPS-103577 53 test

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@tinatian 

new error on rolling restart test https://testray.liferay.com/reports/production/logs/test-1-23/1582660973920/test-portal-acceptance-pullrequest(master)/5528/functional-tomcat90-mysql57-jdk8/1/0/jenkins-console.txt.gz

Cluster shutdown error
https://testray.liferay.com/reports/production/logs/test-1-23/1582660973920/test-portal-acceptance-pullrequest(master)/5528/functional-tomcat90-mysql57-jdk8/7/0/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
Manual Testing on process kill in Cluster PASSED
https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit?ts=5e2a3128#gid=1206555946&range=E31

**Comment by vicnate5** [comment]
@tinatian did not reproduce the node shutdown error locally. Master node shutdown with error.

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
https://github.com/tinatian/liferay-portal/pull/1725

**Pull request closed without merging**
