### PR TITLE
LPS-132370 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-132370

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
cc: @john-co

**Comment by kyle-miho** [comment]
Tested here: https://github.com/kyle-miho/liferay-portal/pull/442
running an extra acceptance test since this is a "mass change", although it is an improvement/fix for tests with test.skip.portal.instance, and especially tests with skip.start.app.server

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/102143

**Pull request closed without merging**
