### PR TITLE
LRQA-44342 Check warning error

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-44342

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 Sending this back. I don't want the test to check a specific error. I want the test to fail on any warning, because we could have a different problem in the future.

**Comment by koor4356** [comment]
ci:open

**Comment by koor4356** [comment]
ci:reopen

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64843
https://github.com/brianchandotcom/liferay-portal-ee/pull/22294

**Pull request closed without merging**
