### PR TITLE
master-qa-29095

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-29095

### CODE REVIEW

**Comment by ctampoya** [comment]
@vicnate5 

- There are some tests still failing. 
- Additional test fixes will be made in https://issues.liferay.com/browse/LRQA-29115 and https://issues.liferay.com/browse/LRQA-29151.
- Bugs present: https://issues.liferay.com/browse/LPS-69282 and https://issues.liferay.com/browse/LPS-67598

**Comment by vicnate5** [comment]
@ctampoya so is it just 2 tests that are still failing?

**Comment by ctampoya** [comment]
No, there are a handful of tests that are failing from the bugs as well.

**Comment by vicnate5** [comment]
Beyond https://issues.liferay.com/browse/LRQA-29104?

I want to make sure we don't have more tests to turn off.

**Comment by ctampoya** [comment]
KaleoformsUsecase#ProcessUsesEditForm and KaleoformsUsecase#CompleteProcessAndAssertFieldOrder fail from https://issues.liferay.com/browse/LPS-67598

**Comment by vicnate5** [comment]
Can you make a LRQA task ticket to turn those off as well?

**Comment by ctampoya** [comment]
Done - https://issues.liferay.com/browse/LRQA-29160

**Comment by vicnate5** [comment]
Awesome. thanks!

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44852

**Pull request closed without merging**
