### PR TITLE
LRQA-81259 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://liferay.atlassian.net/browse/LRQA-81259

Tested here: https://github.com/Kvale1733/liferay-portal/pull/378.
There were no failures:https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2373549392

I know you stated otherwise but I discovered we don't actually copy any jars for Tomcat in this test. Somehow the test was still passing all this time though.

I made some changes to the configs we use for jndi to reflect what's in the documentation here: https://learn.liferay.com/w/dxp/installation-and-upgrades/installing-liferay/installing-liferay-on-an-application-server/setting-up-jndi-on-tomcat. As Mariano noted was needed in the LPS.

I'm not sure if there is a specific reason the test doesn't use the configuration used in that documentation.

With hikari as the factory, it does require to place the the db driver in the lib directory, along with 2 other jars. But still, I it doesn't look like there is any warning at shutdown.

It looks like this test passes on the additional db's even with the changes.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
I want to see how this pans out before we merge
https://liferay.atlassian.net/browse/LPS-188019?focusedCommentId=2160266

**Comment by vicnate5** [comment]
Confirmed this does not break the read/write tests
https://github.com/vicnate5/liferay-portal/pull/2393

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/137768

**Pull request closed without merging**
