### PR TITLE
LRQA-37160 Fix reference to DDM Form Instance

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by rodrigo-e-c-souza** [comment]
Thanks @pedroqueiroz94 !

**Comment by pedroqueiroz94** [comment]
No problem, @rodrigo-e-c-souza ;)

**Comment by vicnate5** [comment]
Thanks so much @pedroqueiroz94 

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54378

**Comment by pedroqueiroz94** [comment]
You're welcome, @vicnate5 !! :D

**Pull request closed without merging**
