### PR TITLE
LPS-69586 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
@ctampoya Can you do a quick check on this pull and then push to BChan?

**Comment by ctampoya** [comment]
Pushed to BChan https://github.com/brianchandotcom/liferay-portal/pull/45559

**Comment by ctampoya** [comment]
@brunobasto Since Victor is out for the rest of the week, can you close this pull. Thanks!

**Comment by brunobasto** [comment]
Sure. Thanks, @ctampoya

**Pull request closed without merging**
