### PR TITLE
LRQA-59742 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-59742

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test
testing all for safety

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
PortalconfigurationUsecase#DeletePortalInstance
and
PortalconfigurationUsecase#AddPortalInstance

cover the removal of manually using the UI for Virtual Instances

**Comment by kyle-miho** [comment]
ci:test
build was aborted

**Comment by vicnate5** [comment]
@kyle-miho if you need to iterate on this more, restrict to functional tests only

**Comment by kyle-miho** [comment]
ci:test:poshi

**Comment by vicnate5** [comment]
@kyle-miho let me know when this is actually ready.

**Pull request closed without merging**
