### PR TITLE
LRQA-51999 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-51999

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
tested here: https://github.com/kyle-miho/liferay-portal/pull/247

**Comment by vicnate5** [comment]
Testing 7.1.x backport before merge: https://github.com/vicnate5/liferay-portal-ee/pull/332

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/80037
https://github.com/brianchandotcom/liferay-portal-ee/pull/27263
https://github.com/brianchandotcom/liferay-portal-ee/pull/27262

**Pull request closed without merging**
