### PR TITLE
LPS-171004 Investigate false positives for DatabaseUpgradeClient tests

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-171004

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@susanchen3 The function `WaitForConsoleTextPresent` can only see the Liferay Portal log, it will not read the upgrade log file. You will need something that checks the upgrade.log specifically.

**Comment by susanchen3** [comment]
Yeah I wanted to wait for specific messages in the Liferay Portal log to show up before `check-failed-upgrade-log` could run (this checks the upgrade log).

**Pull request closed without merging**
