### PR TITLE
LPS-94615

### PR DESCRIPTION
**Pull request by tinatian**
Hi @vicnate5 ,
Could you please help verify the fix of this issue? It needs windows env.

Thanks.
Tina

### CODE REVIEW

**Comment by vicnate5** [comment]
@anthony-chu

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by anthony-chu** [comment]
@tinatian @dantewang I tested this branch and the bundle, and no `initializationError`s or `InvalidPathExceptions` were thrown when running module integration tests.

**Comment by tinatian** [comment]
Thanks @anthony-chu!

**Pull request closed without merging**
