### PR TITLE
master-qa-55958

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-55958

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Tina's branch now has many conflicts that will fail rebase, so I did not rebase on it. But I run ci:test:norebase in pr https://github.com/zhangyan0701/liferay-portal/pull/148, and the tests pass on CI.

**Comment by zhangyan0701** [comment]
The error that I got before, I couldn't reproduce on local. So I added a property that can skip the third node.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Pushed to BChan. See my changes.
https://github.com/brianchandotcom/liferay-portal/pull/88563

**Pull request closed without merging**
