### PR TITLE
LRQA-72198

### PR DESCRIPTION
**Pull request by koor4356**
- LPS-72198 Use different macro to assert portlet is not present, previous macro use assert console present instead of not present
- LPS-72198 Do not commit

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by vicnate5** [comment]
@koor4356 Is there anything in the console we can assert to confirm the module is disabled?

**Comment by koor4356** [comment]
@vicnate5, we are asserting this in the console. 

`AssertConsoleTextNotPresent(value1 = "Reinstalling bundle com.liferay.gogo.shell.web");`

**Comment by vicnate5** [comment]
@koor4356 Is there anything that is printed in the console that says the module is stopped after restart?

**Comment by koor4356** [comment]
@vicnate5,
I looked through the log after restarting and found this line. "Stopping blacklisted bundle com.liferay.gogo.shell.web".

**Comment by vicnate5** [comment]
Please resend with that line as the check.

**Comment by koor4356** [comment]
got it, thanks!

**Pull request closed without merging**
