### PR TITLE
LRQA-72463 Unzip files

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upstream-functional

**Comment by vicnate5** [comment]
Running functional tests to make sure we didn't break anything expanding the archives.

@Hijky If the results come in, please check for regressions, otherwise I will scan tomorrow.

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
SF failures is not related to this pull.
I applied XML SF checks to `*.svg` last week, and this pull removed [these lines](https://github.com/vicnate5/liferay-portal/pull/1943/commits/9a787a790c8053f84867d8e2bd184309aa56ea25#diff-967a46bafa2036c78c2d3c5c2ad04e624b891d7821d882f38564650ca3131f98L17-L18), that means SF will check all files in `dependencies` directories.

**Comment by ling-alan-huang** [comment]
If functional tests don't break anything, we can use the latest SF to format this pull again.

**Comment by vicnate5** [comment]
@Hijky Lots of failures I think I caused by this PR:
https://testray.liferay.com/home/-/testray/case_results/1601356961
https://testray.liferay.com/home/-/testray/case_results/1601352449
https://testray.liferay.com/home/-/testray/case_results/1601356825
https://testray.liferay.com/home/-/testray/case_results/1601348528
https://testray.liferay.com/home/-/testray/case_results/1601353230
https://testray.liferay.com/home/-/testray/case_results/1601353232
https://testray.liferay.com/home/-/testray/case_results/1601354273
https://testray.liferay.com/home/-/testray/case_results/1601354181
https://testray.liferay.com/home/-/testray/case_results/1601357092
https://testray.liferay.com/home/-/testray/case_results/1601349510
https://testray.liferay.com/home/-/testray/case_results/1601349532
https://testray.liferay.com/home/-/testray/case_results/1601356548
https://testray.liferay.com/home/-/testray/case_results/1601348946
https://testray.liferay.com/home/-/testray/case_results/1601348943

Can you take a look?

**Comment by Hijky** [comment]
> @Hijky Lots of failures I think I caused by this PR: https://testray.liferay.com/home/-/testray/case_results/1601356961 https://testray.liferay.com/home/-/testray/case_results/1601352449 https://testray.liferay.com/home/-/testray/case_results/1601356825 https://testray.liferay.com/home/-/testray/case_results/1601348528 https://testray.liferay.com/home/-/testray/case_results/1601353230 https://testray.liferay.com/home/-/testray/case_results/1601353232 https://testray.liferay.com/home/-/testray/case_results/1601354273 https://testray.liferay.com/home/-/testray/case_results/1601354181 https://testray.liferay.com/home/-/testray/case_results/1601357092 https://testray.liferay.com/home/-/testray/case_results/1601349510 https://testray.liferay.com/home/-/testray/case_results/1601349532 https://testray.liferay.com/home/-/testray/case_results/1601356548 https://testray.liferay.com/home/-/testray/case_results/1601348946 https://testray.liferay.com/home/-/testray/case_results/1601348943
> 
> Can you take a look?

I will check these today

**Comment by Hijky** [comment]
I run these in my local:

For these cases, the problem with these cases is Stuck while importing the file, no failure message
https://testray.liferay.com/home/-/testray/case_results/1601356961
https://testray.liferay.com/home/-/testray/case_results/1601352449
https://testray.liferay.com/home/-/testray/case_results/1601356825
https://testray.liferay.com/home/-/testray/case_results/1601356548 https://testray.liferay.com/home/-/testray/case_results/1601348946 https://testray.liferay.com/home/-/testray/case_results/1601348943
https://testray.liferay.com/home/-/testray/case_results/1601349510 https://testray.liferay.com/home/-/testray/case_results/1601349532
https://testray.liferay.com/home/-/testray/case_results/1601354273 https://testray.liferay.com/home/-/testray/case_results/1601354181

For this case is the loaded file is in the wrong format and cannot be imported
https://testray.liferay.com/home/-/testray/case_results/1601348528

For these cases is the required file cannot be imported normally
https://testray.liferay.com/home/-/testray/case_results/1601353230 https://testray.liferay.com/home/-/testray/case_results/1601353232

**Comment by vicnate5** [comment]
@Hijky Are you able to confirm the specific change that causes the failure? I would just focus on trying to get 1 of the failing tests to work.

**Comment by Hijky** [comment]
> @Hijky Are you able to confirm the specific change that causes the failure? I would just focus on trying to get 1 of the failing tests to work.

I think the specific reason is that there is a difference between the modification and modification rules of Unzip files, not hitting full compatibility

**Pull request closed without merging**
