### PR TITLE
Check upgrade clinet zip file content

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-50279

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@koor4356 please don't run the full upgrade suite unless we need to. it is very resource heavy.

In a case like this, add a temp commit to only run the db upgrade client batch.

**Comment by vicnate5** [comment]
@koor4356 This looks good. I would just like to see some wording changes.

`db.upgrade.client.zip.dir` change to `db.upgrade.client.dist.dir`

Instead of "failed to appear" and "appeared successfully"
Use "is not present" and "is present"

**Pull request closed without merging**
