### PR TITLE
LRQA-79471

### PR DESCRIPTION
**Pull request by catarineaguiar**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Are you able to run this locally? This creates a summary of what relevant will do, it should help you debug what is wrong here.

`ant -f build-test.xml record-job-summary -Djob.name='test-portal-acceptance-pullrequest(master)' -Dtest.suite.name=relevant`

See workaround for known issue: https://liferay.slack.com/archives/CL3TWSMHQ/p1671564559761469

**Comment by catarineaguiar** [comment]
ci:close

**Pull request closed without merging**
