### PR TITLE
LPS-78332 Add Filtering and sorting to the new management bar in monitoring tab

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by vicnate5** [comment]
Hey @jeyvison since this doesn't compile, I cannot reliably update the tests. I think I will need the test results to know what to fix. I can set this as top priority tomorrow when we can get results.

**Comment by jeyvison** [comment]
Hi @vicnate5 , i believe it's because of the merge after the moving of workflow. I'll try to fixit and oush force this PR

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
These results are very helpful for fixing the tests

**Comment by jeyvison** [comment]
ci:close

**Pull request closed without merging**
