### PR TITLE
Run oracle DB version 19c

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-62941

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance-dxp:nocompile

**Comment by koor4356** [comment]
ci:test:nocompile

**Comment by koor4356** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 Please send final version of this PR now that we know the batches are working. Replace all our Oracle 12c testing with Oracle 19c.

**Comment by koor4356** [comment]
ci:retest:nocompile

**Pull request closed without merging**
