### PR TITLE
LPS-108993 Move the basic document creation to the proper place to allow upgrade on startup

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test

**Comment by jpince** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@achaparro I think fixing upgrades to work on startup is going to be more work.

6.2.10.21 https://testray.liferay.com/reports/production/logs/test-1-12/1582253780131/test-portal-acceptance-pullrequest(master)/2391/functional-upgrade-tomcat90-mysql57-jdk8/3/0/liferay-log.txt.gz

7.0.10.6 https://testray.liferay.com/reports/production/logs/test-1-12/1582253780131/test-portal-acceptance-pullrequest(master)/2391/functional-upgrade-tomcat90-mysql57-jdk8/6/0/liferay-log.txt.gz

7.2.10 https://testray.liferay.com/reports/production/logs/test-1-12/1582253780131/test-portal-acceptance-pullrequest(master)/2391/functional-upgrade-tomcat90-mysql57-jdk8/8/0/liferay-log.txt.gz

For some reason 7.1 is OK
https://testray.liferay.com/reports/production/logs/test-1-12/1582253780131/test-portal-acceptance-pullrequest(master)/2391/functional-upgrade-tomcat90-mysql57-jdk8/4/0/liferay-log.txt.gz

**Comment by achaparro** [comment]
Hi @vicnate5,

This is why we wanted to keep the upgrade tool as the preferred option :-( The goal of the property change was to set the property to false and then not upgrade modules on startup. However now we want to use that property to allow any kind of upgrades. I also had a check to avoid the use of this property when the release number is different, so only between GAs but Brian didn't want it.

We can talk today about it.

**Comment by vicnate5** [comment]
@jpince We are going to put a hold on fixing this for now and Alberto is going to discuss with Brian tomorrow. The Core product team is currently recommending that we only allow auto upgrades between 7.3 versions.

**Comment by vicnate5** [comment]
We have a root level fix for auto upgrades, but it looks like we still need at least this fix for older versions.

Testing again here: https://github.com/vicnate5/liferay-portal/pull/1440

**Pull request closed without merging**
