### PR TITLE
master-qa-42923

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-42923
https://issues.liferay.com/browse/LRQA-42924

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Tested new testcases in [zhangyan0701#169](https://github.com/zhangyan0701/liferay-portal/pull/169).

**Comment by vicnate5** [comment]
@zhangyan0701 Thanks for getting this done quickly.

When I look at these tests, I think they can be combined into 1 test and then you can avoid hardcoding the version. You just need to make some updates to `UpgradeCoreFromLatestFailingPoint`

When running the first groovy script, store the value of the current version as a variable, then lower the version and execute the upgrade. After executing the upgrade to the latest version, check the final version based on the original version that was stored.

```
AssertTextEquals.assertPartialText(
	locator1 = "ServerAdministrationScript#OUTPUT_FIELD",
	value1 = "Schema Version is ${originalSchemaVersion}");
```

After this update is made, remove `UpgradeCoreSchemaVersion`, both scenarios will be covered by the first test

**Pull request closed without merging**
