### PR TITLE
[Company Logging] LRQA-75854 Add macro to assert company log content

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:acceptance

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:acceptance

**Comment by vicnate5** [comment]
ci:test:acceptance

**Comment by vicnate5** [comment]
Will send this once https://github.com/brianchandotcom/liferay-portal/pull/121410 is merged.

**Comment by Kvale1733** [comment]
@vicnate5 So it seems like these tests will fill now due to an issue affecting tests with database partitioning enabled: [LPS-160370](https://issues.liferay.com/browse/LPS-160370)

**Comment by vicnate5** [comment]
Waiting for additional changes https://github.com/brianchandotcom/liferay-portal/pull/122664#issuecomment-1240969375

**Comment by vicnate5** [comment]
@Kvale1733 Due to the changes in the development of this story, can you resend with the following changes?

1. Remove the dev commits, only include the tests
2. Ignore all tests for the UI part of this feature
3. Ignore tests that are not passing on master

Give me something I can merge to master now, we can revisit and update these tests the development is actually completed.

**Pull request closed without merging**
