### PR TITLE
LPS-166395 Uniform Automated test | ReportPersistThroughAdditionalUpgradeRuns

### PR DESCRIPTION
**Pull request by lucasperj**
Issue: https://issues.liferay.com/browse/LPS-166395

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:upgrade:nocompile

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:upgrade:nocompile

**Comment by vicnate5** [comment]
@lucasperj I am getting this when I run this test locally:
```
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.UpgradeReport#ReportPersistThroughAdditionalUpgradeRuns] STANDARD_ERROR
     [exec]     java.lang.Exception: Original upgrade report does not contains expected upgrades.
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/UpgradeReport.testcase[ReportPersistThroughAdditionalUpgradeRuns]:241
```

We probably need a more specific way to confirm there are 2 different upgrade reports. Can we hardcode the names of both of them?

**Comment by lucasperj** [comment]
ci:reopen

**Pull request closed without merging**
