### PR TITLE
master-qa-65406

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-65406

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Tested and analyzed in https://github.com/zhangyan0701/liferay-portal/pull/261.

Failures are unrelated.

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@zhangyan0701 I created an LPS for this issue and changed the commit to the LPS.

I updated the SOP doc for this additional procedure

https://github.com/vicnate5/liferay-portal/pull/1682

**Pull request closed without merging**
