### PR TITLE
LPS-134152 TEMP for CI

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@koor4356 Please investigate

**Comment by koor4356** [comment]
@vicnate5, Since you move the test out to its own, you should have added: "Reindex all search indexes."

**Comment by koor4356** [comment]
Ci:close

**Comment by koor4356** [comment]
See new PR: https://github.com/vicnate5/liferay-portal/pull/1802

**Comment by koor4356** [comment]
Also, I am not able to close this PR, thanks!

**Pull request closed without merging**
