### PR TITLE
Add new Gogo shell Test

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-53800

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by vicnate5** [comment]
ci:test:acceptance:nocompile

**Comment by vicnate5** [comment]
Going to hold this until 7.1.x has been synced so I can make sure the rename gets in to all branches.

I modified this for a safer rename by deleting the file and then re-adding.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/81845
https://github.com/brianchandotcom/liferay-portal-ee/pull/27999
https://github.com/brianchandotcom/liferay-portal-ee/pull/27998

**Pull request closed without merging**
