### PR TITLE
LPS-61568 Dot not add an unecessary dependency to initialize Form Builder

### PR DESCRIPTION
**Pull request by marcellustavares**
@vicnate5, We've added a "Confirm" button at the publish dialog. Form is just available after this action.

Could you double check?

Thanks a lot!

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares @fernandosouza @brunobasto This needs a minor test update, which I will add.

But 2 questions on this pull:
1. Should there be a success message after clicking "Confirm" to publish the Form? There is not one currently.
2. The Copy URL button doesn't work on all browsers. I was able to use it on Chrome, but not on Firefox or Safari. Is this a known limitation?

**Comment by vicnate5** [comment]
cc @ctampoya

**Comment by brunobasto** [comment]
Hey @vicnate5,

1. The's no success message. What'll do in a future PR is move the persistence code to the save button of the form, but the behavior should be the same as far the tests are concerned. Once we do move this code, there should be nothing to update on the tests side.

2. This is a known issue. Modern browsers have implemented the clipboard API, but not all. For those on unsupported browsers, they'll just have to manually copy it. I think firefox supports it, but only newer versions.

Thanks,

**Comment by vicnate5** [comment]
@brunobasto Thanks Bruno. I can forward this on to Brian.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/36836

**Pull request closed without merging**
