### PR TITLE
LRQA-53834 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-53834

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@kyle-miho Is the testcase <setup> osgi deployment step still needed since we have the following
```
property osgi.module.configuration.file.names = "com.liferay.portal.bundle.blacklist.internal.BundleBlacklistConfiguration.config";
	property osgi.module.configurations = "blacklistBundleSymbolicNames=";
```

**Comment by kyle-miho** [comment]
@vicnate5 youre right it shouldnt be needed, i ended up adding it to the top to over-ride some forced bundle blacklist configuration. Ill fix it up (remove the setup teardown) and retest

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Pull request closed without merging**
