### PR TITLE
master-qa-135481

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LPS-135481

This is only for master!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Running tests in https://github.com/zhangyan0701/liferay-portal/pull/297.

No regression found.

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
