### PR TITLE
LPS-85888 Uses lower case

### PR DESCRIPTION
**Pull request by ealonso**
Hey @vicnate5 @john-co,

Could you please take a look to this fix since you revert it before? If you find any problem with https://issues.liferay.com/browse/LPS-95409, please let me know, It is a little bit strange that this commit causes this regression because I've only changed the capitalization of the letters.

I've tested it locally with the changes and I cannot reproduce https://issues.liferay.com/browse/LPS-95409.

cc: @kyle-miho, @brianchiu

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @ealonso, Using the test bundle from the pull, I'm still able to locally reproduce https://issues.liferay.com/browse/LPS-95409

cc/ @vicnate5, @brianchiu, @kyle-miho

**Comment by john-co** [comment]
Hi @ealonso, I attached a mp4 showing full steps to reproduce here: https://issues.liferay.com/browse/LPS-95409?focusedCommentId=1831327&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1831327

**Comment by john-co** [comment]
Hi @ealonso,

We took a further look into the issue and we're able to reproduce the issue at master head even after reverting the commit. I'll push these changes up to BChan.

The test results gave us a false positive after reverting, sorry for mistakenly reverting the commit.

What's still strange is that you're not able to reproduce the issue...

**Comment by john-co** [comment]
pushed to https://github.com/vicnate5/liferay-portal/pull/1193

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
