### PR TITLE
LPS-122557 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Victor,
I have updated the log message as suggested by PMs.

Could you please trigger the test and verify the logic manually if needed?

Thanks
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:license

**Comment by vicnate5** [comment]
https://github.com/vicnate5/liferay-portal/pull/1712

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
ci:test:license

**Comment by vicnate5** [comment]
@tinatian I want to use the branch with the test changes, so move this to a fresh PR here https://github.com/vicnate5/liferay-portal/pull/1721

**Pull request closed without merging**
