### PR TITLE
LPS-68474 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by ctampoya** [comment]
@brunobasto The sidebar does not collapse when I click on the "Rules" tab. When I revert the SF commit, it works as expected. Can you take another look please =) 

cc @fernandosouza  @vicnate5

**Comment by brunobasto** [comment]
Hey Clarissa, sure. I'll take a look. Thanks

**Comment by ctampoya** [comment]
Seems to be only happening on FF45. When tested on Chrome, Safari and Edge, everything works as expected.

**Comment by fernandosouza** [comment]
@brunobasto. I can make that.

**Comment by fernandosouza** [comment]
@ctampoya, @brunobasto, @vicnate5.

https://github.com/vicnate5/liferay-portal/pull/601

**Pull request closed without merging**
