### PR TITLE
LPS-168738 Convert remaining database upgrade client batches into Poshi tests

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-168738 :pray:

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@susanchen3 Can you fix the code conflicts here?

**Comment by susanchen3** [comment]
@vicnate5 rebased!

**Comment by vicnate5** [comment]
Nice job on this. I like the solution to the upgrade startup wait. Just one minor naming change from me.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/127498

**Pull request closed without merging**
