### PR TITLE
LPS-171015 Uniform Automated tests | Add  CompareUpgradedAndFreshDatabaseSchemas testcase for all versions

### PR DESCRIPTION
**Pull request by lucasperj**
Issue link : https://issues.liferay.com/browse/LPS-171015

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Please add `property ci.retries.disabled = "true";` to this testcase

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/129028

**Pull request closed without merging**
