### PR TITLE
master-qa-59212

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-59212

This is for fixing the missing database driver error on Wildfly envrionments:
```
[beanshell] [0m[31m09:15:23,698 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
[beanshell]     ("subsystem" => "datasources"),
[beanshell]     ("data-source" => "LiferayPool")
[beanshell] ]) - failure description: {
[beanshell]     "WFLYCTL0412: Required services that are not installed:" => ["jboss.jdbc-driver.mysql"],
[beanshell]     "WFLYCTL0180: Services with missing/unavailable dependencies" => [
[beanshell]         "jboss.driver-demander.java:/jdbc/LiferayPool is missing [jboss.jdbc-driver.mysql]",
[beanshell]         "org.wildfly.data-source.LiferayPool is missing [jboss.jdbc-driver.mysql]"
[beanshell]     ]
[beanshell] }
```

Tested in https://github.com/zhangyan0701/liferay-portal/pull/395.
Testray results:
MariaDB: https://testray.liferay.com/home/-/testray/case_results/1956567339
MySQL: https://testray.liferay.com/home/-/testray/case_results/1957585128

The communication link failure error didn't occur. But it still happens on Weblogic and Websphere, I need more time to investigate.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/122267

**Pull request closed without merging**
