### PR TITLE
LPS-XXXXX Fix clay imports in marketplace themes

### PR DESCRIPTION
**Pull request by Robert-Frampton**
Hey @vicnate5 

I've rebased this branch and included the latest changes to Clay. Bootstrap 4 Beta has been released since the last time we ran the tests against this branch, so there is a good probability that we will see new test failures due to changes they've made.

### CODE REVIEW

**Comment by vicnate5** [comment]
CC @alee8888 @jpince

**Comment by vicnate5** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

If the node8/npm5 fixes for `wiki-web` get merged before I get into the office tomorrow, can you rerun the tests on this PR?

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @vicnate5, @Robert-Frampton, how is this looking? 🤞

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

According to @vicnate5 we still have 7 test failures, he is analyzing the results so we can track down what the issues are. We're running the tests again based on the most recent release (from Friday), so there might be more.

Once we have the details of what broke we can fix the issues in the compat layer.

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by vicnate5** [comment]
@Robert-Frampton On the latest run, the "Add" button is back on the left side

https://testray.liferay.com/reports/production/logs/test-1-20/1504631934275/test-portal-acceptance-pullrequest(master)/3646/functional-smoke-jboss70-mysql56-jdk8/1/0/PortalSmoke_Smoke/screenshots/before0.jpg.gz

**Comment by vicnate5** [comment]
https://github.com/vicnate5/liferay-portal/pull/840

**Pull request closed without merging**
