### PR TITLE
LRQA-73874 | master

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LRQA-73874

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by vicnate5** [comment]
@catarineaguiar So the s3 directory does have a file cache (before and after the reindex)?
```
Temp Folder before Reindex: [42201.png1659567171000, 2031659567776000, 2011659567275000, 2021659567763000]
```
 I am not clear on the expected results of https://issues.liferay.com/browse/LPS-122233. I read it as the folder should be empty.
 However, this ticket makes me expect the cache to be there: https://issues.liferay.com/browse/LPS-158613
 
I do have one question, when you sent this test to me previously, the folder was empty:
https://testray.liferay.com/home/-/testray/case_results/1916921105. Do you know why?

**Comment by vicnate5** [comment]
@catarineaguiar `AssertConsoleTextNotPresent` is not working here and so the test could still give a false positive.

I went ahead and made some changes and tried to give the reasoning. See commits on https://github.com/brianchandotcom/liferay-portal/pull/121254. Let me know if you have questions on any of these changes.

**Comment by catarineaguiar** [comment]
Hi @vicnate5, thanks for checking and making changes. Thats the objective of the test, to verify if the cache remains the same after the reindex.

**Pull request closed without merging**
