### PR TITLE
LPS-66844 SF

### PR DESCRIPTION
**Pull request by brandizzi**
Hey Victor! This is a story @leoadb is working on. It should break some POSHI tests.

Select options used to have values such as "1", "2" etc. Now these values have a signature appended, so they look like "1#av/2eCxV4==", "2#VV2abJXx/a==" and so on. We suspect some POSH tests rely on the value of the option, so they will not be able to find it now.

Also, in this PR, there is a fix for the front end. So there are two tickets here, LPS-66844 and LPS-70189. This latter one is a sub-task from the former, so it should not cause any problems.

That is it! Any questions, you can talk to Leo.

Thanks!

### CODE REVIEW

**Comment by vicnate5** [comment]
@brandizzi @leoadb There are backend test failures here too. Do you know what those are?

**Comment by brandizzi** [comment]
I'll be out of office so I guess @leoadb will have to take care of it, or maybe @rafaprax.

**Comment by leoadb** [comment]
@vicnate5 Please send to @rafaprax Thanks !!!

**Comment by vicnate5** [comment]
ci:reopen Going to fix the poshi tests and then forward on.

**Comment by vicnate5** [comment]
Pushed to @rafaprax
https://github.com/rafaprax/liferay-portal/pull/157

**Pull request closed without merging**
