### PR TITLE
LPS-109105 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Auto upgrades for each version of Liferay

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1046986585&testrayRunId=1046986587

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@achaparro Getting closer.

still issues on

6.2.10
https://testray.liferay.com/reports/production/logs/test-1-15/1583878460078/test-portal-acceptance-pullrequest(master)/2472/functional-upgrade-tomcat90-mysql57-jdk8-1/1/0/jenkins-console.txt.gz

7.2.10
https://testray.liferay.com/reports/production/logs/test-1-15/1583878460078/test-portal-acceptance-pullrequest(master)/2472/functional-upgrade-tomcat90-mysql57-jdk8-2/4/0/jenkins-console.txt.gz

Others passed. 

It also looks like we still have some some random indexing issues on all versions. We might need to ask the Search team.

**Comment by achaparro** [comment]
Hey @vicnate5,

Sorry, I had a really busy day, I will check this tomorrow.

Cheers!

**Comment by achaparro** [comment]
see https://github.com/achaparro/liferay-portal/pull/499

**Pull request closed without merging**
