### PR TITLE
LRQA-64650 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-64650

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Tested locally, theres a bug with the commerce binary not printing out all of the expected console logging for poshi to continue so it errors out, i temporarily ignored that test for now, looking into it tomorrow

**Comment by vicnate5** [comment]
ci:test:license

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by vicnate5** [comment]
@kyle-miho I am probably gonna merge this as is, send me a follow up when you have more changes

**Comment by vicnate5** [comment]
https://github.com/vicnate5/liferay-portal/pull/1686

**Pull request closed without merging**
