### PR TITLE
master-qa-27261

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-27261

@vicnate5 please backport this to ee-7.0.x.  Thanks!

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:stop

**Comment by brianwulbern** [comment]
ci:retest

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42551
https://github.com/brianchandotcom/liferay-portal/pull/42552

**Comment by vicnate5** [comment]
@brianwulbern BChan should sync this to ee-7.0.x from 7.0.x

**Pull request closed without merging**
