### PR TITLE
LRQA-82692 Upgrade Tomcat to 9.0.80 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
This upgrade Tomcat to 9.0.80 on Master for

https://liferay.atlassian.net/browse/LPS-195495

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:foward:force

**Comment by vicnate5** [comment]
ci:forward:force

**Comment by Kvale1733** [comment]
ci:foward:force

**Comment by Kvale1733** [comment]
ci:forward:force

**Pull request closed without merging**
