### PR TITLE
LPS-64230 Add functional test to verify DDL Form Record search

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 Could you please take a look into the functional test @inacionery created ?
If it's ok for you, please forward this on to Brian, I already reviewed.

cc @marcellustavares

**Comment by marcellustavares** [comment]
hey @vicnate5, could you please fwd to me after your review?

Thanks

**Comment by vicnate5** [comment]
Pushed to Marcellus
https://github.com/marcellustavares/liferay-portal/pull/1439

**Comment by marcellustavares** [comment]
thx @vicnate5!

**Pull request closed without merging**
