### PR TITLE
LRQA-76371 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-76371

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Testing here: https://github.com/Kvale1733/liferay-portal/pull/171

**Comment by Kvale1733** [comment]
Only two paths were fixed. Also an old teardown macro for pages was uses that no longer exists so I replaced it. I simplified the teardown for both testcases as they used two different Bookmark teardown macros that do exactly the same thing.

Other than that I just used the openBookmarksAdmin to speed up navigation and replaced the setup for PGBookmarks with JSON to speed things up.

**Comment by vicnate5** [comment]
@Kvale1733 Nice job, thanks for getting this done so quickly.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/121297

**Pull request closed without merging**
