### PR TITLE
Delete UpgradeEnhancement#UpgradeCoreSchemaVersion

### PR DESCRIPTION
**Pull request by lucasperj**
[LPS-168110](https://issues.liferay.com/browse/LPS-168110)

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@lucasperj Can you update the commit message to explain why we are deleting it?

**Comment by lucasperj** [comment]
Done :heavy_check_mark:

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/126035

**Pull request closed without merging**
