### PR TITLE
master-qa-64666

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-64666

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Upgrade test from 7310 will fail because bugs:
https://issues.liferay.com/browse/COMMERCE-5588
https://issues.liferay.com/browse/LPS-127275
https://issues.liferay.com/browse/LPS-127285

So quarantine test  ViewPortalSmokeArchive7310 for now until the bugs get resolved.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 I would prefer to just ignore the warnings for now so this test can be used to verify the basic functionality.

See https://github.com/vicnate5/liferay-portal/pull/1629

**Pull request closed without merging**
