### PR TITLE
LPS-85888, LPS-95409 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-85888
https://issues.liferay.com/browse/LPS-95409

### CODE REVIEW

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73324

**Comment by brianwulbern** [comment]
@john-co @vicnate5 would we want this check added into 7.1 and/or 7.0, as well - or does it not apply there?

**Comment by john-co** [comment]
HI @brianwulbern, I think having LPS-95409 RTL padding and css macro test commits backported to 7.1 and 7.0 would be a good idea. We may have to update the style classes to what's in 7.1/7.0 if they changed. Would you be able to take care of this?

**Comment by brianwulbern** [comment]
Hi @john-co, I can take a look.  If I have questions about how to find anything, I'll ask you.

My first question, though, is about these LPS tickets: [LPS-85888](https://issues.liferay.com/browse/LPS-85888) looks like it only applies on master, 7.2 and 7.1; and [LPS-95409](https://issues.liferay.com/browse/LPS-95409) is only for master and 7.2.  *Would padding be enforced on 7.1 and 7.0 down to the (px) pixel value?*

I've created [LRQA-49225](https://issues.liferay.com/browse/LRQA-49225) to monitor this task.

**Comment by john-co** [comment]
Hi @brianwulbern, thanks!

I wouldn't worry about LPS-85888. My test fix in theory will be backported together with the code change since it's committed with the same LPS-85888.

For LPS-95409...In hindsight I could have made a NAT/TestFix ticket to make it easier to track/backport. We just want the poshi test changes.

The pixel value check is more so to check that padding-right is > 0px in RTL. I assigned it to match the product-menu sidenav-menu width since it would make sense to shift over that many pixels when product menu is opened. I think that this would be a valid check for 7.1 and 7.0.

**Comment by brianwulbern** [comment]
@john-co great, that makes sense.   Thanks for explaining :)

**Pull request closed without merging**
