### PR TITLE
LRQA-66288 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-66288

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/101535

**Pull request closed without merging**
