### PR TITLE
LRQA-53834 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-53834

### CODE REVIEW

**Comment by vicnate5** [comment]
@kyle-miho Looking at this again. Do we even need to make the module config blank?

**Comment by kyle-miho** [comment]
Yes, otherwise Poshi will forcibly black-list certain modules, which messes with our Blacklist tests

**Comment by kyle-miho** [comment]
I'm not sure why they are forcibly blacklisted, since it doesnt make sense from a business perspective or in a testing perspective (should be isolated), but this is how we can get around that

**Comment by vicnate5** [comment]
Thanks.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/86286

**Pull request closed without merging**
