### PR TITLE
LPS-64582 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
hey @vicnate5, could you help us to double check that we're not causing regressions?

This affects the visibility expressions of all field types.

cc @brunobasto 

Thanks

### CODE REVIEW

**Comment by vicnate5** [comment]
@brunobasto @marcellustavares 

Not sure this is a regression from this pull or a just a bug I found, but if a field gets visibility value from a Multiline and Required text field, it does not work right away.

Steps:
1. Add new Form
2. Add text field ("TextName", Required, Multiline)
3. Add Radio - Visibility - equals(TextName, "test")
4. Save form
5. Select form in Form Portlet
6. Input text field "test"

Radio field should be visible.

Only workaround I found, double click "test" word in the text field so that it is highlighted. Click out of the field.

**Comment by vicnate5** [comment]
@marcellustavares @brunobasto So I checked and the above issue is not a regression from this pull. I reproduced on RC1. I will file a ticket instead.

**Comment by marcellustavares** [comment]
k, we'll fix that. thx @vicnate5

**Comment by vicnate5** [comment]
@marcellustavares @brunobasto 

Unfortunately I did find a regression on the pull that I cannot reproduce on RC1.

**Repeatable Field with conditional visibility cannot be repeated.**

Steps:
1. Add new Form
2. Add text field ("TextName")
3. Add Select field - Visibility - equals(TextName, "test")
4. Save form
5. Select form in Form Portlet
6. Input text field "test"
7. Click Plus Icon to repeat select field

Field is not repeatable.

**Comment by marcellustavares** [comment]
Awesome, thx a lot @vicnate5

**Comment by brunobasto** [comment]
hey @vicnate5,

I'll take a look. Thanks!

**Comment by vicnate5** [comment]
I am going to close this for now. Feel free to send me another pull.

**Comment by leoadb** [comment]
@vicnate5 Please assign the ticket to me as soon as you get filed. Thanks !!!

**Comment by brunobasto** [comment]
Hey @vicnate5,

Resent at https://github.com/vicnate5/liferay-portal/pull/296.

Let me know if you find any other issue.

Thanks,

**Pull request closed without merging**
