### PR TITLE
LRQA-73386

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@kyle-miho

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Create ticket https://issues.liferay.com/browse/COMMERCE-8486 for this startup error.

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
