### PR TITLE
LPS-163117 Uniform | Fix backend DB Partition tests not running on our routines

### PR DESCRIPTION
**Pull request by lucasperj**
https://issues.liferay.com/browse/LPS-163117

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
@lucasperj Doesn't look like this worked (you won't see any integration tests in the db-partition results). You will need to add `modules-integration-mysql57-jdk8` and `modules-unit-jdk8` batch to the db-partition suite for the tests to run.

Also you do not need to include `*TestCase.java` since those classes are not the actual test running classes. Only look for `*Test.java` 

It would be better for this case to just include all tests in the modules for DB partition.
e.g. `**/portal-db-partition-test/**/*Test.java`

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:test:db-partition

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/123185

**Pull request closed without merging**
