### PR TITLE
LPS-68854 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
@brunobasto Known build failure. not related to your changes.

**Comment by vicnate5** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
ci:retest

**Comment by ctampoya** [comment]
Pushed to VWare.
https://github.com/vicnate5/liferay-portal/pull/583

**Pull request closed without merging**
