### PR TITLE
Tomcat LPS-172797 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LPS-172797

@vicnate5 This is to update tomcat for master. Tested here and no regressions: https://github.com/Kvale1733/liferay-portal/pull/255

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@Kvale1733 Looks like we can't use the cve in the commit message. Update this to just note we are updating tomcat.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
Looks like the highest tomcat mirror version Liferay has is 9.0.69 even though tomcat most recent is 9.0.71. Will resend with 9.0.69.

**Comment by Kvale1733** [comment]
ci:close

**Comment by Kvale1733** [comment]
ci:reopen

**Comment by vicnate5** [comment]
Testing release tool fix at https://github.com/vicnate5/liferay-portal/pull/2237

**Comment by vicnate5** [comment]
I sent a PR to the release repo
https://github.com/CAustin582/liferay-release-tool-ee/pull/95

Will need this merged before we merge the Tomcat upgrade.

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
@Kvale1733 This is working now, but we are getting random timeouts due to the fact that we are falling back to download from apache instead of mirrors.

I think we just still need to get mirrors updated.

Can you open an IT ticket to update mirrors?

**Comment by Kvale1733** [comment]
[IS-13649](https://issues.liferay.com/browse/IS-13649)

**Comment by Kvale1733** [comment]
@vicnate5 The mirror is updated. Should we rerun relevant?

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/129277

**Pull request closed without merging**
