### PR TITLE
LPS-63830 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @rafaprax

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares @rafaprax The ability to "search" for lists when selecting them in the DDL Display configuration is gone. Is this an intended limitation of lexicon?

**Comment by rafaprax** [comment]
@vicnate5 That isn't a lexicon limitation but It was proposed by Ivan Morote's review/redesign to DDL Display Portlet. You can see the documentation about the review/redesign here(https://issues.liferay.com/secure/attachment/160078/160078_Dynamic+Data+List+Display.pdf) 

Thx

**Comment by vicnate5** [comment]
@rafaprax I am gonna send this to you with the test fixes so you can add the search back in :)

**Comment by rafaprax** [comment]
Thx @vicnate5

**Comment by vicnate5** [comment]
Pushed to @rafaprax 
https://github.com/rafaprax/liferay-portal/pull/64

**Pull request closed without merging**
