### PR TITLE
LRQA-52641 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-52641

### CODE REVIEW

**Comment by john-co** [comment]
Ignoring from acceptance until resolved based on discussion on slack with @manoelcyreno. Created tickets attached to LRQA-52641 for refactoring flaky tests. May need to consider how to include these tests in release testing if they're required.

cc/ @kyle-miho

**Comment by vicnate5** [comment]
These tests will still run during release testing because `property portal.release = "true"` is set

**Comment by vicnate5** [comment]
@john-co what branches is this for? Brian is no longer auto backporting

**Comment by john-co** [comment]
master and 7.2.x

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/79371
https://github.com/brianchandotcom/liferay-portal-ee/pull/26923

**Pull request closed without merging**
