### PR TITLE
LRQA-46475 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-46475

### CODE REVIEW

**Comment by kyle-miho** [comment]
@vicnate5 Test to see if this fits the requirements for the test Portlet.

You should be able to deploy the api / service / web modules (the service module has a dependency on the api module so it wont work if the api module is not deployed)

The web module should allow a Portlet called test to be added to a widget page (category is also test)

Deploying the service module should create the DB table for it upon as part of its default upgrade process.

Let me know if i need to make any adjustments

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by vicnate5** [comment]
Pushed to Tina
https://github.com/tinatian/liferay-portal/pull/2278

**Pull request closed without merging**
