### PR TITLE
LPS-169969 Uniform Automated tests | Fix DocumentLibraryLogged testcase

### PR DESCRIPTION
**Pull request by lucasperj**
Issue link : https://issues.liferay.com/browse/LPS-169969
Tested here : https://github.com/lucasperj/liferay-portal/pull/314 ([Passed](https://testray.liferay.com/home/-/testray/case_results/2157590563?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2157579752%26testrayRunId%3D2157590106%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc))

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
As we discussed, Lucas will do more testing to find out why their is a difference before we move forward.

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:reopen

**Pull request closed without merging**
