### PR TITLE
LPS-147273 Temporarily ignore test until it is fixed because it causes other integration tests to hang

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-147273

### CODE REVIEW

**Comment by kyle-miho** [comment]
We need to ignore the whole class since an injected module is failing to resolve, no test in this integration test class will start

**Comment by vicnate5** [comment]
@kyle-miho You sure this modules test all work after this? When I tried this, I still got hanging https://github.com/vicnate5/liferay-portal/pull/1980#issuecomment-1040952592. Maybe I had some local issue.

**Comment by vicnate5** [comment]
@kyle-miho Can you confirm that these steps work?
1. Start Portal
2. cd modules/apps/content-dashboard/content-dashboard-blogs-test/
3. `gw testIntegration`

**Comment by kyle-miho** [comment]
now successfully ignores the test classes, there were multiple failures

**Comment by vicnate5** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/113535

**Pull request closed without merging**
