### PR TITLE
master-qa-50461

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-50461

7.1.x: [vicnate5/liferay-portal-ee#260](https://github.com/vicnate5/liferay-portal-ee/pull/260)
7.0.x: [vicnate5/liferay-portal-ee#259](https://github.com/vicnate5/liferay-portal-ee/pull/259)

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@zhangyan0701 The new tests all failed, is there known issues? Some are missing a variable declaration?

https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=675131561&testrayComponentId=438902455&testrayRunId=675131563

**Comment by zhangyan0701** [comment]
@vicnate5 Yes, there are two issues: 
https://issues.liferay.com/browse/LPS-97976
https://issues.liferay.com/browse/LPS-98192

The error that looks like missing variable declaration, I filed https://issues.liferay.com/browse/LPS-98168 that I thought it was a portal issue but a wrong configuration on 70. I created sub-task https://issues.liferay.com/browse/LRQA-50566 to update the pre-upgrade tests of 70. 
Can I resend post-upgrade test after LRQA-50566 is closed? 
Sorry for any inconvenience!

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@zhangyan0701 After we get the test fixes in, resend this this with ignores for the tests that will fail due to open bugs, we can merge this, but it isn't worth running these tests until we know they might pass.

**Pull request closed without merging**
