### PR TITLE
LRQA-73874 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-73874

Test passed on CI, testray result: https://testray.liferay.com/home/-/testray/case_results/1916921105

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@catarineaguiar @zhangyan0701  This test has a high chance of giving us a false positive result, since we are checking an empty directory.

On my local machine I made this change:
```
-               var displayDateYear = DateUtil.getFormattedCurrentDate("yyyy");
+               var displayDateYear = "FAKEDIR";
```
The test still passed.
```
Temp Folder before Reindex: []
```


We need a way to verify that the directory is empty BUT also exists.
Can you get the tempDir's file path and store that as your compare value? 

Please resend with a check that will fail if the directory doesn't exist.

**Comment by catarineaguiar** [comment]
@vicnate5 do you mean that we need to assert if the s3 file exists and is populated, right?

**Comment by vicnate5** [comment]
@catarineaguiar We need to make sure we are checking a real directory (even though we are checking it is empty). Right now the test will passed even if the whole directory does not exist.

**Pull request closed without merging**
