### PR TITLE
LPS-122557 git commit

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:cluster-license

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
@gaborlovasdotcom @JoyceWang08211 I don't have enough understanding of SAML to fully test this, can one of you test the solution?

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
@vicnate5 The latest pull should fix all the issues, it passed on ci, could you please verify the manual tests?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian Status update

### Known Issue 1
**FIXED** 5th node will start deactivated, then each node will shut down (5, 4, 3).

~~When I exceed the node limit by more than double, none of the nodes shutdown - they deactivate instead. (Node limit: 2, Nodes started 5). The 5th node never activates and remains deactivated. The other nodes will deactivate after the grace period, instead of shutting down. The first 2 nodes (that do not deactivate) continue to show the UI warning about exceeding the node count.~~

I added an automation test for exceeding the node limit by more than double, but because of the heaviness of running 5 tomcats, it might never be stable enough to run on CI regularly. It still makes local testing a little easier for me when needed.


### Known Issue 2
**FIXED**
~~There is some inconsistency on which node gets deactivated when using manual recovery (`license.cluster.overload.node.auto.shut.down=false`), even though we always start the nodes in the same order. Automation shows that any of the 3 nodes randomly might be the one deactivated after the grace period. The expected result is that the 3rd node deactivates, so the automation will pass in this scenario.~~


### Known Issue 3
Message shows time limit now, but
We should probably discuss the entire message wording and format with product stakeholders, and this is easy to fix in a follow up. **Will open a Slack thread**.
screenshot6
~~The UI error message needs to be cleaned up in wording and is not always populating variable values.~~

~~Example UI message:
"You have exceeded the maximum number of cluster nodes 2, please shut down overloaded nodes as soon as possible. Grace period started and will expire in , 4 nodes are allowed during grace period, current node is at 2, it is normal and will not be deactivated or shut down automatically after grace period"~~

~~Notice "Grace period started and will expire in [blank]". I did modify the grace period to only 5 minutes in my test build, but shouldn't the message [account for minutes left](https://github.com/tinatian/liferay-release-tool-ee/pull/74/files#diff-bd599bcf924b0ced63de886ecb6f6242a976be5d2e0c92e484cf5f6dae454c35R732)? I know that the real user period will always be 2 hours, I will try to test again with the real time period when I have a chance.~~

### Known Issue 4
**Remaining issue:** Message does not show in Node 2 of 3 when using Manual Recovery. Automation will pass when this is fixed.
~~I think the error message should show up in all node console logs. We didn't enforce this before, but I expect we might have users who are relying on the console output to provide information about the cluster status. Also, it should be there [per the spec](https://docs.google.com/document/d/1ahZnkNMKWKrqTaxvCzpyZBiFd4qNChKjQbV65eMmIoo/edit#):
"When the number of cluster nodes is exceeded, the cluster will kick off the 2-hour grace period and display grace period warnings in the console and for admin users in the UI, on all nodes."~~

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Pull request closed without merging**
