### PR TITLE
LPS-69593 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45431

**Comment by cleydyr** [comment]
Hey, @vicnate5

I see that the commits for [LPS-69593](https://issues.liferay.com/browse/LPS-69593) didn't get into the PR you've sent to BChan. Can you send it again?

Thank you.

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@cleydyr Thanks, sorry I must have accidentally closed this and added the wrong link. I want to add a poshi test for this use case and then push it in.

**Comment by cleydyr** [comment]
No problem, @vicnate5. ;)

**Comment by vicnate5** [comment]
Pushed to BChan. https://github.com/brianchandotcom/liferay-portal/pull/45920

For real this time!

**Pull request closed without merging**
