### PR TITLE
LPS-173727 Uniform Automated test | Include VerifyResourcePermissionsTest class to Upgrades suite

### PR DESCRIPTION
**Pull request by lucasperj**
Issue link: https://issues.liferay.com/browse/LPS-173727

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
W/ that it will add 
- VerifyPropertiesTest.java
- VerifyResourcePermissionsTest.java 
- VerifyUUIDTest.java

It will also add 
- VerifyGroupTest.java

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/129328

**Pull request closed without merging**
