### PR TITLE
LRQA-66288 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-66288

### CODE REVIEW

**Comment by kyle-miho** [comment]
Backport as far back as we can, however this is likely requires manual backports to each branch, should probably do them 1 at a time after this gets merged

**Comment by vicnate5** [comment]
@kyle-miho Can you confirm that the test failures here are not related?

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
fyi previous build failed on a new CI environment, I'm rerunning the build.

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
@vicnate5 failing tests are unrelated

**Comment by vicnate5** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
@kyle-miho There looks to be a unique failure on this change related to the JSON calls

Example: https://testray.liferay.com/home/-/testray/case_results/1528167209/history?p_p_state=normal&orderByCol=createDate_sortable&orderByType=desc&statuses=3&errors=userId

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
There were new failures that were not present before ~10, need to re-run

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
@vicnate5 if you want to push through now, there were 3 unique failures, 2 Remote Staging ones which require more tuning up, the other one is a DB partitioning one which i fixed the UI steps for

**Comment by kyle-miho** [comment]
ci:test

**Comment by vicnate5** [comment]
See https://github.com/vicnate5/liferay-portal/pull/1724

**Pull request closed without merging**
