### PR TITLE
LPS-68877 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
@vicnate5, let me know if it's a real failure, the original pull passed https://github.com/marcellustavares/liferay-portal/pull/1699

**Comment by vicnate5** [comment]
@marcellustavares Something funny with SPA. It was all on one batch so it might be a fluke. ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@marcellustavares Unfortunately this looks like a real failure. The page load freezes when user attempts to assign/transition a Workflow task.

Steps to used to Reproduce manually:
1. Enable workflow for blogs
2. Add blogs entry
3. Go to My Workflow Tasks > Assigned to My Roles
4. Navigate to asset details
5. Assign to Me
6. Click "Done" on the comment pop-up

Result: Page loads indefinitely. SPA gives warning `Oops It looks like this is taking longer than expected.`

**Comment by marcellustavares** [comment]
got it @vicnate5, it may be related to Bruno's SF, will send this to @thiago-rocha take a look.

Thanks

**Comment by marcellustavares** [comment]
sent to https://github.com/thiago-rocha/liferay-portal/pull/40

**Comment by thiago-rocha** [comment]
https://github.com/vicnate5/liferay-portal/pull/633

**Pull request closed without merging**
