### PR TITLE
LPS-90086 SF

### PR DESCRIPTION
**Pull request by anthony-chu**
Tests running here:
https://github.com/anthony-chu/liferay-portal/pull/589
https://github.com/anthony-chu/liferay-portal/pull/590

### CODE REVIEW

**Comment by vicnate5** [comment]
running more tests because I am worried about regressions in weird places...

**Comment by vicnate5** [comment]
@anthony-chu  are we good on this now?

**Comment by vicnate5** [comment]
@anthony-chu  Send me a new pull when this is ready

**Comment by anthony-chu** [comment]
Pull sent here: https://github.com/vicnate5/liferay-portal/pull/1123

Failures are accounted for upstream or are present in other pulls elsewhere.

**Pull request closed without merging**
