### PR TITLE
LPS-171004 Investigate false positives for DatabaseUpgradeClient tests

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-171004

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:upgrade:nocompile

**Comment by susanchen3** [comment]
ci:test:upgrade:nocompile

**Comment by susanchen3** [comment]
Upgrade process is complete in this latest run.
[LocalFile.DatabaseUpgradeClient#CheckUpgradeClientGogoShellFailedUpgrade](https://testray.liferay.com/reports/production/logs/2023-01/test-1-29/test-portal-acceptance-pullrequest(master)/6044/functional-upgrade-tomcat90-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0) took 509 seconds.
[LocalFile.DatabaseUpgradeClient#CheckUpgradeClientUpgradeCoreOnly](https://testray.liferay.com/reports/production/logs/2023-01/test-1-29/test-portal-acceptance-pullrequest(master)/6044/functional-upgrade-tomcat90-mysql57-jdk8/0/11/jenkins-console.txt.gz?authuser=0) took 80 seconds.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/128433

**Pull request closed without merging**
