### PR TITLE
DB2 Temp fix

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@zhangyan0701

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by yuhai** [comment]
Hi @vicnate5, 

I want to confirm two things.

1.What's the probability of this issue happening in CI?
2. I check the test [log](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128415/consoleFull), and find the below properties.
```
 jdbc.default.driverClassName=com.ibm.db2.jcc.DB2Driver
 jdbc.default.url=jdbc:db2://test-1-29-20.lax.liferay.com_db2:50000/lportal:deferPrepares=false;fullyMaterializeInputStreams=true;fullyMaterializeLobData=true;progresssiveLocators=2;progressiveStreaming=2;
 jdbc.default.username=root
jdbc.default.password=******** 
```
But in your the latest provided [log](https://gist.githubusercontent.com/vicnate5/02cf48a1f23a9901ef525f9da1e7e5cb/raw/39eb6530e9e35ef698a0d04e379db507cd79340c/gistfile1.txt), it display Caused by: 
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=**DB2INST1**.DDLRECORD, DRIVER=4.24.92

If the configurations were same. It seems it was trying to find the DDLRECORD table under **DB2INST1**, but the right user should be **root**. Could you please check this?

**Comment by yuhai** [comment]
@zhangyan0701, could you please also scan the test result? Thanks.

**Comment by zhangyan0701** [comment]
There are some objects integration tests failed with error like below:
```
     [exec] com.liferay.object.service.test.ObjectEntryServiceTest > testDeleteObjectEntry FAILED
     [exec]     com.liferay.portal.kernel.exception.SystemException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.O_20098_AXWT2RBBK, DRIVER=4.24.92
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-07/test-1-35/test-portal-acceptance-pullrequest(master)/2105/modules-integration-db2111-jdk8/2/17/jenkins-console.txt.gz?authuser=0

After talking with @yuhai , this error is most likely the same issue as LPS-112222, and the temp fix only covers the error during portal startup, but in the integration tests, the error occurred after portal fully startup.

And he is trying another possible fix in https://github.com/yuhai/liferay-portal/pull/292, will also follow up on that.

**Comment by yuhai** [comment]
Hi @vicnate5,

After talked with @zhangyan0701, please ignore my the previous comment. I will delete it.

Thanks.

**Pull request closed without merging**
