### PR TITLE
LPS-119582 Try to index the page by finding a surrogate user

### PR DESCRIPTION
**Pull request by jkappler**
Hi @vicnate5, we prefer to send this to you first so as not to cause more regressions. Partitioning and Websphere issues should be solved thanks to @dacousalr

Peer review was already done, so we could send to BChan directly. Please let us know what you think.

Thanks

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
will resend

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@jkappler

2 Regressions in the test results:

1. Database partitioning test still failed. The user cannot access the new partition. 
```
ERROR [main][PortletTracker:393] Portlet com_liferay_product_navigation_user_personal_bar_web_portlet_ProductNavigationUserPersonalBarPortlet from com.liferay.product.navigation.user.personal.bar.web_6.0.0 [1199] failed to initialize
com.liferay.portal.kernel.exception.NoSuchRoleException: No Role exists with the key {companyId=41051, name=Guest}
	at com.liferay.portal.service.persistence.impl.RolePersistenceImpl.findByC_N(RolePersistenceImpl.java:5773)
	at com.liferay.portal.service.impl.RoleLocalServiceImpl.getRole(RoleLocalServiceImpl.java:797)
``` 
-- [Full Liferay log](https://testray.liferay.com/reports/production/logs/test-1-3/1604426355908/test-portal-acceptance-pullrequest(master)/8415/functional-tomcat90-mysql57-jdk8/4/2/liferay-log.txt.gz).

2. There is also a unique integration test failure: [LayoutSetPrototypePropagationTest.testLayoutPropagationWhenLoadingLayoutsTreeWithLinkEnabled](https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/310171/AXIS_VARIABLE=20,label_exp=!master/testReport/junit/com.liferay.exportimport.test/LayoutSetPrototypePropagationTest/testLayoutPropagationWhenLoadingLayoutsTreeWithLinkEnabled/)
I was able to reproduce the failure locally.

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
Unable to test Websphere due to issue on CI, will need to retest once this is resolved.

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
Websphere is OK

**Comment by jkappler** [comment]
Hi @vicnate5, taking with @pavel-savinov and @dacousalr, it seems that the partitioning could be a flaky one. Neither Pavel or I can reproduce it in local, and as for Daniel, he can reproduce it without this pull.

Could it have to do with mysql version or something with the dev environment? All my tests were with mysql 5.7 and on Mac OSX

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@vicnate5, @dacousalr found the issue, will take a look

**Pull request closed without merging**
