### PR TITLE
LPS-143837 | master

### PR DESCRIPTION
**Pull request by Hijky**
https://issues.liferay.com/browse/LPS-143837
This is only for master

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@Hijky Can you also review the test results for regressions?

**Comment by Hijky** [comment]
> 

I ran ci:test before and compared the results on testray. Those errors will also appear before the Tomcat version is not changed.

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@Hijky In the future, make sure to check for existing tickets when reporting tomcat CVE issues. In this case, a ticket already existed from October https://issues.liferay.com/browse/LPS-140818

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/111170

**Comment by Hijky** [comment]
> @Hijky In the future, make sure to check for existing tickets when reporting tomcat CVE issues. In this case, a ticket already existed from October https://issues.liferay.com/browse/LPS-140818
> 
> Pushed to BChan. [brianchandotcom#111170](https://github.com/brianchandotcom/liferay-portal/pull/111170)

Next time I will double check if the ticket already exists

**Pull request closed without merging**
