### PR TITLE
LRQA-72728 Disable FileInstallCFGTest for release bundles since it can get stuck in deadlock in release bundles causing mass test failures

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@kyle-miho Shouldn't this be under `portal-release` instead of `test-portal-release`?

**Comment by kyle-miho** [comment]
@vicnate5 fixed

**Comment by vicnate5** [comment]
Moved to LPS-150161

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/116868

**Pull request closed without merging**
