### PR TITLE
LPS-64305 Setting the value of fields before set the key when the field is restored by the backend

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
@brunobasto Writing a poshi test for this would be really easy, but this looks like a case where we can just javascript test it (js might be faster and more reliable). What do you think?

**Comment by brunobasto** [comment]
I think most aspects of this can be unit tested by JS Tests. Things like saving the DDL or WebContent and then editing it to make sure the value saved is actually there could be tested by poshi - because this not only tests that the JS code works, but also that the back-end also works.

**Comment by vicnate5** [comment]
I didn't know this affected old DDM. Editing a DDM field name for instance? We already have a poshi test for that on the PR tester `CPDynamicdatalists#EditBooleanFieldFieldLabel`

**Comment by brunobasto** [comment]
@vicnate5 Disregard my last comment. I commented on the wrong pull request. This does not affect the old DDM whatsoever. That comment was supposed to go the the "Link To Page" pull request. Sorry

**Comment by vicnate5** [comment]
@brunobasto So for this pull it looks like something that should be JS test but we might need to use poshi for now because it is what we have. That sound good to you? It will be a quick test to write.

**Comment by brunobasto** [comment]
Hey @vicnate5, yeah, let's just write a poshi tests for now. I'll try to push for the JS tests. Thx

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-26277

**Comment by vicnate5** [comment]
Pushed to BChan with poshi test.
https://github.com/brianchandotcom/liferay-portal/pull/41180

**Pull request closed without merging**
