### PR TITLE
LPS-164410 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LPS-164410

This is to update Tomcat for master only. Tested here and no regressions found: https://github.com/Kvale1733/liferay-portal/pull/201

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/123908

@Kvale1733 I modified the commit message to include the CVEs

**Comment by vicnate5** [comment]
@Kvale1733 Please do the backports when you have a chance in the next week. Send PRs to the `liferay` user on https://github.com/liferay/liferay-portal-ee

**Pull request closed without merging**
