### PR TITLE
LPS-109105 | master

### PR DESCRIPTION
**Pull request by vicnate5**
See if this solves the known issues. Forward to Brian if this is consistently passing

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/85921

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Rebased

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@achaparro Failures here are different than before, most of them are due to indexing. 

I sent another PR to see what happens if we auto upgrade from older versions of portal
https://github.com/vicnate5/liferay-portal/pull/1440

**Comment by achaparro** [comment]
Yeah @vicnate5, I thought we could still have issue with the stale version of release records since it seemed not related to the fix but I see it's fixed. Those are great news :-)

I guess from previous versions we will get the error about the BasicDLFileEntryType since we still do the call before the upgrade.

Thanks.

**Pull request closed without merging**
