### PR TITLE
LRQA-72302 | master

### PR DESCRIPTION
**Pull request by Hijky**
This is only for master
https://issues.liferay.com/browse/LRQA-72302
https://issues.liferay.com/browse/LRQA-72303
https://issues.liferay.com/browse/LRQA-72304
https://issues.liferay.com/browse/LRQA-72305
https://issues.liferay.com/browse/LRQA-72306

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
The latest pull is for test.name.skip.portal.instance case name

**Comment by Hijky** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/111930


@Hijky See my changes. When you rename a file, make sure to `mv` instead of `cp` and make sure git is deleting and adding the new file in the same commit. And please check with me or Summer on test priority if you are not sure. Priority 5 tests should be in `portal.acceptance`.

Also can you update your git config for your name and email?
```
git config --global user.name "Kevin Wan"
git config --global user.email "kevin.wan@liferay.com>"
```
Note the capitalization/case I used. I manually fixed the author for the commits in this PR.

**Pull request closed without merging**
