### PR TITLE
LPS-108993 Auto upgrade fixes

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
I don't see previous failures, what do you think @vicnate5 ?

I sent another upgrade tests to verify it.

**Comment by vicnate5** [comment]
@achaparro the failures here are the same as the previous PR. A document cannot be found by search after upgrade.

**Comment by achaparro** [comment]
Hi @vicnate5,

this pull is intended to solve these issues:
https://github.com/vicnate5/liferay-portal/pull/1440#issuecomment-597771085

they are solved with it.

The document library issue is another one I haven't worked on it yet but maybe it's not related with upgrades

**Comment by vicnate5** [comment]
@achaparro I can make a new ticket for the Document search issue. If this ticket is ready, can you drop all the `TEMP` commits and force push? We should run a normal upgrade test suite now.

**Comment by achaparro** [comment]
Ok @vicnate5, let's do that. I will send this pull to Brian and share the LPS about the DL indexing issue with me.

Thanks!

**Pull request closed without merging**
