### PR TITLE
LPS-103493 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Testing changes on LPS-103493

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@dantewang test got passed the compile, then failed to build the apps, looking into it.

**Comment by vicnate5** [comment]
@dantewang I reproduced the problem locally. I am pretty sure this is unrelated to you change, you can probably send your fix in, we just have more issues on this test.

**Comment by vicnate5** [comment]
New issue
```
download-artifact:
[stopwatch] [run.batch.test.action: 9:20.241 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build.xml:129: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-release.xml:779: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/get-release-apps.xml:11: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/get-release-app.xml:37: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:376: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app-module.xml:109: Missing artifact.properties file in /opt/dev/projects/github/liferay-portal/modules/.releng/apps/account/account-admin-web.
      [get] Getting: http://test-1-16/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/332150//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20191106223400627.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20191106223400627.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1445187784.properties
```

**Comment by dantewang** [comment]
@vicnate5 Thanks! I'll send my change up.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by dantewang** [comment]
Cool, thanks @vicnate5 !

**Pull request closed without merging**
