### PR TITLE
LRQA-52312 Adding Appbuilder.testcase and AppBuilder.macro in modules/apps/app-builder/app-builder-test directory

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
Hey @vicnate5 , could you please double-check my last commits related to moving tests from portal-web to modules/apps/app-builder? Thanks!

**Comment by vicnate5** [comment]
@alexcandidos The only issue here is that the test files should follow the same directory structure as we have in portal web (directories: macros, paths, tests).

@patriciajeanperez this needs to be fixed here too https://github.com/liferay/liferay-portal/tree/master/modules/apps/account/account-test/src/testFunctional

See example https://github.com/liferay/com-liferay-commerce/tree/7.1.x/commerce-product-test/src/testFunctional

**Comment by patriciajeanperez** [comment]
I see, thanks @vicnate5! Will update those

**Comment by alexcandidos** [comment]
Thanks @vicnate5 !! :)

**Pull request closed without merging**
