### PR TITLE
LPS-66815 Create browse portlet provider

### PR DESCRIPTION
**Pull request by marcellustavares**
@vicnate5, I was talking to @jkappler and the only way to access this view is thru content targeting, can we add some tests to this?

Thanks

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @vicnate5, @anthony-chu created some functional tests for this. You can check them out here: https://github.com/brianwulbern/liferay-portal/pull/187

**Comment by vicnate5** [comment]
Thanks @jkappler! @marcellustavares There is a test already in source that covers this basic use case of this story. 
1. The user creates a form and wants to track user interaction with that specific form
2. After creating a campaign and user segment in Audience Targeting, he/she creates a new report
3. The user selects "Form" in order to track it
4. The user then selects the form that he/she wants to track from the list of available forms that show up in the form browser

However, when testing this manually with @anthony-chu we found a bug that prevents us from fully testing this implementation of Forms. 
See https://issues.liferay.com/browse/WCM-754
We can write a test for this bug when it is fixed.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41294

**Comment by marcellustavares** [comment]
Cool, thanks for the analysis @vicnate5.

**Pull request closed without merging**
