### PR TITLE
LPS-85610 SF

### PR DESCRIPTION
**Pull request by anthony-chu**
Testing was done here: https://github.com/anthony-chu/liferay-portal/pull/542#issuecomment-429162536 - failures were unrelated to changes in pull, as they happened on other pulls as well.

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
just to be sure

**Comment by vicnate5** [comment]
ci:test

**Comment by anthony-chu** [comment]
looks like the LPKG tests are failing here too =[

**Comment by vicnate5** [comment]
They aren't totally fixed at head as of running this.

**Pull request closed without merging**
