### PR TITLE
LRQA-25388 Change field type values to adapt to the new field type labels

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
@brunobasto , @vicnate5 , could you check it please?
Thank you, guys :)

**Comment by brunobasto** [comment]
Looks good to me 👍

**Comment by ctampoya** [comment]
Looks Good :+1:

**Comment by pedroqueiroz94** [comment]
Thank you guys, @brunobasto @ctampoya :)

**Comment by brunobasto** [comment]
hey @vicnate5, If everything goes alright, yes :)

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40089

**Pull request closed without merging**
