### PR TITLE
LRQA-52008 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-52008

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:poshi

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Faliures are upstream: HSQL/HSQLEE, Blogs NPE, WEM Test Fixes, etc.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/80008
https://github.com/brianchandotcom/liferay-portal-ee/pull/27248

**Pull request closed without merging**
