### PR TITLE
LPS-106592-LPS-103577 test

### PR DESCRIPTION
**Pull request by tinatian**
Hi Victor,
This pull is based on https://github.com/shuyangzhou/liferay-portal/pull/8879.

Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:search-es7

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
@vicnate5 Is there random startup error on this pull?

Tina

**Comment by vicnate5** [comment]
@tinatian Startup error not seen on the results here.

**Comment by vicnate5** [comment]
@tinatian see new manual test results at https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit?ts=5e2a3128#gid=1206555946&range=E2

**Comment by tinatian** [comment]
Update at https://github.com/vicnate5/liferay-portal/pull/1420

**Pull request closed without merging**
