### PR TITLE
LPS-64945 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
This is an IE specific issue, correct? We could write a poshi test for this, but it would not be regularly running on IE at this time. But it might be worth it to have a test for the future as we improve our environment testing.

**Comment by brunobasto** [comment]
Hey @vicnate5, it only happens on IE. Yeah, would be nice to have it for when CI gains the ability to run tests on IE.

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-26276

**Comment by vicnate5** [comment]
https://github.com/brunobasto/liferay-portal/pull/650

**Pull request closed without merging**
