### PR TITLE
LRQA-53782 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-53782

### CODE REVIEW

**Comment by kyle-miho** [comment]
Tested here: https://github.com/kyle-miho/liferay-portal/pull/335
Issue we talked about: problem was the default created DB name is different for SQL Server compared to other databases. For some reason every database uses the name lportal1, but SQLServer uses lportal

**Comment by vicnate5** [comment]
@kyle-miho the database name should be determined either by our ant scripts or by the `create.sql` scripts generated during `ant all`. No leads on why this is different for SQL Server?

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/85872

**Comment by kyle-miho** [comment]
@vicnate5 yea its generated by our ant scripts, lportal not lportal only for sqlserver
`
<elseif>
						<equals arg1="${database.type}" arg2="sqlserver" />
						<then>
							<replace
								file="create.sql"
							>
								<replacefilter>
									<replacetoken>create database lportal;

go</replacetoken>
									<replacevalue><![CDATA[create database lportal;

go

alter database lportal set allow_snapshot_isolation on;
go

alter database lportal set read_committed_snapshot on;
go]]></replacevalue>
								</replacefilter>
							</replace>
						</then>
					</elseif>
`

**Pull request closed without merging**
