### PR TITLE
LRQA-X SF

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@zhangyan0701 Can you investigate why this doesn't fail SF? A single use file should not be permitted in global dependencies.

**Comment by zhangyan0701** [comment]
I think the SF only checks the multiple usages of a file, but not check single use file. I will confirm with Alan.

**Comment by ling-alan-huang** [comment]
I am working on adding this SF rule.

**Comment by ling-alan-huang** [comment]
see: https://github.com/hhuijser/liferay-portal/pull/6067

**Pull request closed without merging**
