### PR TITLE
LPS-112222 DB2 Verify - Empty Database - output stack trace

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:environments:nocompile

**Comment by yuhai** [comment]
ci:test:environments:nocompile

**Comment by vicnate5** [comment]
New failure here https://testray.liferay.com/reports/production/logs/2022-02/test-1-35/test-portal-acceptance-pullrequest(master)/716/modules-integration-db2111-jdk8/1/3/jenkins-console.txt.gz

**Comment by yuhai** [comment]
@vicnate5, I find the latest [run](https://github.com/vicnate5/liferay-portal/pull/1974#issuecomment-1039717605) and the current pr ci test didn't take my added commits to run because their output logs dismatch with my changed classes. I rerun the ci test from https://github.com/yuhai/liferay-portal/pull/280

**Comment by yuhai** [comment]
ci:test:environments

**Pull request closed without merging**
