### PR TITLE
LRQA-62584 Use a custom app server startup because the normal app server startup target is wrapped in a java class that will strip out the environment variables

### PR DESCRIPTION
**Pull request by vicnate5**
@koor4356 https://issues.liferay.com/browse/LRQA-62584

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
Passed but I noticed `[delete] Deleting directory /opt/dev/projects/github/liferay-portal/bundles/osgi/state`

We need to test with the same state folder between startups.

**Comment by koor4356** [comment]
okay, I will do

**Pull request closed without merging**
