### PR TITLE
master-qa-46825

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-46825

This is for master only!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69277

See https://github.com/brianchandotcom/liferay-portal/pull/69277/commits/7adb8c0446e99388205dd1933ef075663ab33872

**Pull request closed without merging**
