### PR TITLE
LPS-167187 Uniform | Drop schema only if exists when executing create-*.sql script to postgres and sqlserver

### PR DESCRIPTION
**Pull request by lucasperj**
Issue: https://issues.liferay.com/browse/LPS-167187
Tested here: https://github.com/lucasperj/liferay-portal/pull/309

### CODE REVIEW

**Comment by lucasperj** [comment]
@vicnate5 , regarding this cases, I have the premise that passed because:
We cant find `ERROR:  database "lportal" does not exist` for example for [PortalSmokeAutoUpgrade#ViewPortalSmokeArchiveAutoUpgrade740](https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6463/functional-upgrade-tomcat90-postgresql134-jdk8/0/8/jenkins-console.txt.gz?authuser=0) with Postgresql 13.4 , and looking somewhere that does not have this changes, we can, for example at [PortalSmokeAutoUpgrade#ViewPortalSmokeArchiveAutoUpgrade740 on pull 2168](https://testray.liferay.com/reports/production/logs/2022-10/test-1-29/test-portal-acceptance-pullrequest(master)/5220/functional-upgrade-tomcat90-postgresql134-jdk8/0/8/jenkins-console.txt.gz?authuser=0).

**Comment by vicnate5** [comment]
I am worried this might cause a version bump for the portal, running relevant to check.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Pushed to Core team
https://github.com/liferay-core-infra/liferay-portal/pull/2412

**Pull request closed without merging**
