### PR TITLE
LPS-75036 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Temp test with subrepo changes

### CODE REVIEW

**Comment by vicnate5** [comment]
@leoadb Hashi told me it would not do the subrepo change check if I send to myself.

So using this.

**Comment by vicnate5** [comment]
@leoadb I built this locally. The form builder still did not render.

Liferay console:
```
19:19:15,695 ERROR [http-nio-8080-exec-3][GoogleJavaScriptMinifier:116] (/o/dynamic-data-mapping-form-renderer/js/soy_template_util.js:22): Parse error. syntax error
19:19:15,699 ERROR [http-nio-8080-exec-3][GoogleJavaScriptMinifier:116] (/o/dynamic-data-mapping-form-renderer/js/soy_template_util.js:22): Parse error. illegal character
19:19:15,699 ERROR [http-nio-8080-exec-3][GoogleJavaScriptMinifier:116] (/o/dynamic-data-mapping-form-renderer/js/soy_template_util.js:22): Parse error. syntax error
19:19:15,700 ERROR [http-nio-8080-exec-3][GoogleJavaScriptMinifier:129] {0} error(s), {1} warning(s)
```
I disabled minifier and then it worked. Any ideas?

**Comment by leoadb** [comment]
@vicnate5 we are probably missing something in the JavaScript. I’m going to run checkstyle tool made by Nate to see what’s going on.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Forwarded to BChan now that the subrepo was merged
https://github.com/brianchandotcom/liferay-portal/pull/52013

**Pull request closed without merging**
