### PR TITLE
LRQA-46630 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-46630

### CODE REVIEW

**Comment by vicnate5** [comment]
Please import the `Ignore` class and update this pull

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
@vicnate5, no backport needed. Test doesn't exist in 7.1.x branch.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68498

**Pull request closed without merging**
