### PR TITLE
Add gogo shell test

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-53802

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance:nocompile

**Comment by koor4356** [comment]
ci:open

**Comment by koor4356** [comment]
ci:reopen

**Comment by koor4356** [comment]
ci:test:nocompile

**Comment by koor4356** [comment]
ci:reopen

**Comment by koor4356** [comment]
ci:test:acceptance

**Comment by koor4356** [comment]
Falling because of https://issues.liferay.com/browse/LRCI-822. It is good to merge since this is not an acceptance test.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/82008
https://github.com/brianchandotcom/liferay-portal-ee/pull/28082
https://github.com/brianchandotcom/liferay-portal-ee/pull/28081

**Pull request closed without merging**
