### PR TITLE
LRQA-79222 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-79222

This is to persist the docker database properties for the scripts.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129426/commits/f93bd3b424dbfcdfc72f3a26d75edcccf975dff1

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/129426

**Pull request closed without merging**
