### PR TITLE
master-qa-18029

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-18029

### CODE REVIEW

**Comment by ctampoya** [comment]
@kmaria Due to https://issues.liferay.com/browse/LPS-59183, I removed the function that asserts the _Publish to Live button_ is not present (commit  1cea407). Discussed the fix with @evannagayama

**Comment by vicnate5** [comment]
@ctampoya @kmaria I can also confirm the button should be present. This was something I discussed with the staging devs.

**Comment by vicnate5** [comment]
Added use case description message and additional assert at the end of the test.

**Comment by vicnate5** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/956

**Pull request closed without merging**
