### PR TITLE
LPS-171012 Uniform Automated test | Add CheckUpgradeDebugOptions testcase

### PR DESCRIPTION
**Pull request by lucasperj**
Issue link: [LPS-171012](https://issues.liferay.com/browse/LPS-171012)

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:upgrade:nocompile

**Comment by vicnate5** [comment]
@lucasperj Can you please review these and resend?

1. Please give unique failure messages. Instead of `JVM arguments are not present`, you can do `timeout {send_user "\"agentlib:jdwp=transport=dt_socket,address=8001,server=y,suspend=y\" debug output is not present";exit 2}`
2. I noticed that SF is not working correctly on DatabaseUpgradeClient.testcase. The tests should be sorted by name, and there is a mix of TAB and 4 SPACES usage. I suspect SF is configured to ignore this file. See source-formatter.properties files. I can explain more if this gets confusing to investigate.
3. Most importantly, when I run the upgrade client locally with --debug, it hangs on `Listening for transport dt_socket at address: 8001`. Is this expected? Is the user expected to attached a debugger? Once we figure out why it isn't working locally, we should have the test also confirm the upgrade completes with debug enabled (unless we do need a debugger to test..)

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:test:upgrade:nocompile

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
See https://github.com/vicnate5/liferay-portal/pull/2256

**Pull request closed without merging**
