### PR TITLE
LPS-65949 The "Disable" checkbox now works on the repeated Date fields

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
@brunobasto @thiago-rocha I have a couple questions about this pull and the disable checkbox

1. Why does this functionality exist? What is the use case for a user disabling the checkbox?
2. The disabled checkbox still shows up in the list record and when editing the record. Why?
3. The "disable" option does not exist when editing the record. This looks like a bug.

**Comment by brunobasto** [comment]
@vicnate5,

I'm not sure why or when this functionality was introduced. We may need to talk to the WCM team to figure this out.

**Comment by vicnate5** [comment]
@brunobasto I spoke the WCM QA team and they don't know about this.

@epgarcia Would you be able to tell us more about the field disable feature?

**Comment by epgarcia** [comment]
Hi @vicnate5 

As of LPS-48138 date fields are allowed to be empty (nullable). In LPS-56907 a checkbox was added to allow disabling the field in case it's declared as nullable. 

As far as I can tell, these changes allow having optional date fields. In case those date fields are filled automatically, they can be marked as disabled. But please refer to those tickets and their reporters for the actual use cases. 

Regards

**Comment by vicnate5** [comment]
I tested this manually, but will not be adding a test for it due to https://issues.liferay.com/browse/LPS-66957. After looking into the purpose of the disable for the date field it seems that this feature is not needed in DDL, or Web Content, or DM. But I figured it would not hurt to merge this for now.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41218

**Pull request closed without merging**
