### PR TITLE
master-qa-52003

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52003

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Waiting for https://issues.liferay.com/browse/LRQA-52002 before I merge this. Going to add the test case to the new FriendlyURL-specific testcase file from that ticket.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you rebase this on https://github.com/brianchandotcom/liferay-portal/pull/79666 and move the test to `FriendlyURL.testcase`?

**Pull request closed without merging**
