### PR TITLE
LPS-74571 SF

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @vicnate5, I talked to @marco-leo and he isn't sure why the CI is failing (or running) here... @jpince, @iovaneale, any idea of what's going on?

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, @pat270, I've managed to reproduce this, and as we suspected, the commerce theme won't compile due to the changes. 

@jpince, it would be ideal if we didn't have to deal with this, since commerce shouldn't be a concern in this scenario at this point. We will need to update their theme, but we can't do it without breaking it because it will be missing the changes from this PR. And we can't push the changes in this PR without breaking the theme...

**Pull request closed without merging**
