### PR TITLE
LPS-67025 Change test data and disable a test for now. Once the UI for form's rules gets done this test will be restructured and reenabled.

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 Is this real ? I tend to think that it's not related.

**Comment by vicnate5** [comment]
@leoadb A regression not merged, this isn't due to your changes

**Comment by leoadb** [comment]
@vicnate5 Thanks !! You can forward to Brian when you finish, if it's OK.

Em seg, 15 de ago de 2016 19:18, Victor Ware <notifications@github.com>
escreveu:

**Comment by vicnate5** [comment]
@leoadb Unfortunately, I do see a regression on this pull. The user cannot access the configurations in System Settings.

Steps to Reproduce:
1. Go to Control Panel > System Settings
2. Open "Apache Felix Declarative Service Implementation"

```
00:08:46,832 ERROR [http-nio-8080-exec-7][render_portlet_jsp:131] null
java.lang.NumberFormatException: For input string: "["1"]"
       	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
       	at java.lang.Integer.parseInt(Integer.java:580)
       	at java.lang.Integer.valueOf(Integer.java:766)
       	at com.liferay.dynamic.data.mapping.form.evaluator.internal.rules.DDMFormRuleEvaluatorHelper.createDDMFormFieldEvaluationResult(DDMFormRuleEvaluatorHelper.java:124)
       	at com.liferay.dynamic.data.mapping.form.evaluator.internal.rules.DDMFormRuleEvaluatorHelper.createDDMFormFieldRuleEvaluationResult(DDMFormRuleEvaluatorHelper.java:154)
       	at com.liferay.dynamic.data.mapping.form.evaluator.internal.rules.DDMFormRuleEvaluatorHelper.addDDMFormFieldRuleEvaluationResults(DDMFormRuleEvaluatorHelper.java:96)
       	at com.liferay.dynamic.data.mapping.form.evaluator.internal.rules.DDMFormRuleEvaluatorHelper.evaluate(DDMFormRuleEvaluatorHelper.java:69)
       	at com.liferay.dynamic.data.mapping.form.evaluator.internal.DDMFormEvaluatorImpl.evaluate(DDMFormEvaluatorImpl.java:55)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory._createDDMFormEvaluationResult(DDMFormPagesTemplateContextFactory.java:287)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createFieldTemplateContext(DDMFormPagesTemplateContextFactory.java:164)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createFieldsTemplateContext(DDMFormPagesTemplateContextFactory.java:156)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createColumnTemplateContext(DDMFormPagesTemplateContextFactory.java:125)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createColumnsTemplateContext(DDMFormPagesTemplateContextFactory.java:112)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createRowTemplateContext(DDMFormPagesTemplateContextFactory.java:238)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createRowsTemplateContext(DDMFormPagesTemplateContextFactory.java:225)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createPageTemplateContext(DDMFormPagesTemplateContextFactory.java:203)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.createPagesTemplateContext(DDMFormPagesTemplateContextFactory.java:186)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.create(DDMFormPagesTemplateContextFactory.java:79)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormTemplateContextFactoryImpl.getPages(DDMFormTemplateContextFactoryImpl.java:196)
       	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormTemplateContextFactoryImpl.doCreate(DDMFormTemplateContextFactoryImpl.java:121)
```

**Comment by leoadb** [comment]
@vicnate5 I appreciate your time catching this. It's a critical issue we are trying to push, it replaces the form evaluation by the new rule engine. Thanks a lot !!!

**Pull request closed without merging**
