### PR TITLE
LRQA-62584 Simplify since this is the only current use case

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-62584

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by koor4356** [comment]
@vicnate5 This passed and looked good. no need for the macros. Thank you!

**Comment by vicnate5** [comment]
Testing backport https://github.com/vicnate5/liferay-portal-ee/pull/439

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 Sorry for the delay on this, I was trying out some other cleanups on this code. I should be able to merge this tomorrow.

**Pull request closed without merging**
