### PR TITLE
master-qa-30719

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-30719

cc @diogo-lins

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/47007

**Pull request closed without merging**
