### PR TITLE
LPS-103034 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Testing on Brian's origin @achaparro

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@achaparro going to run one more test suite

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@achaparro Couple issues found on the latest test results:

Service builder test caught some version increases needed:
Search "VERSION INCREASE REQUIRED"
https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/321394/AXIS_VARIABLE=0,label_exp=!master/consoleText

SF with KaleoFormsServiceUpgrade
https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/343546/AXIS_VARIABLE=0,label_exp=!master/consoleText

Good news is that I found no functional failures in the other tests.

**Comment by achaparro** [comment]
Thanks @vicnate5 
Tomorrow I will send another pull

**Pull request closed without merging**
