### PR TITLE
LPS-62488 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
Hey @vicnate5 @ctampoya,

@rafaprax applied some lexicon rules to DDL/DDM/Forms. I'm afraid this will break some tests.

Could you please double check?

Thanks

### CODE REVIEW

**Comment by marcellustavares** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/35392 since there're no broken tests.

**Comment by marcellustavares** [comment]
Reopened b/c we got different test results in brianchandotcom.

**Comment by vicnate5** [comment]
@marcellustavares I don't see any BP tests failing on this pull. Test failures are on unrelated. You still want me to do something with this? QA cleaned up the PR tester yesterday. Maybe we retest?

**Comment by vicnate5** [comment]
@marcellustavares I see the failures on BChan's pull. This is odd.

**Comment by marcellustavares** [comment]
I'll resend.

**Pull request closed without merging**
